### ISSUE TITLE
instrument PrecipitateParticle.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#104]
ShakerParticles (the container type for shaker particles) has basic support for saving and loading the state of the particles.  Why is this support not necessary for Precipitate (the container type for precipitate particles)?

**Comment by samreid** [comment]
We will probably need to add support for save/load precipitate particles so that the sim can be loaded from an arbitrary state.  We can reassign this issues once we are working on together again, I'm working on other things so unassigning for now.

**Comment by pixelzoom** [comment]
Since beers-law-lab has now been fully instrumented, presumably it's time to revisit this.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
Currently, the number of precipitate particles will be correct, but the exact positions of the precipitate particles will be incorrect.  Is it essential to get the exact location of all the precipitate particles correct?  I'm not sure, but will leave this assigned to me for investigation.

**Comment by samreid** [comment]
The solution to this problem will be to instrument PrecipitateParticle.js, so I'll rename the issue.

**Comment by samreid** [comment]
Instrumentation complete in the above commits.  Working properly in state mirror and state load, tested by creating patterns of precipitate and confirming they are loaded back properly.  Like #103, it would be good for @pixelzoom to confirm the beers-law-lab repo changes to make sure I didn't miss something important.

**Comment by pixelzoom** [comment]
Inspected commits, I don't see anything amiss. Closing.
