### ISSUE TITLE
branch: together

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#105]
Work on https://github.com/phetsims/beers-law-lab/issues/99 was put on hold due to difficulty in factoring out together API declarations that are used from the same screen in multiple sims.  In https://github.com/phetsims/together/issues/130, @samreid suggested how to factor out the code.  I put together a solution and discussed it briefly with @jbphet, who suggested that I commit it to a branch until it can be reviewed and tested, since metacog may require a new snapshot deliverable in the near future.  I would have liked to name this branch "tandem" but that was already taken here: https://github.com/phetsims/beers-law-lab/issues/97

**Comment by pixelzoom** [comment]
Can @samreid or @jbphet briefly describe the approach, and whether it required changes to together/tandem?

**Comment by pixelzoom** [comment]
Never mind, looks like there's a description in https://github.com/phetsims/together/issues/130#issuecomment-108606922.

**Comment by pixelzoom** [comment]
Does this branch require the "beers-law-lab" branch of together, mentioned here: https://github.com/phetsims/together/issues/134?  Confusing that the branches have different names (would be nice if they had the same name), and neither issue explicitly mentioned this dependency.

**Comment by pixelzoom** [comment]
When phetsims/beers-law-lab#99 and phetsims/beers-law-lab#105 are completed, this branch can presumably be deleted.

**Comment by samreid** [comment]
> Does this branch require the "beers-law-lab" branch of together,

To run beers-law-lab with concentration fully instrumented and ready for the 2nd screen instrumentation, you need the following branches:

together: beers-law-lab
beers-law-lab: together

My hope is that these will be short-lived branches, just long enough to verify and test that they don't disturb anything for concentration, which may need to be re-released for metacog.

**Comment by samreid** [comment]
I don't have plans to work on this branch at the moment, unassigning.

**Comment by samreid** [comment]
I deleted the branch during work in https://github.com/phetsims/together/issues/130 .  Please be advised I have only deleted the remote branches and local branches will have to be deleted by each developer (or re-clone the repo).

**Comment by samreid** [comment]
Reassigned to @pixelzoom as a reminder to remove local branches. Close if there is nothing else to do here.

**Comment by pixelzoom** [comment]
Got it. Closing.
