### ISSUE TITLE
branch: label-set-demo

### ISSUE THREAD

**Issue by jbphet** [phetsims/beers-law-lab#107]
This branch was created to support a demo, requested by @ariel-phet, where it is possible to override the label on the shaker using a query parameter.  See https://github.com/phetsims/concentration/issues/43 for more information.

**Comment by pixelzoom** [comment]
According to @ariel-phet in https://github.com/phetsims/concentration/issues/43#issuecomment-131590731:
>  it can be totally be done as a one off, and discarded. I don't want to add it to the main simulation.

@ariel-phet @jbphet Is there any value in keeping this branch, or can it now be deleted?  The demo date was 8/17/15, over 2 years ago.

**Comment by jbphet** [comment]
Since this is now pretty straightforward to do through PhET-iO, I think it's safe to delete the branch, so I've done so.  Closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
