### ISSUE TITLE
concentration readout always 0

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/beers-law-lab#108]
See screenshot:

![bll-always-0](https://cloud.githubusercontent.com/assets/480878/9375028/472877aa-46b9-11e5-8db8-cb8ae6fb58bc.PNG)

You can switch solutions, and it is always 0 (sometimes with different units it seems). Different from online version.

**Comment by pixelzoom** [comment]
It's also not updating (displayed value remains 0) when moving the slider.

**Comment by pixelzoom** [comment]
Fixed. This was introduced 0n 6/25/15 in @5e74b67, when I switched to using dot.Util.toFixed. It has never appeared in a published version.  Thanks @jonathanolson for noticing this.  Closing.
