### ISSUE TITLE
Consider reducing size of radio buttons

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/beers-law-lab#109]
It seems the visual size of the radio buttons in this sim is a bit large, though the touch area is obviously nice. (compared to what we seem to have settled upon these days). We might consider reducing the size when we republish.

**Comment by pixelzoom** [comment]
Example of the size you'd prefer, for reference?

**Comment by ariel-phet** [comment]
RPAL looks right to me.

**Comment by pixelzoom** [comment]
Reduced radius of radio buttons in this dev version:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-dev.4/beers-law-lab_en.html

Compare to RPAL:
http://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_en.html

Assigning to @ariel-phet to verify.

**Comment by ariel-phet** [comment]
Looks good, except the "preset" and "variable" radio buttons on the beer's law screen, those still look large.

**Comment by pixelzoom** [comment]
I hate you JavaScript. Syntax error that it just completely ignored. But I should have noticed visually. 

Here's another dev version:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-dev.5/beers-law-lab_en.html

**Comment by ariel-phet** [comment]
Hate understood...looks great now. Closing.
