### ISSUE TITLE
use ProbeNode instead of images

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#111]
In https://github.com/phetsims/bending-light/issues/165 @pixelzoom suggested factoring out the light sensor node "probe" for reuse in other sims.  I have generalized it and created a demo in scenery-phet's example launcher in https://github.com/phetsims/bending-light/issues/165 .  That should all be reviewed by someone other than @samreid.  After the review is complete, Beers Law Lab should be rewritten to use the new LightSensorNode.

**Comment by samreid** [comment]
The name of the image to be replaced is at-detector-probe.png.  When I tried replacing:

```js
    var imageNode = new Image( probeImage );
    thisNode.addChild( imageNode );
    imageNode.x = -imageNode.width / 2;
    imageNode.y = -PROBE_CENTER_Y_OFFSET;
```
with 

```js
    var imageNode = new LightSensorNode( { scale: 1.05 } );
    thisNode.addChild( imageNode );
```
in ATDetectorNode.js, things look pretty good.  I made a before/after screencast to depict the visual differences.  It seems like both sensors intercept the light in the same way as well.

![intensity-sensor](https://cloud.githubusercontent.com/assets/679486/9637597/f2aef6a8-515e-11e5-8b4e-442808328358.gif)

**Comment by samreid** [comment]
If it is important for the height to exactly match the predecessor, the height can be adjusted independently in the options.

**Comment by pixelzoom** [comment]
It's mainly important for the center of the probe to be in the same place.

**Comment by pixelzoom** [comment]
LightSensorNode has a ways to go before I would add it to beers-law-lab, see review comments in https://github.com/phetsims/bending-light/issues/165#issuecomment-137838691.   Highly recommended to generalize it so that it can be used for both the AT Detector probe and Concentration meter probe - the shapes aren't that different.

**Comment by pixelzoom** [comment]
Assigning this back to @samreid until work is completed in phetsims/bending-light#165. Please assign back to me when you're done.

**Comment by samreid** [comment]
As far as I know, the outstanding probe node issues are awaiting feedback.  I'll reassign this to @pixelzoom as well.

**Comment by pixelzoom** [comment]
To approximate the image that was used in beers-law-lab, I tried these options to ProbeNode in beers-law-lab.ATDetector:

```js
{
  radius: 55,
  innerRadius: 40,
  handleWidth: 68,
  handleHeight: 60,
  handleCornerRadius: 20,
  lightAngle: 1.25 * Math.PI,
  color: 'rgb(8,133,54)'
}
```

Here's a comparison of the image file (left) and ProbeNode (right). The dimensions of the probes shown are identical (110x171).

![screenshot_15](https://cloud.githubusercontent.com/assets/3046552/10143630/8bef9a08-65d6-11e5-8367-ce598be479d7.png)

I could not duplicate the shape, particularly where the handle meets the surround, which is more tapered in the image file. This difference in is probably acceptable (though a designer will need to approve). 

The shading, however, is inferior. ProbeNode looks flatter. There's not as much of a specular highlight affect in general, and the bevel around the handle is barely visible. So I think ProbeNode needs some work here. This may be related to https://github.com/phetsims/scenery-phet/issues/183 or some other GitHub issue (there are several issue related to ProbeNode generalization).

I had intended to also use ProbeNode for the probe in ConcentrationMeterNode, but I'm going to hold off on that until we decide how to proceed. Assigning to @samreid for thoughts.

**Comment by pixelzoom** [comment]
Note to self: BeersLaw-screen-icon.png will also need to be recreated, because it shows the AT probe, which now looks slightly different.

**Comment by pixelzoom** [comment]
@samreid If you don't agree that the shading needs to be improved, feel free to run it by @ariel-phet or one of the designers.

**Comment by pixelzoom** [comment]
beers-law-lab-screenshot.png will also need to be regenerated, since it also shows the AT probe.

**Comment by ariel-phet** [comment]
@pixelzoom @samreid - agreed that shape is totally acceptable

agreed with @pixelzoom that shading should be improved

**Comment by samreid** [comment]
I'm not sure how to create the desired shading, I added a developer-meeting label to see if anyone has ideas about that.

**Comment by pixelzoom** [comment]
9/30/15 dev meeting notes:
• Some developers think this looks ok.
• Look at ShadedRectangle to see how shading was done, try to match that.
• @jonathanolson and @samreid will look at improving gradient look.
• I will revert changes to beers-law-lab and look at this after redeploy.

**Comment by pixelzoom** [comment]
Reverted to using an image. Will revisit this issue after S2015R.

**Comment by samreid** [comment]
The ProbeNode got better shading in https://github.com/phetsims/scenery-phet/issues/192 and is ready for re-evaluation for usage in Beer's Law Lab and other sims.

**Comment by pixelzoom** [comment]
The benefits to switching to ProbeNode are (1) it will eliminate 2 image files, (2) it will exercise ProbeNode.  The cost is a 1-2 hours, mostly spent trying to make ProbeNode look like the image files, and potential destabilization.  

Questions for @ariel-phet: 
• Do you want this done for S2105R?
• Do you want this done at all?

**Comment by ariel-phet** [comment]
@pixelzoom seems worth a shot in terms of exercising ProbeNode.

**Comment by pixelzoom** [comment]
@ariel-phet And do you want that done for S2015R?

**Comment by pixelzoom** [comment]
In Skype conversation with @ariel-phet, he would like this done for S2105R.

**Comment by pixelzoom** [comment]
Note that a change to ProbeNode was required to completed this, https://github.com/phetsims/scenery-phet/commit/fa539b27b2162fa9a10c9bfc60d64c4e2be4d374.  So the RC for beers-law-lab will need to use master of common-code repos.

**Comment by samreid** [comment]
> So the RC for beers-law-lab will need to use master of common-code repos.

**Or** it could use a tiny, safe branch (one non-comment line changed) from the tested SHA.

**Comment by pixelzoom** [comment]
This dev version uses ProbeNode:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-dev.6/beers-law-lab_en.html

Here's the published version (1.2.3), which uses image files:
https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_en.html

To my eye, using ProbeNode results in a much flatter look. But perhaps that's OK.  In any case, there's nothing else that the client (in this case, beers-law-lab) can do to make ProbeNode look more like the image files.

@ariel-phet please review this change.  Examine the concentration probe (screen 1) and AT detector probes (screen 2).  If this is OK, close this issue.  Otherwise describe additional work desired.

**Comment by pixelzoom** [comment]
@ariel-phet Please also advise on whether the screenshot for beers-law-lab and concentration need to be recreated, since the screenshots show the probes.

**Comment by pixelzoom** [comment]
> Or it could use a tiny, safe branch (one non-comment line changed) from the tested SHA.

Branching common repos is outside PhET's standard process for publishing sims. If we need to do that for something as trivial as this change, then we should rethink the process.

**Comment by pixelzoom** [comment]
@ariel-phet requested that the specular highlight be toned down, which I did in https://github.com/phetsims/scenery-phet/commit/33f3162822238368ddac713bf7d4c6c7bcddee86 by increasing the transparency of the 'white' portion of the linear gradient in ProbeNode.

**Comment by ariel-phet** [comment]
@pixelzoom looking good to me now, no need to update screenshots
