### ISSUE TITLE
Button on Solution Dripper is Limited with Double String and Unusable with Long String

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/beers-law-lab#114]
Test device: Mac, personal

Operating System: OS X 10.10.5

Browser: Safari 9.0.1 (10601.2.7.2)

Problem description: I first noticed this issue when testing IE11 on Win 7 and am able to reproduce it on my Mac with Safari. The boundaries around the text for double and long string texts affect the ability to use the solution dropper. For double, only half of the button is active for using the dropper. For long, the dropper seems to be completely unusable.  

Steps to reproduce: Test long and double strings. Select the Solution dropper on the Concentration screen.

Severity:

Screenshots: 
long: 
![screen shot 2015-10-29 at 11 15 22 am](https://cloud.githubusercontent.com/assets/12610678/10826356/06c60d64-7e2f-11e5-8ec9-a3cb85ef4694.jpg)

double: https://drive.google.com/file/d/0B_TAL-jnJOoKR1BscUt6WUZoUE0/view?usp=sharing 

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-rc.1/beers-law-lab_en.html?stringTest=long
Version: 1.3.0-rc.1 2015-10-28 17:08:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7
Language: en-us
Window: 1238x667
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"ea354263","branch":"master"},"babel":{"sha":"d352eb6d","branch":"master"},"beers-law-lab":{"sha":"79f505c0","branch":"1.3"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"778caa53","branch":"master"},"dot":{"sha":"03415417","branch":"master"},"joist":{"sha":"8d87df6c","branch":"master"},"kite":{"sha":"7f2df7e9","branch":"master"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"6eab326e","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"1606cafc","branch":"master"},"scenery-phet":{"sha":"33f31628","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"f678dd20","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by pixelzoom** [comment]
This is a problem with scenery-phet.EyeDropperNode, it should be limiting the length of the label to the glass part of the dropper.  This will require a change to common code, so the next RC will need to use master of all repos.

**Comment by pixelzoom** [comment]
Good news, the issues is actually with BLLDropperNode, which decorates scenery-phet.EyeDropperNode with a label.  So all changes here will be in sim code, which can be patched into the 1.3 branch.

**Comment by pixelzoom** [comment]
Fixed. Here's what it looks like with stringTest=double and stringTest=long.

![screenshot_41](https://cloud.githubusercontent.com/assets/3046552/10827904/fcafcaf6-7e36-11e5-826a-77bdbb2ba7dd.png)

![screenshot_42](https://cloud.githubusercontent.com/assets/3046552/10827905/ff6defca-7e36-11e5-931c-a559b9f92ae0.png)

So the label will no longer overlap the button, as it's size is now limited to the dropper's glass.

This fix affects the Concentration screen, and will appear in Beer's Law Lab 1.3.0-rc.2 and Concentration 1.2.0-rc.2.
