### ISSUE TITLE
add QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#117]
@ariel-phet This sim currently has no QA credits. Please specify the QA credits, ordered alphabetically by last name.  These same credits will be used in beers-law-lab and concentration.

**Comment by ariel-phet** [comment]
Steele Dalton,  Bryce Griebenow, Elise Morgan, Oliver Orejola, Benjamin Roberts, Bryan Yoelin

**Comment by ariel-phet** [comment]
@pixelzoom for all the open "add QA credits" issues assigned to me can you use the above list. I will let you know if anything changes, but all these QA members are likely to help out in one way or another, or have in the past.
