### ISSUE TITLE
Fix the touch area for the Concentration Meter Probe Node

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#119]
Tracked in https://github.com/phetsims/scenery-phet/issues/204 but I wanted to create an issue here in Beer's Law Lab because (a) the code change to address this issue may be implemented here in beers-law-lab and (b) it was said that:

> This must be fixed before publishing additional RCs for beers-law-lab (phetsims/tasks#40) and concentration (phetsims/tasks#406). Publication of these is desired ASAP on 11/3/15, so high priority.

**Comment by samreid** [comment]
@pixelzoom and I just fixed this in the scenery-phet issue, closing.

**Comment by pixelzoom** [comment]
This was fixed in master in https://github.com/phetsims/beers-law-lab/commit/259835a9771aa613d9ef164c8519b1d99bc8bb1e.

Reopening because it needs to be patched into 1.3 branch.

**Comment by pixelzoom** [comment]
1.3 branch patched, closing.
