### ISSUE TITLE
Reset button does not remove solute particles that are in mid-air.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/beers-law-lab#122]
This issue occurs on multiple browsers and OS: Windows, OS X, IOS.
Also occurs in the latest RC of Concentration: http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.0-rc.2/concentration_en.html

Test device: Personal Macbook OSX 10.11
Operating System: OSX 10.11
Browser: Safari 9
Problem description: Identical to old issue https://github.com/phetsims/beers-law-lab/issues/68 where instead of the "Remove Solute" button use the "Reset" button. 
The Reset button does not remove solute particles that are in mid-air, does not completely reset the state of the sim.

Steps to reproduce:
Open sim & Select Concentration Screen
Move Shaker so that solute particles fall down
Hit Reset (Particles will remain on screen and affect the concentration of fluid as normally)

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Beer's Law Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-rc.2/beers-law-lab_en.html
Version: 1.3.0-rc.2 2015-11-03 16:08:34 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"202abb27","branch":"master"},"babel":{"sha":"6571b3e0","branch":"master"},"beers-law-lab":{"sha":"96f30213","branch":"1.3"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"d13a1dda","branch":"master"},"dot":{"sha":"b9e3c1e0","branch":"master"},"joist":{"sha":"5d0e22ec","branch":"master"},"kite":{"sha":"7f2df7e9","branch":"master"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"12bc1541","branch":"master"},"phetcommon":{"sha":"8f0f79d2","branch":"master"},"scenery":{"sha":"6ec044ac","branch":"master"},"scenery-phet":{"sha":"60ccb6e8","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"f678dd20","branch":"master"},"tandem":{"sha":"210ece84","branch":"master"}}

**Comment by samreid** [comment]
I also reproduced this problem.

**Comment by pixelzoom** [comment]
Fixed in 1.3 and master. This fix was a trivial fix, so (at the concluding of 1.3.0-rc.2 testing) we'll have to evaluate whether another RC is warranted.  Closing.

**Comment by pixelzoom** [comment]
This was a very minor fix, and there were no other issues found for 1.3.0-rc.2.  So I'm going to publish a dev version (1.3.0-dev.7) to verify this fix.  If all goes well, then we can publish 1.3.0 off of the 1.3 branch.

**Comment by pixelzoom** [comment]
@ariel-phet says that I can just verify this (which I have), no need for a dev version.
