### ISSUE TITLE
Remaining 1.3.0 redeploy items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/beers-law-lab#123]
Remaining issues from check list:

- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by pixelzoom** [comment]
This is related to Beer's Law Lab 1.3.0 redeploy.

**Comment by ariel-phet** [comment]
The primer projects are being covered by https://github.com/phetsims/tasks/issues/429 and https://github.com/phetsims/tasks/issues/430 closing
