### ISSUE TITLE
use NumberControl for concentration

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#126]
In https://github.com/phetsims/together/issues/250#issuecomment-166326831, @samreid said this about instrumenting ConcentrationSlider for PhET-iO:

> The ConcentrationSlider was particularly expensive to instrument because:
> 
> • it is a custom component (doesn't use common code slider)
> • it can be dragged by the track or by the knob, each of which requires 3 pairs of emitters (for a total of 12 emitters)
> • it switches input listeners dynamically (this last issue minor compared to previous items)

ConcentrationSlider likely pre-dates HSlider, and I don't see anything that wouldn't be a desirable feature in HSlider.   So I think that it would be preferable to use HSlider in ConcentrationSlider, enhancing HSlider where necessary.

**Comment by samreid** [comment]
Good suggestion @pixelzoom, :+1:

**Comment by pixelzoom** [comment]
Things in HSlider that would need to be mutable

• value range
• tick marks
• track fill

**Comment by samreid** [comment]
Brainstorming here: 

as an alternative to making immutable parts of HSlider mutable, we could instead create one instance of HSlider for each Solution

Just wanted to run this past @pixelzoom as a possibility in case he hadn't considered it, and in the end making HSlider mutable may be best if not too much work (or increase of complexity).

**Comment by pixelzoom** [comment]
> as an alternative to making immutable parts of HSlider mutable, we could instead create one instance of HSlider for each Solution

I'd considered a variation of that: Replacing the slider each time the solution changes. If there's no performance hit, that might be preferable to creating 8 sliders.  We'll see...

**Comment by pixelzoom** [comment]
PhET-iO instrumentation of ConcentrationSlider has been merged into master, and I don't see the "particularly expensive" instrumentation that @samreid described in https://github.com/phetsims/beers-law-lab/issues/126#issue-123322284.  All I see is the instrumentation of the plus/minus buttons. @samreid what am I missing?

**Comment by pixelzoom** [comment]
Proposed approach:
• make no modifications to HSlider, use "as is"
• move arrow buttons from ConcentrationSlider to ConcentrationControl
• replace ConcentrationSlider with HSlider in ConcentrationControl
• when solutionProperty changes in ConcentrationControl, dispose of and replace HSlider
• delete ConcentrationSlider.js

**Comment by pixelzoom** [comment]
If the HSlider is replaced each time the solution changes, how do we handle the tandem associated with the slider? Reuse it, so that it refers to the instance that currently exists? Or create a new tandem (with same id?) each time a new HSlider is created?

**Comment by pixelzoom** [comment]
If we implement the approach proposed in https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-166739145, then this bit in beers-law-lab-api.js:

```js
      solutionControls: {

          // TSolute Combo Box
          comboBox: TComboBox( TSolute ).extend( {
            listVisible: TProperty( TBoolean )
          } ),
          concentrationControl: {
            slider: TConcentrationSlider.extend( {
              plusButton: TButton,
              minusButton: TButton
            } )
          }
```

will change to something like:

```js
      solutionControls: {

          // TSolute Combo Box
          comboBox: TComboBox( TSolute ).extend( {
            listVisible: TProperty( TBoolean )
          } ),
          concentrationControl: {
            slider: TSlider,
              plusButton: TButton,
              minusButton: TButton
          }
```

This is probably preferable, because the plus/minus buttons don't belong under the slider.

**Comment by samreid** [comment]
What about using NumberSlider instead of a custom implementation of HSlider + Arrow buttons?

**Comment by pixelzoom** [comment]
What is NumberSlider? Do you mean NumberControl?

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
Yes, NumberControl.

**Comment by pixelzoom** [comment]
NumberControl would require an alternative layout option. It's layout currently looks like this:

![screenshot_97](https://cloud.githubusercontent.com/assets/3046552/11967294/ed190776-a8be-11e5-81d4-f2aa8daaeafd.png)

ConcentrationControl looks like this:

![screenshot_98](https://cloud.githubusercontent.com/assets/3046552/11967301/f4b175a4-a8be-11e5-8a66-e224e26ac8e0.png)

**Comment by pixelzoom** [comment]
NumberControl would require an alternative layout option. Its layout currently looks like this:

![screenshot_97](https://cloud.githubusercontent.com/assets/3046552/11967294/ed190776-a8be-11e5-81d4-f2aa8daaeafd.png)

ConcentrationControl looks like this:

![screenshot_98](https://cloud.githubusercontent.com/assets/3046552/11967301/f4b175a4-a8be-11e5-8a66-e224e26ac8e0.png)

 Would you describe this as `orientation: 'vertical'` versus `orientation: 'horiztonal'` ?

**Comment by samreid** [comment]
`orientation: 'vertical'` and `orientation: 'horizontal'` will match our existing precedents nicely.  However, it's unclear to me why the word `orientation` has been used instead of `layout`.  For instance, for RadioButtonGroup, why is it `orientation: 'vertical'` instead of `layout: 'vertical'`?  In any case, it seems good to proceed with `orientation: 'vertical'` and address all orientation keys together, if at all.

**Comment by pixelzoom** [comment]
I believe the term `orientation` is typically used when there's a choice between 'horizontal' and 'vertical'.  The term `layout` is much more general.

**Comment by pixelzoom** [comment]
So back to this question: https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-166741682 ... which is a question regardless of whether we use HSlider or NumberControl.   If the control is replaced dynamically to match the solution, what do we do about its associated tandem?

**Comment by samreid** [comment]
> If the HSlider is replaced each time the solution changes, how do we handle the tandem associated with the slider? Reuse it, so that it refers to the instance that currently exists? Or create a new tandem (with same id?) each time a new HSlider is created?

I'd recommend one tandem per slider. If "throwing away" unused sliders instead of storing them in memory, then the process would look like this:
1. create slider for solution A, register with tandem under name solutionASlider
2. user selects another solution
3. un-register the solutionASlider, instantiate the slider for solution B, register with tandem under name solutionBSlider
4. user selects solution A
5. create a new slider for solution A, register with tandem under the name solutionASlider.

Or if lazily creating the sliders they would only need to be registered once.

Shorter answer: one tandem per conceptual component. Actual components can come and go and be assigned to the same tandem.

**Comment by pixelzoom** [comment]
I'm confused by https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-167664828.  

"One tandem per slider" and "One tandem per conceptual component" are very different. And steps 1-5 are for the former, where there are N sliders, one for each solutions, each with a different tandem name. 

But from the user's viewpoint, there is only 1 concentration slider in this sim.  So if we're "trowing away" unused slider, and only 1 concentration slider exists at a time, why not reuse the same tandem name ("concentrationSlider")?  Something like:

```js
if ( concentrationSlider ) {
   concentrationSliderTandem.removeInstance( concentrationSlider );
}
concentrationSlider = new ConcentrationSlider( solution );
concentrationSliderTandem.addInstance( concentrationSlider );
```

Would that work?

**Comment by pixelzoom** [comment]
@samreid and I discussed this. Either of the above examples would work in theory.  I'm partial to  https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-167667955 since it fits the user's conceptual model (1 concentration slider) and since the solution can be interrogated to determine range, units, etc.

**Comment by samreid** [comment]
I'm not convinced that it should be instrumented as a single slider.  When the solution changes, the concentration slider resets to 100 and the units can change.  @pixelzoom's comment from above is that the user's conceptual model is that there is one slider that changes its units, range and gradient.

Not recommending this, but brainstorming how the sim might be different if we wanted to change the UI to make it clear that there was one slider per solution:
1. If the user set slider A to 80 mmol, then slider B to 120 mmol, then went back to slider A, they would see it was still at 80 mmol, making it easy to compare different solutions at different concentrations.  Is there a reason the sim wasn't designed with this feature?
2. (Again, not recommending this) The sim could have been designed so that the old slider faded out and the new slider faded in.  If we had done this, then there would be no issue about the user's conceptual model being 1 concentration slider, right?  So perhaps our decision to show the different sliders in exactly the same place, with no transition leads to the conceptual model that there is only one slider?

**Comment by samreid** [comment]
I should also chime in that it seems like either model (one multi-slider or many sliders) would work, as @pixelzoom pointed out in https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-167680314 , it just changes how they would appear in the instrumentation/data stream, etc.

**Comment by pixelzoom** [comment]
>  So perhaps our decision to show the different sliders in exactly the same place, with no transition leads to the conceptual model that there is only one slider?

I doubt that a typical user can wrap their heads around the concept of a UI control that exists but isn't visible on the screen.  Or that they would perceive there being anything other than 1 concentration slider, regardless of whether it's faded in/out, or whether it retains its previous value for a solution.  We could make the wavelength slider also be per-solution -- do you think they would then realize that there are actually 8 wavelength sliders, and only one of them is visible? 

Also important is that the implementation shouldn't be forced to use 8 sliders.  It's currently implemented as 1 mutable slider. It could just as easily have been implemented as 8 sliders.  And the implementor should have the freedom to use either approach (or change approaches) without impacting the PhET-iO API.  Which is another reason why I advocate for 1 'concentrationSlider' in the data stream.

**Comment by pixelzoom** [comment]
The current API presents a single concentration slider.  Let's see how that goes with the UBC study.

**Comment by pixelzoom** [comment]
@samreid Are you OK with the proposal in https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-170121610?

**Comment by samreid** [comment]
Yes

**Comment by pixelzoom** [comment]
Using HSlider will also presumably give us keyboard navigation, as was the case in Molarity https://github.com/phetsims/molarity/issues/37.  @jessegreenberg is that the case?

**Comment by jessegreenberg** [comment]
@pixelzoom that is correct.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg. dev:ally label added.

**Comment by pixelzoom** [comment]
A11y issues were discussed with @jessegreenberg via Slack.

A11y ignores touch.  Focus is determined via keyboard navigation.  But the user can still use the mouse.  So it's possible set focus to the concentration slider (using the keyboard), then change the solute using the mouse (with no focus change).  Since a new concentration slider may be created, we might want to restore focus to the new concentration slider.  But...

Changing the "selected thing", and then creating a new panel for controlling the thing that is now selected, is a common pattern in PhET sims.  It's unclear how to restore focus in the general case.  And it also seems burdensome to have sim-specific code that needs to worry about focus issues.
Imo "restoring focus" requires a general solution.

@jessegreenberg suggested perhaps something in scenery to address this. Brainstorming, I suggested something like Node `replaceChild( nodeA, nodeB )`, where nodeA is replaced with nodeB in the scene graph, and focus (tandem id? event handling?...) is transferred from nodeA to nodeB.

**Comment by pixelzoom** [comment]
I got pretty far with what I proposed in https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-436764297, not checked in, but see the screenshot below.  The top slider is the original implementation `ConcentrationControl`, which controls whatever solution is selected. The bottom slider is a `NumberControl` that is specific to "Drink Mix".

Two significant problems:

(1) Filling the track with a linear gradient that corresponds to the solution color is a firm requirements. NumberControl currently has no way to set the track fill.  Slider's `trackFillEnabled` option may or may not work with a linear gradient - I've never tried.

(2) Model concentration units are M.  View units depend on the solution.  And the displayed value should be created using `solution.getDisplayConcentration( concentration )`.   NumberControl currently has no way to specify such a transform for the displayed value.

![screenshot_838](https://user-images.githubusercontent.com/3046552/48163184-3e222200-e29c-11e8-96de-2fdd75941358.png)

**Comment by pixelzoom** [comment]
(1) above turned out to be easy.  NumberControl passes all options to Slider, and Slider does work with a LinearGradient track fill.  Screenshot:

![screenshot_839](https://user-images.githubusercontent.com/3046552/48163575-4464ce00-e29d-11e8-8f71-f181433c2c0a.png)

**Comment by pixelzoom** [comment]
(2) above was resolved by using a DynamicProperty to map between model and view concentration values.

**Comment by pixelzoom** [comment]
The new version of `ConcentrationControl` was committed above.  There is now one instance of `ConcentrationControl` per solution, and one instance is made visible depending on which solutions is selected in the combo box.  (There is of course nothing to prevent the client from making more than one, or the wrong one, visible.)

The phetioIDs for the 8 controls are:

```
beersLawLab.beersLawScreen.view.solutionControls.drinkMixConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.cobaltIINitrateConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.cobaltChlorideConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.potassiumDichromateConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.potassiumChromateConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.nickelIIChlorideConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.copperSulfateConcentrationControl
beersLawLab.beersLawScreen.view.solutionControls.potassiumPermanganateConcentrationControl
```

I also added `phetioDocumentation` for each control.  Here's an example from Studio:

![screenshot_841](https://user-images.githubusercontent.com/3046552/48166613-5139ef80-e2a6-11e8-8367-273e8cc7456e.png)

There is one remaining problem to work out.  When the concentration units switch between "mM" and "uM", the width of the control changes.   This doesn't affect usability, but is visually distracting.  There's currently no way to set a fixed width for `NumberDisplay` (the value display used by `NumberControl`), so this will probably involve common-code changes.

**Comment by pixelzoom** [comment]
This also broke https://github.com/phetsims/beers-law-lab/issues/229 (moving the thumb in 5 unit increments), so I'll need to start over on that.

**Comment by pixelzoom** [comment]
Removing the a11y label, since we're now using NumberControl and a11y should be handled therein.

**Comment by pixelzoom** [comment]
Over to @samreid for review.  See https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-436810280 for a summary of what was done.

**Comment by samreid** [comment]
What is the timeline for review?

**Comment by pixelzoom** [comment]
> What is the timeline for review?

Whenever this sim is ready for a new release branch.  No idea when that might be.

**Comment by samreid** [comment]
Instead of this code:

```js
    // Make the control visible for the selected solution
    currentSolutionProperty.link( function( currentSolution ) {
      concentrationControls.forEach( function( concentrationControl ) {
        concentrationControl.visible = ( currentSolution === concentrationControl.solution );
      } );
    } );
```

Would it be appropriate to use `ToggleNode`?

**Comment by pixelzoom** [comment]
> - [ ] I don't understand why the new ConcentrationControl uses solution.concentrationTransform but the old implementation didn't. Maybe I've just missed something.

See https://github.com/phetsims/beers-law-lab/commit/8c222d2c4f1a1d45e6c8df1ed1c0bdee19622605.

`ConcentrationControl` called `getDisplayConcentration`, which called `concentrationTransform.modelToView`:

```js
62 valueDisplay.text = solutionProperty.get().getDisplayConcentration( concentration )
```

And `getDisplayConcentration` was deleted from BeersLawSolution:

```js
    //TODO #126 delete this when ConcentrationControl is rewritten
     // @public
     getDisplayConcentration: function( concentration ) {
       var valueText = Util.toFixed( this.concentrationTransform.modelToView( concentration ), 0 );
       return StringUtils.format( pattern0Value1UnitsString, valueText, this.concentrationTransform.units );
     }
```

**Comment by pixelzoom** [comment]
> - [ ] SolutionControl.js should use ToggleNode

Done in the above commit.

**Comment by pixelzoom** [comment]
Recommendation and question addressed.  Back to @samreid to review answer to his question in https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-438710623.  If that's clear, feel free to close this issue.

**Comment by samreid** [comment]
The newly introduced code for creating `toggleNodeElements` currently reads like this:

```js
    // concentration controls, one for each solution
    var toggleNodeElements = []; // {{value:{BeersLawSolution}, node:{ConcentrationControl}}
    solutions.forEach( function( solution ) {
      toggleNodeElements.push( {
        value: solution,
        node: new ConcentrationControl( solution, {
          visible: false,
          tandem: tandem.createTandem( solution.internalName + 'ConcentrationControl' ),
          phetioDocumentation: 'the concentration control for ' + solution.name
        } )
      } );
    } );
```

This is the perfect opportunity to use `map`:

```js
    // {{value:{BeersLawSolution}, node:{ConcentrationControl}} - concentration controls, one for each solution
    var toggleNodeElements = solutions.map( function( solution ) {
      return {
        value: solution,
        node: new ConcentrationControl( solution, {
          visible: false,
          tandem: tandem.createTandem( solution.internalName + 'ConcentrationControl' ),
          phetioDocumentation: 'the concentration control for ' + solution.name
        } )
      };
    } );
```

Everything else looks great.

**Comment by pixelzoom** [comment]
Done, closing.

**Comment by pixelzoom** [comment]
Reopening because the arrow buttons have apparently never worked. See https://github.com/phetsims/scenery-phet/issues/448#issuecomment-450408651.

**Comment by pixelzoom** [comment]
Move to new issue https://github.com/phetsims/beers-law-lab/issues/233. Closing.
