### ISSUE TITLE
Movable should create tandem for its Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#128]
Example...  In Ruler:

```js
// Ruler.js
function Ruler( length, insets, height, location, dragBounds, tandem ) {
    Movable.call( this, location, dragBounds, tandem.createTandem( 'position' ) );
    ...
}

// Movable.js
function Movable( location, dragBounds, tandem ) {
    this.locationProperty = new Property( location, { tandem: tandem } ); // @public
    ...
}
```

This assumes that Movable only has 1 Property, which could change in the future. And it doesn't match the pattern uses elsewhere, where tandems for Properties are created in the constructor where the Property is instantiated.

The proper patterns is:

```js
// Ruler.js
function Ruler( length, insets, height, location, dragBounds, tandem ) {
    Movable.call( this, location, dragBounds, tandem );
    ...
}

// Movable.js
function Movable( location, dragBounds, tandem ) {
    this.locationProperty = new Property( location, { tandem: tandem.createTandem( 'location' ) } ); // @public
    ...
}
```

This occurs in all subtypes of Movable: ATDetector, Ruler, ConcentrationMeter, Dropper, Shaker.

Assigning to @samreid for comment.

**Comment by samreid** [comment]
Yes, this is a good suggestion.  Note that ConcentrationMeter.js has

```js
    this.body = new Movable( bodyLocation, bodyDragBounds, tandem.createTandem( 'body.location' ) );
    this.probe = new Movable( probeLocation, probeDragBounds, tandem.createTandem( 'probe.location' ) );
```

so the API file will have to be changed (location => position) to match the change.  Please indicate whether I should fix this, or if you would like to.

**Comment by pixelzoom** [comment]
In ConcentrationMeter, the change should be:

```js
this.body = new Movable( bodyLocation, bodyDragBounds, tandem.createTandem( 'body' ) );
this.probe = new Movable( probeLocation, probeDragBounds, tandem.createTandem( 'probe' ) );
```

Yes, please rename location => position.

Yes, please handle the fix.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by pixelzoom** [comment]
@samreid said:
> so the API file will have to be changed (location => position) to match the change. 

The change needs to be the other way around, `position` => `location`, because Movable's Property is named `locationProperty`.

**Comment by pixelzoom** [comment]
I'll take a stab at this, then have @samreid verify.

**Comment by pixelzoom** [comment]
Actually, looks like there's no change necessary in the API file, it's already `location`.

**Comment by pixelzoom** [comment]
Ah... the entry for `ruler` uses `position`, that will need to change to `location`.

**Comment by pixelzoom** [comment]
Consistency, another good reason to change this.

Ruler:
`Movable.call( ..., tandem.createTandem( 'position' ) );`

Dropper:
`Movable.call( ..., tandem.createTandem( 'location' ) );`

So the API entry for `ruler.position` needs to be changed to `ruler.location`.

**Comment by pixelzoom** [comment]
Changes pushed.  I realized that I'm totally unaware of how to test this.  Are there html files somewhere that have the preloads required?  I build with `--brand=phet-io` and it runs OK, but I don't see any data stream. 

Assigning to @samreid  to review, and to clue me in about how to test PhET-iO.

**Comment by samreid** [comment]
We discussed how to test the phet-io simulations today, and there is further documentation about testing in https://github.com/phetsims/together/blob/master/doc/how-to-instrument-a-phet-simulation.md#step-5-test-the-general-wrappers

@pixelzoom can you test and report back?

**Comment by pixelzoom** [comment]
Cannot test due to a error introduced elsewhere, see https://github.com/phetsims/beers-law-lab/issues/135#issuecomment-168040741.

**Comment by pixelzoom** [comment]
I don't see any errors after making this change. But there is *so much* stuff in the data stream that's it's difficult to verify the 'location' tandem for all Movables.  @samreid do you have a technique for verifying specific changes, or do you just run the tests in the together doc and assume everything is OK?

**Comment by pixelzoom** [comment]
And since this is my first attempt at a tandem change, I think it would be good for you to inspect https://github.com/phetsims/beers-law-lab/commit/daac1aa1aa75f53dfb37ee4da00e969eb64c3ace, and confirm that no changes to the API file are needed.

**Comment by samreid** [comment]
> @samreid do you have a technique for verifying specific changes

I would make sure the data stream contains all of the required messages.

**Comment by samreid** [comment]
I reviewed the change sets and tested the data stream for the ruler and dropper, all seems well, closing.
