### ISSUE TITLE
unused tandem param in CuvetteNode.CuvetteDragHandler

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#130]
In CuvetteNode.CuvetteDragHandler:

```js
function CuvetteDragHandler( cuvetteNode, cuvette, modelViewTransform, snapInterval, tandem ) {
```

The `tandem` param is unused. Is this an oversight or can it be removed from the constructor signature?

**Comment by samreid** [comment]
Confirmed, this tandem is unused and can be removed.
