### ISSUE TITLE
when is tandem.addInstance required?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#131]
When is a call to tandem.addInstance required?

For example: CuvetteNode and LightNode are both subtypes of scenery.Node. CuvetteNode has a call to tandem.addInstance at the end of its constructor. LightNode does not. Why are they different?

**Comment by pixelzoom** [comment]
Similar question for SolutionControls. It does not pass its tandem to sun.Panel, and sun.Panel is not instrumented (does not have a `tandem` option).

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
This relates to the unsolved issue of subclassing in tandem registration.

**Comment by samreid** [comment]
LightNode.js does not provide any new instance attributes or methods, it simply calls the LaserPointerNode constructor with values appropriate to Beer's Law Lab.  Hence it does not require (a) suppressing the tandem in the super call and (b) calling its own tandem.addInstance.  In the future, if LightNode adopts properties or methods that must be instrumented, then the steps (a) and (b) should be implemented.

**Comment by pixelzoom** [comment]
Let me take a stab at the general answer to this question.

A call to `tandem.addInstance` is required if the object's entry in the API file has an associated together type. Specifying a together type implies that the client can access an associated instance through that type's API, so we need to have a registered instance. Some examples from beers-law-lab-api.js:

```js
shaker: TDraggableNode.extend( { ... } )
solventFaucet: Faucet.extend( { ... } )
resetAllButton: TResetAllButton 
locationProperty: TProperty( TVector2 )
```

A call to `tandem.addInstance` is *not* required if the object's entry in the API file has no associated type. With no type specified, nothing can be accessed by the client, so no instance needs to be registered.  Some examples from beers-law-lab-api.js:

```js
solution: {  ... }
concentrationMeter: { ... }
solutionControls: { ... }
```

@samreid Do I understand this correctly?

**Comment by samreid** [comment]
Yes, this explanation was perfect.  I copied your answer into the `how-to-instrument-a-phet-simulation.md` file.
