### ISSUE TITLE
should ConcentrationMeter.valueProperty be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#132]
It currently is not. Oversight or intentional?

```js
this.valueProperty = new Property( NaN ); // @public NaN if the meter is not reading a value
```

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
After instrumenting this, I'm seeing odd messages like this (where the value goes from null=>null):

```js
{
  "messageIndex": 6,
  "eventType": "model",
  "togetherID": "beersLawLab.concentrationScreen.concentrationMeter.valueProperty",
  "componentType": "TProperty(TNumber)",
  "event": "changed",
  "time": 1451419438673,
  "parameters": {
    "oldValue": null,
    "newValue": null
  }
}
```

**Comment by samreid** [comment]
I'll commit this instrumentation, but we should still understand these null=>null messages.

**Comment by samreid** [comment]
There are 2 related issues here:

* NaN is being output as "null" in the data stream
* NaN===NaN evaluates to false in Property, so Property keeps sending out spurious messages.

**Comment by samreid** [comment]
Testing stringification, I see:

```
> JSON.stringify({x:NaN},null,2);
"{
  "x": null
}"
```

**Comment by samreid** [comment]
For the stringify issue, it seems common to use a replacer/reviver to address this issue, say serializing NaN as 'NaN', but what if the user wanted to serialize the string 'NaN'? This is documented here: http://stackoverflow.com/questions/21896792/force-json-stringify-to-emit-nan-infinity-or-js-json-lib-that-does-so  Perhaps we must use the type info in the API?

**Comment by samreid** [comment]
To solve the spurious NaN=>NaN messages, perhaps we should add a type NumberProperty or NaNProperty that handles these values properly?

I'm ready for @pixelzoom feedback on the above issues at his convenience.

**Comment by samreid** [comment]
By the way, putting a check for NaN equality in Property solves the data stream issue but breaks the sim in many ways (background is black, things are undraggable, etc).  Very interesting!

**Comment by samreid** [comment]
By the way, here is the areValuesEqual that yielded the behavior described above:

```js
      areValuesEqual: function( a, b ) {
        return a === b || (isNaN( a ) && isNaN( b ));
      },
```

**Comment by pixelzoom** [comment]
How about if we skip this entire `NaN` problem and use `null` to signify that the meter is not reading a value?  This would be for both the concentration meter and AT detector, and would touch these files: ConcentrationMeter, ConcentrationMeterNode, ATDetector, ATDetectorNode.

**Comment by samreid** [comment]
Using null instead of NaN would be a great solution to this problem:

![image](https://cloud.githubusercontent.com/assets/679486/12107092/7605314a-b323-11e5-81eb-7df1f9d9fdcd.png)

Do you want to make this change?  Please assign to me if I should.

**Comment by pixelzoom** [comment]
I changed the representation of "no value" from NaN to null.  Back to @samreid to verify the instrumentation of valueProperty.

**Comment by samreid** [comment]
The data stream looks perfect and there are no longer any spurious messages.
