### ISSUE TITLE
why doesn't EyeDropperNode register its tandem?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#133]
BLLDropperNode is a subtype of scenery-phet.EyeDropperNode.  

BLLDropperNode line 99:

```js
// Supertype registers the momentary button, but not itself, so register here in the subtype.
// No corresponding removeInstance is needed because this object exists for the lifetime of the sim
tandem.addInstance( this );
```

EyeDropperNode line 51:

```js
// Note: EyeDropperNode is not draggable and hence only registers its button with tandem.
tandem: null
```

Why doesn't EyeDropperNode register its tandem? Does a Node only register its tandem if it's interactive? What if interactivity is added to a common-code Node in the future?

**Comment by pixelzoom** [comment]
Related to #131 (when is tandem.addInstance required?)

**Comment by pixelzoom** [comment]
As a counter example...  scenery-phet.FaucetNode is not draggable, but registers its tandem.  And BLLFaucetNode therefore passes the tandem to FaucetNode.  BLLDropperNode and EyeDropperNode have an identical relationship, and identical interactivity - why are they handled differently?

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
The problem is that the dropper should not be registered until the `movableDragHandler` has been assigned.  This is related to the problem of dealing with tandems in subclasses.  In this case it may be possible to move the `movableDragHandler` declaration before the EyeDropperNode supercall, but I don't think that will work as a general solution in every case.

**Comment by samreid** [comment]
One solution for this problem would be to use one tandem per each level of inheritance...  Could be confusing in the API file but practically it should work.

**Comment by pixelzoom** [comment]
That would be very confusing in the API, and would get more confusing as the levels of inheritance increased.  The dropper should be referred to as `concentration.concentrationScreen.dropper`, not something like `concentration.concentrationScreen.dropper.EyeDropperNode`.

**Comment by pixelzoom** [comment]
Methinks this issue is very much related to how drag data is being handler via TDraggableNode, see https://github.com/phetsims/together/issues/254.

**Comment by samreid** [comment]
An idea: only the most `subclassiest` (sp?) of a hierarchy registers the tandem.  If subclassing, then strip out the tandem before passing to the parent.

This seems like it wouldn't work for subclassing simulation instances where tandems are required (though we could make tandems always optional to support this idea).

**Comment by samreid** [comment]
The idea from the preceding comment first appeared in this thread: https://github.com/phetsims/sun/issues/192

The problem noted there is that subtandems (by composition) still need to be registered.

**Comment by samreid** [comment]
Perhaps we need a way to pass the tandem to the parent, but with a flag to "only register children, not the node itself".  This seems complicated but it would solve the problem at hand.  Tagging @pixelzoom to get his thoughts on the matter.

**Comment by samreid** [comment]
Assigning to @pixelzoom for feedback on the preceding idea.

**Comment by pixelzoom** [comment]
A flag to "only register children, not the node itself" sounds like a bandaid. And this problem will occur again, so I'd like to find a cleaner solution. Since this is due to an ordering dependency caused by TDraggableNode, I think we should address this after https://github.com/phetsims/together/issues/254 (various issues related to TDraggableNode)

**Comment by samreid** [comment]
There is a solution proposed in https://github.com/phetsims/sun/issues/192#issuecomment-169191660 and pending discussion with @pixelzoom at his convenience (within 2 weeks would be great).

**Comment by pixelzoom** [comment]
Not a fan of the workaround proposed in phetsims/sun#192.  As noted in https://github.com/phetsims/beers-law-lab/issues/133#issuecomment-168849994, I think the root of this problem (the ordering dependency) is in TDraggableNode.

**Comment by samreid** [comment]
In the above commits, EyeDropperNode registers its tandem and BLLDropperNode uses createSupertypeTandem.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Looks great. 

FYI, while I was reviewing this, I implemented `EyeDropperNode.dispose`, which (among other things) calls `tandem.removeInstance`.  See https://github.com/phetsims/scenery-phet/issues/216

Closing.
