### ISSUE TITLE
how does the client know when solution is saturated?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#135]
I noticed that SaturatedIndicator is not instrumented, nor is anything related to saturation in ConcentrationSolution.  How does a client determine if the solution is saturated? Seems like they'll need to duplicate the logic in ConcentrationSolution.isSaturated, which would be unfortunate.  

Perhaps `saturatedProperty` should be added to ConcentationSolution? Something like this:

```js
this.saturatedProperty = new DerivedProperty( [ ],
  function( solute, soluteAmount, volume ) {
   return ( volume > 0 ) && ( soluteAmount / volume ) > solute.getSaturatedConcentration()
  },  
  { tandem: tandem.createTandem( 'saturated' ) }
);
```

And then observe this in SaturatedIndicator.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
Fixed as described above, @pixelzoom please review at your convenience.

**Comment by pixelzoom** [comment]
:+1: Closing.

**Comment by pixelzoom** [comment]
Reopening. When running `together/doc/site/examples/event-log.html?sim=beers-law-lab`, I'm seeing a fatal error:

> Assertion failed: beersLawLab.concentrationScreen.solution.saturated could not find component saturated

**Comment by pixelzoom** [comment]
The above error message is also misleading. It occurs at together.js line 241:

```js
var componentType = type[ componentName ];
assert && assert( !!componentType, togetherID + ' could not find component ' + componentName );
return componentType;
```

The error message should be:

`togetherID + ' could not find type for component ' + componentName`

**Comment by pixelzoom** [comment]
Error message modified in 915a2c6f819e125dba2a69eaf78b24ea4dcad298.

After doing that, it's now running without error. Weird.  Perhaps something was cached.

**Comment by pixelzoom** [comment]
Verified that `beersLawLab.concentrationScreen.solution.saturated` is in the data stream. Closing.
