### ISSUE TITLE
When loading through together.expressions, there is an auto-shake when the sim starts up

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#138]
Using the "states" test harness, move the shaker, and pressing launch (at the bottom), the simulation will "auto-shake" some particles into the solution.

**Comment by samreid** [comment]
Here's a url that exhibits this incorrect behavior.  The measured concentration should be 1.7 mol/L:

http://localhost/beers-law-lab/beers-law-lab_en.html?brand=phet-io&ea&together.expressions=%5B%5B%22together%22%2C%22setState%22%2C%5B%7B%22beersLawLab.solutions.drinkMix.concentration%22%3A0.1%2C%22beersLawLab.solutions.cobaltIINitrate.concentration%22%3A0.1%2C%22beersLawLab.solutions.cobaltChloride.concentration%22%3A0.1%2C%22beersLawLab.solutions.potassiumDichromate.concentration%22%3A0.0001%2C%22beersLawLab.solutions.potassiumChromate.concentration%22%3A0.0001%2C%22beersLawLab.solutions.nickelIIChloride.concentration%22%3A0.1%2C%22beersLawLab.solutions.copperSulfate.concentration%22%3A0.1%2C%22beersLawLab.solutions.potassiumPermanganate.concentration%22%3A0.0001%2C%22beersLawLab.sim.active%22%3Atrue%2C%22beersLawLab.sim.screenIndex%22%3A0%2C%22beersLawLab.sim.showHomeScreen%22%3Afalse%2C%22beersLawLab.concentrationScreen.soluteForm%22%3A%22solid%22%2C%22beersLawLab.concentrationScreen.solution.soluteAmount%22%3A0.8500000000000006%2C%22beersLawLab.concentrationScreen.solution.volume%22%3A0.5%2C%22beersLawLab.concentrationScreen.solute%22%3A%22beersLawLab.solutes.drinkMix%22%2C%22beersLawLab.concentrationScreen.shaker.location%22%3A%7B%22x%22%3A385.7435344827586%2C%22y%22%3A141.4870689655172%7D%2C%22beersLawLab.concentrationScreen.evaporator.rate%22%3A0%2C%22beersLawLab.concentrationScreen.evaporator.enabled%22%3Atrue%2C%22beersLawLab.concentrationScreen.solventFaucet.flowRate%22%3A0%2C%22beersLawLab.concentrationScreen.drainFaucet.flowRate%22%3A0%2C%22beersLawLab.concentrationScreen.dropper.location%22%3A%7B%22x%22%3A400%2C%22y%22%3A225%7D%2C%22beersLawLab.concentrationScreen.dropper.flowRate%22%3A0%2C%22beersLawLab.concentrationScreen.dropper.dispensing%22%3Afalse%2C%22beersLawLab.concentrationScreen.dropper.empty%22%3Afalse%2C%22beersLawLab.concentrationScreen.concentrationMeter.valueProperty%22%3Anull%2C%22beersLawLab.concentrationScreen.concentrationMeter.probe.location%22%3A%7B%22x%22%3A750%2C%22y%22%3A370%7D%2C%22beersLawLab.concentrationScreen.concentrationMeter.body.location%22%3A%7B%22x%22%3A785%2C%22y%22%3A210%7D%2C%22beersLawLab.concentrationScreen.shakerParticles%22%3A%5B%5D%2C%22beersLawLab.beersLawScreen.ATDetector.mode%22%3A0%2C%22beersLawLab.beersLawScreen.ATDetector.body.location%22%3A%7B%22x%22%3A6.3%2C%22y%22%3A0.2%7D%2C%22beersLawLab.beersLawScreen.ATDetector.probe.location%22%3A%7B%22x%22%3A6.3%2C%22y%22%3A2%7D%2C%22beersLawLab.beersLawScreen.light.onProperty%22%3Afalse%2C%22beersLawLab.beersLawScreen.light.wavelengthProperty%22%3A508%2C%22beersLawLab.beersLawScreen.wavelengthControls.variableWavelengthProperty%22%3Afalse%2C%22beersLawLab.beersLawScreen.cuvette.width%22%3A1%2C%22beersLawLab.beersLawScreen.ruler.location%22%3A%7B%22x%22%3A0.6999999999999997%2C%22y%22%3A4.5%7D%2C%22beersLawLab.beersLawScreen.solution%22%3A%22beersLawLab.solutions.drinkMix%22%7D%5D%5D%5D

**Comment by samreid** [comment]
This is because the previousLocation in Shaker is not being saved/restored. Hence on startup if the shaker is at a different position, the sim things it must shake out solute.

**Comment by samreid** [comment]
The simplest way to instrument the `Beaker.previousLocation` would be to make it a property.  The alternative would be to create a together wrapper type for Shaker that knows how to save/load its own previousLocation.

**Comment by samreid** [comment]
I changed `@public` to `@public` above for `previousLocation` since it is not used outside of the file.

**Comment by samreid** [comment]
In the above commit, I demonstrated how to convert the Vector2 to Property(Vector2), and verified that it solves the problem.  This solution seems reasonable to me since the `previousLocation` is `@private`.  However, I have reverted the change so that @pixelzoom may review them before we commit them.  The issue is that a Vector2 has been converted to Property(Vector2) not so that it may be observed, but so that it can transmit its value easily for together. @pixelzoom please review this issue and let me know if the Property(Vector2) is satisfactory.  Currently a restriction of together is that only Property instances may be saved and restored.  If we extend this to non-Properties we will need to introduce some markup that indicates what (aside from Property instances) to save/restore and it's unclear to me how it would work exactly.

**Comment by samreid** [comment]
A correction on the comment above: I learned that any object with a toStateObject gets serialized, not just Property instances.

**Comment by pixelzoom** [comment]
I'm still a little confused about why the "auto-shake" is occurring. I need to understand that before deciding how/whether to convert `previousLocation`. On my plate to discuss with @samreid via Skype.

**Comment by samreid** [comment]
Here's Shaker.step:

```js
// @public Sets the dispensing rate if the shaker is moving.
step: function() {
  var thisShaker = this;
  if ( thisShaker.visibleProperty.get() && !thisShaker.emptyProperty.get() ) {
    if ( thisShaker.previousLocation.equals( thisShaker.locationProperty.get() ) ) {
      thisShaker.dispensingRateProperty.set( 0 ); // shaker is not moving, don't dispense anything
    }
    else {
      thisShaker.dispensingRateProperty.set( thisShaker.maxDispensingRate ); // max rate seems to work fine
    }
  }
  thisShaker.previousLocation = thisShaker.locationProperty.get();
}
```

When the sim starts up, the shaker's `location` (also equal to `previousLocation`) is set to `new Vector2( thisModel.beaker.location.x, 170 )` from ConcentrationModel.js calling `new Shaker(...)`.  After the sim starts up, together.js changes the position of the Shaker by setting the Shaker's Movable's `locationProperty` value.  However, together.js does not change the `previousLocation`.  Therefore, the next time step runs, it detects that the previous location is not equal to the current location, so the dispensing rate is set to max.  This causes solute to shake out.

**Comment by samreid** [comment]
@kathy-phet requested me to work on https://github.com/phetsims/together/issues/237 for a presentation tomorrow.  I've got it mainly working but it suffers from the autoshake problem.  My time is short before the upcoming presentation, so I'm inclined to make this change in master (dealing with branches across 2 repos seems like too much overhead).  After the presentation, @pixelzoom can evaluate and if he decides on another plan, I will be happy to revert this change.

**Comment by samreid** [comment]
I've applied the previousLocation => Property change above and it works nicely in the wrapper (no more autoshake.)  Leaving assigned to @pixelzoom for next steps as outlined above, and my apologies for rushing forward with this before you were ready.

**Comment by pixelzoom** [comment]
Looks good.  But in Shaker, the visibility for `this.previousLocation` seems incorrect:

```js
// Store the previousLocation as a property so that it can be easily saved/restored for phet-io, see #138
// @private
thisShaker.previousLocationProperty = new Property( ... );
``` 

Since it's accessed by together, it's public.  So I believe that visibility should "qualified public", i.e.:

```js
// Store the previousLocation as a property so that it can be easily saved/restored for phet-io, see #138
// @public (together)
thisShaker.previousLocationProperty = new Property( ... );
``` 

@samreid does that make sense?

**Comment by pixelzoom** [comment]
Change to visibility annotation committed above.

**Comment by pixelzoom** [comment]
There's something that still feels a little wrong about having to make this a Property. And it seems like this could be a general issue that will be encountered in other sims.  Not sure what else to suggest, but perhaps we should do a "pair brainstorm" to see if we can come up with something that won't require code changes in similar situations.

**Comment by pixelzoom** [comment]
Perhaps a better general/longterm solution would be the "alternative" mentioned in https://github.com/phetsims/beers-law-lab/issues/138#issuecomment-168362178.  Define TShaker with field `previousLocation`, then declare `previousLocation` like this: 

```
// @public (together)
thisShaker.previousLocation = location;
```

**Comment by samreid** [comment]
Generally, it would be good for together to easily be able to save/load non-Properties.  I'll look into this next.

**Comment by samreid** [comment]
> So I believe that visibility should "qualified public"

Thank you for correcting this.  I was (hopefully temporarily) under the mistaken impression that the parenthetical listed exceptions rather than qualifiers.  I looked around bending-light and didn't see any other of this kind of problem, so hopefully this was an isolated incident.

**Comment by samreid** [comment]
Fixed above, tested and it works nicely.  I confirmed that `previousLocation` is declared as requested in https://github.com/phetsims/beers-law-lab/issues/138#issuecomment-169762980

Assigned to @pixelzoom to review if you have time.

**Comment by pixelzoom** [comment]
@samreid I'm not clear on how you resolved this. Did you add the ability to save/load non-Properties, as discussed in https://github.com/phetsims/beers-law-lab/issues/138#issuecomment-169762980?

**Comment by samreid** [comment]
Yes, now any objects with toStateObject/fromStateObject/setValue will be save/loaded.  Here's the new TShaker declaration that manages it:

```js
  var TShaker = togetherInherit( TObject, 'TShaker', function( instance, togetherID ) {
    TObject.call( this, instance, togetherID );
    assertInstanceOf( instance, phet.beersLawLab.Shaker );
  }, {
    setValue: {
      returnType: TVoid,
      parameterTypes: [ TObject ],
      implementation: function( value ) {
        this.instance.previousLocation.x = value.previousLocationX;
        this.instance.previousLocation.y = value.previousLocationY;
      },
      documentation: 'Load the values recorded in getState'
    }
  }, {
    toStateObject: function( instance ) {
      return {
        previousLocationX: instance.previousLocation.x,
        previousLocationY: instance.previousLocation.y
      };
    },
    fromStateObject: function( stateObject ) {
      return stateObject; // no coercion necessary for a plain object with primitives
    }
  } );
```

**Comment by pixelzoom** [comment]
Great, that looks nice.  If there's nothing else to do here, feel free to close.

**Comment by pixelzoom** [comment]
Reopening for one minor comment... It's too bad that `previousLocation` needs to be explicitly unpacked as separate `x` and `y` values. Can this same same pattern be applied to `Vector2`?  Or does this work only for integral types?

**Comment by pixelzoom** [comment]
@samreid ping

**Comment by samreid** [comment]
In this case, the value can be stored/loaded with TVector2, see the above commit.  Though in general, I must say that PhET-iO's save/restore state feature is in a sticky situation and requires investigation and discussion as noted in https://github.com/phetsims/together/issues/319

**Comment by pixelzoom** [comment]
I inspected the change, looks good, closing.
