### ISSUE TITLE
Prepare for deliver to Ido

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#139]
@kathy-phet said now that this simulation is instrumented, the next step will to be to get it to a good point to deliver to Ido for testing.  We should address many of the outstanding issues before sending it along.

**Comment by pixelzoom** [comment]
Based on email that @samreid shared with me, it sounds like Ido's studies are in March, but he's not certain yet that he'll be using Beer's Law Lab.

**Comment by samreid** [comment]
@kathy-phet confirmed that we will be delivering BLL to Ido, no more information about the precise date.

**Comment by samreid** [comment]
From Ido:

> “ready” means
- backend data instrumentation
- custom start state
- label changes, availability of features, other minor screen adaptations.
Perhaps also
- ability of students to report out screen state (and capture somehow, somewhere).

**Comment by samreid** [comment]
Ido continued:

> After our meeting today, we have identified the following minor changes to the sims that would really facilitate our study:
* add constant absorption by water
* add unitless marks to beaker to measure width of beaker (similar to how there is a grid in charges and fields)
* add a measuring tape (similar to how there is a measuring tape in charges and fields). This would allow us to assess if students can assess distance relationships without units but using ratios instead.

> Ideally we would have these changes as early as beginning of February so that we can have a pilot study with a handful of students. Is this doable?

**Comment by samreid** [comment]
@kathy-phet replied:

can you write up a 1-2 page study description so that we understand how you are structuring and your research questions you are trying to answer specifically. 

> add constant absorption by water

what's the motivation for this change? this is probably one of the most involved because it is a change to the model. 

> add a measuring tape (similar to how there is a measuring tape in charges and fields). This would allow us to assess if students can assess distance relationships without units but using ratios instead.

can the ruler not serve this purpose?

**Comment by samreid** [comment]
Ido replied regarding the constant absorption of water:

> The reason is to have a model fail - so even at concentration 0 there is some absorption. The absorption depends on width. 

Ido replied about the ruler:

> Yes. We had in mind something similar to Beer and to Balance Beam - where students can choose ticks only (simpler to use and unites) or a tape (harder to use with units), to see whether they “waste their time” to get values. 

And about the study description:

> Sarah will send a study description soon (I think; Sarah? :-)

**Comment by pixelzoom** [comment]
@samreid Can this issue be closed? Seems like we have graduated to creating specific issues for the UBC study. (eg #154, #155)

**Comment by samreid** [comment]
Sure, sounds good.
