### ISSUE TITLE
model and view: should we separate or combine?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#140]
Entries in the PhET-iO API are inconsistent.  Sometime there's a separation of model and view, sometimes entries combine model and view attributes under a single tandem id.

Here's the entry for the concentration meter in beers-law-lab-api.js:

```js
    concentrationMeter: {
          probe: TDraggableNode.extend( {
            location: TProperty( TVector2 )
          } ),
          body: TDraggableNode.extend( {
            location: TProperty( TVector2 ),
            readout: TProperty( TString ) // Use TString here for precision so it will display exactly what the user sees'
          } )
        },
```

This entry combines model and view. The 2 occurrences of `location` are from the model, `readout` is from the view.  This was really confusing to figure out.  This is a maintenance problem because it requires that model and view components *must* have the same tandem ids.  In this case, that's *4* locations in the code that must be kept in sync:

```js
// ConcentrationModel.js line 77
thisModel.concentrationMeter = new ConcentrationMeter( ..., tandem.createTandem( 'concentrationMeter' ) );

// ConcentrationView.js line 75
var concentrationMeterNode = new ConcentrationMeterNode( ..., tandem.createTandem( 'concentrationMeter' ) );

// Concentration.js line 35
this.body = new Movable( bodyLocation, bodyDragBounds, tandem.createTandem( 'body' ) );

// ConcentrationMeterNode.js line 73
var bodyNode = new BodyNode( meter, modelViewTransform, tandem.createTandem( 'body' ) );
```

This same approach (combining model and view) is used for 'dropper', and results in the same need to keep tandem ids in sync.

Now let's look at the AT detector in beers-law-lab-api.js:

```js
        // AT stands for Absorbance Transmittance
        ATDetector: {
          mode: TProperty( TNumber ), // 'TRANSMITTANCE': 0, 'ABSORBANCE': 1
          body: {
            location: TProperty( TVector2 )
          },
          probe: {
            location: TProperty( TVector2 )
          }
        },
        ATDetectorNode: {
          body: {
            transmittanceRadioButton: TRadioButton( TString ),
            absorbanceRadioButton: TRadioButton( TString )
          },
          probeNode: TDraggableNode
        },
```

Here we have an entirely different approach to the same problem, using separate entries for model and view (Node).  The entry for `probeNode` seems redundant and unnecessary, for the same reason there is no such `probeNode` for the concentration meter.   

If we used the same pattern as the concentration meter, then we'd merge model and view like this:

```js
        // AT stands for Absorbance Transmittance
        ATDetector: {
          mode: TProperty( TNumber ), // 'TRANSMITTANCE': 0, 'ABSORBANCE': 1
          body: {
            location: TProperty( TVector2 ),
            transmittanceRadioButton: TRadioButton( TString ),
            absorbanceRadioButton: TRadioButton( TString )
          },
          probe: {
            location: TProperty( TVector2 )
          }
        }
``` 

We should discuss the pros/cons of each approach, and pick one approach to be used consistently.

**Comment by samreid** [comment]
My thought has been to suppress unnecessary implementation details from the API file, but this must be traded off with simplicity/maintainability in instrumentation.  Another option would be to make the API file exactly match the exact implementation of the simulation (which would expose irrelevant implementation details in the API file but could ease instrumentation).  Would be great to discuss together.  I've added this to the phet-io google doc agenda for Thursday Jan 7.

**Comment by samreid** [comment]
After thinking about this, I am inclined to separate model and view in the API file.  In this case, it is not a minor implementation detail that should be hidden from the API/data stream/researchers/etc.  It is an important architectural division shared by all PhET simulations.  Assigned to myself for investigation.

**Comment by samreid** [comment]
Here's an example of before/after for the concentration meter, and discussion of the tradeoffs:

https://github.com/phetsims/beers-law-lab/issues/134#issuecomment-168133664

**Comment by samreid** [comment]
I've separated the model and view in my working copy, and it looks very nice.  Combined with using `var` suffixes from the simulation such as `Node`, there is much more clarity about the different instrumented instances.  It is also helpful to see all of the model instances together and all of the view instances together.  I'll commit shortly.

**Comment by samreid** [comment]
Committed above, should be reviewed/discussed with @pixelzoom at his convenience.

**Comment by pixelzoom** [comment]
I agree that it looks nice.  And I think it makes instrumentation a more straightforward.  I'd like to get (at least) a third opinion before we standardize on this approach. @jbphet, would you mind reviewing? You've had experience with PhET-iO instrumentation, and since this sim is very similar to beaker.

**Comment by pixelzoom** [comment]
@jbphet Issues #129, #134, #141 and #145 are all contingent on whether we separate model and view tandems, so I'm labeling this "high priority".  If you can't get to it in the next day or two, let me know and we'll seek other opinions.

**Comment by jbphet** [comment]
I've read through this and looked at the code differences, and I'm very much aligned with the idea of separating model and view in the API file.  It looks better and just makes more sense to me.  And even though most consumers of the output data are unlikely to be intimately familiar with the MVC architecture, a data stream that is clear about separating model and view will have an underlying logic to it that may well be helpful to them in interpreting the data.  So, the bottom line for me is +1 on separation of model and view in the API.

**Comment by pixelzoom** [comment]
Thanks @jbphet. 

@samreid back to you. I'm comfortable with standardizing on this approach if you are.  If there's nothing else to do, please close this issue, and issues #129, #134, #141 and #145.

**Comment by samreid** [comment]
I'll revise the other sims as part of https://github.com/phetsims/together/issues/263 and https://github.com/phetsims/together/issues/262

**Comment by samreid** [comment]
This issue and the other related issues in Beer's Law Lab seems good, closing.
