### ISSUE TITLE
strange entry for 'cuvette'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#141]
In beers-law-lab-api.js

```js
cuvette: {
  width: TProperty( TNumber ),// goes from 0.5 to 2
  node: TCuvetteNode
},
```

I haven't seen any other entry with a `node` attribute - and in fact, there are no other such examples in together/js/api/*.  So this smells like a workaround, probably to gather data about interaction with the cuvette.  Please explain why this approach its necessarily so different.

**Comment by pixelzoom** [comment]
And this looks like bogus documentation for `TCuvetteNode`, beers-law-lab-api.js line 120:

`documentation: 'The base type for graphical objects that can be dragged by the user.',`

**Comment by samreid** [comment]
Here are the possible options for this case:

```js
cuvette: {
  width: TProperty( TNumber ),// goes from 0.5 to 2
  node: TCuvetteNode
},
```

```js
cuvette: TCuvetteNode.extend({
  width: TProperty( TNumber ),// goes from 0.5 to 2
}),
```

```js
cuvetteWidth: TProperty( TNumber ),// goes from 0.5 to 2
cuvetteNode: TCuvetteNode
},
```

I'm not sure which will be best, and indeed it may not matter too much, since all provide the same data and configurability. What do you recommend @pixelzoom?

**Comment by pixelzoom** [comment]
This option seems most consistent with the approach used in other cases where the registered instance is a Node and there are additional model Properties:
 
```js
cuvette: TCuvetteNode.extend({
  width: TProperty( TNumber ),// goes from 0.5 to 2
}),
```

**Comment by samreid** [comment]
This problem would disappear if we separate model and view in the API file as discussed in #140.

**Comment by samreid** [comment]
I've separated the model and view and now the cuvette appears like so:

```js
beersLawScreen: {
  model: {
    cuvette: {
      widthProperty: TProperty( TNumber )// goes from 0.5 to 2
    }
    // ...
  },
  view: {
    // ...
    cuvetteNode: TCuvetteNode,
  }
}
```

In my opinion this is clearer and more maintainable,.  Ready for review/discussion with @pixelzoom at his convenience.

**Comment by pixelzoom** [comment]
If we standardize on separation of model and view tandems (see #140), then this looks good. I'll leave this open until that issue is closed.
