### ISSUE TITLE
Evaporation API doesn't reflect implementation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#142]
In the sim implementation, there's an evaporator (Evaporator) and associated control (EvaporationControl).  In beers-law-lab-api.js, these abstractions have been replaced by 3 disjoint entries:

```js
// Evaporation
evaporationSlider: TSlider,
evaporationRate: TProperty( TNumber, { units: 'L/s' } ),
evaporationEnabled: TProperty( TBoolean ),
```

I expected to see something like this, which is similar to how other parts of the sim were mapped to the API:

```js
evaporator: {
  slider: TSlider,
  rate: TProperty( TNumber, { units: 'L/s' } ),
  enabled: TProperty( TBoolean ),
}
```

We now have 2 different "implementations" of evaporation (JS and API).  Why did you decide to use a different abstraction here, but not in other cases? When should we stick to the abstractions used in the implementation vs diverging?

**Comment by samreid** [comment]
In the above commits, I changed the API declaration to be nested under `evaporator:{}`.  This simplifies things, except for the evaporation control which has a tandem mismatch:

```js
var evaporationControl = new EvaporationControl( model.evaporator, tandem.createTandem( 'evaporator' ), { maxWidth: 410 } );
```

I think there's a tradeoff between making an elegant API declaration and matching the simulation implementation.  Part of the idea is to hide unnecessary implementation details from the API file, but its unclear when to deviate.

**Comment by pixelzoom** [comment]
This looks better, OK with the "tandem mismatch" in EvaporationControl.
