### ISSUE TITLE
missing type verification in API file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#143]
In beers-law-lab-api.js, type verification is missing for TSolution, TCuvetteNode and TConcentrationSlider. 

After the supertype constructor call, other types (eg TSolute, TShakerParticles) have an assertion that verifies the type of the `instance` arg. E.g.:

```js
var TSolute = togetherInherit( TObject, 'TSolute', function( instance, togetherID ) {
  TObject.call( this, instance, togetherID );
  assertInstanceOf( instance, phet.beersLawLab.Solute );
```

**Comment by pixelzoom** [comment]
As in TogetherCommon.js, this assertion also serves to document which type(s) are supported by the together-type definition.

**Comment by samreid** [comment]
Addressed in https://github.com/phetsims/together/commit/14514b74f05ec2b2fc1f0dc3234a8f54fa7f08aa
