### ISSUE TITLE
Match tandem names with var names

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#145]
As part of https://github.com/phetsims/beers-law-lab/issues/140 and https://github.com/phetsims/together/issues/258 I'd like to try matching the tandem names and the var names.  This should make it easier to instrument & maintain and verify that the instrumentation is correct.

**Comment by samreid** [comment]
This has worked out nicely.  I think it should be a rule of thumb to match var names to tandem names, and if an exception is needed, it should be clearly documented.  Most of the var name matching meant changing tandem names, but in one case I gave a var name a clearer name so the matching tandem name would be clearer (I forget which one it was). Ready for review/discussion with @pixelzoom.

**Comment by pixelzoom** [comment]
This looks good to me, but a prerequisite seems to be standardizing on separation of model and view tandems (see #140).  If we do that, this looks good.  Otherwise, we may have other naming issues to deal with. I'll leave this open until #140 is closed.
