### ISSUE TITLE
display concentration units in percent

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#149]
Migrating this issue from phetsims/concentration#47, where @kathy-phet said:

> We are looking to add the following features to increase flexibility for lab use and for younger grade level. I suggest making all of these as behaviors that are designed into master and part of our published sim, and accessible through query parameters.

- [ ] Display concentration units in percent (as is option in Beaker).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/concentration/issues/47#issuecomment-177034062, @ariel-phet described the priority:

> ideally complete next week. This would be top priority, with the understanding that it is bumping function builder priority for next week. I think we could hand a link that is tested, but not yet published on the website.

**Comment by pixelzoom** [comment]
Related code for this feature in beaker.BeakerNode:

```js
    // note - the following property is controlled through together only
    thisModel.concentrationReadoutUnitsProperty = new Property( 'molesPerLiter', { tandem: tandem.createTandem( 'concentrationReadoutUnits' ) } ); // valid values are 'molesPerLiter' and 'percent'
```

I see no query parameter in beaker for enabling this feature.  So I'm guess it's done through PhET-iO.

Specifications needed:

- [ ] what is the desired query parameter to enabled this feature?

**Comment by pixelzoom** [comment]
I noted above that this was *not* done with a query for beaker, it was done through PhET-iO.  I discussed with @ariel-phet whether this issue and https://github.com/phetsims/beers-law-lab/issues/150 should be done through a query parameter or PhET-iO. Based on @kathy-phet description of the desired features, these are generally-useful features that need to be available in non-PhET-iO versions.  So we're going with a query parameter.  @kathy-phet if this is NOT the case, please notify me ASAP.

**Comment by pixelzoom** [comment]
This will require model changes.  Get the computation of percent from `beaker.Solute.getConcentrationInPercent`.

**Comment by pixelzoom** [comment]
When this feature is enabled, put '%' inside the value display window, hide the units on the body.

**Comment by samreid** [comment]
To be clear, phet-io parsed a query parameter to set the readout to percent.  So it was both a query parameter and phet-io (this fact in itself does not change any conclusions from above).  If we are going to proceed with sim features to be enabled through query parameters, we should make an effort to make sure these are well documented and available to phet-io customers to use alongside the phet-io customization.  Not sure how best to do this, perhaps notes in the API file, which describes the rest of the customizability?

**Comment by pixelzoom** [comment]
I don't see any calls to getQueryParameter in the beaker code base, so the sim itself does not have the ability to enable this feature.  What I believe is happening is that PhET-iO is handling the query parameter and setting sim state (by setting Property values). 

That's not what's has been requested here. @kathy-phet described this as being a generally useful feature that can be set via a query parameter.  If someone with a PhET-iO version wants to enable this feature, they will need to set query parameters in the same way as non-PhET-io versions. There will be no PhET-io instrumentation that is specific to these features. Ditto for requests #148 and #150.

**Comment by pixelzoom** [comment]
Re documentation of query parameters...  In code, my convention is to encapsulate all query parameters, verification and documentation in one file; see for example RPALQueryParameters.  Documenting those query parameters for teachers and integrators is not something I'm going to address; that's up to supplemental materials (eg, teacher tips).

**Comment by pixelzoom** [comment]
Question for @kathy-phet and @ariel-phet .... The current plan is for this feature to apply only to the "Concentration" screen. Is there anything related that needs to be changed in the "Beer's Law" screen?  Ie, if I enabled this feature when running the Beer's Law Lab sim, will there be anything inconsistent between the "Concentration" and "Beer's Law Screen" if only the Concentration screen displays solute amount in grams?

**Comment by pixelzoom** [comment]
Question for @kathy-phet and @ariel-phet .... The current plan is for this feature to apply only to the "Concentration" screen. Is there anything related that needs to be changed in the "Beer's Law" screen? Ie, if I enabled this feature when running the Beer's Law Lab sim, will there be anything inconsistent between the "Concentration" and "Beer's Law Screen" if only the Concentration screen displays concentration units as percent?

**Comment by pixelzoom** [comment]
@ariel-phet How do you want this feature delivered? As a maintenance 1.3.1 maintenance release (mor work for me), or as a new 1.4 release branch (requires a complete RC test)?

**Comment by pixelzoom** [comment]
... keeping in mind that recent PhET-iO changes are not in the 1.3 maintenance branch.

**Comment by ariel-phet** [comment]
@pixelzoom 
- fine for this just to be in concentration screen. Since the concentration as percent was presented as a middle school learning goal, it seems unlikely someone using the Beer's Law screen would opt for this query parameter as Beer's Law is much more advanced than Middle School
- 1.4 release branch seems like the way to go. Delivery to the collaborator will not mean the sim needs to be published yet on the website, but we will move towards publication once the work is complete.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-177326987, it was requested to keep "mol/L" where it is, detached from the value.  But when the "percent" feature is enabled, hide the "mol/L" label, and but put "%" next to the value in the meter.  

Two problems:

(1) This inconsistent handling of units complicates the implementation of `ConcentrationMeterNode`, particularly wrt layout. It's also inconsistent with most other sims, where the units are presented in the readout, next to the value.  My recommendation is to move the units next to the value in all cases; eg "0.885 mol/L" and "65 %". 

(2) A bigger issue is that it affects the PhET-iO data stream.

I see this bit of code that @samreid added for PhET-iO, at `ConcentrationMeterNode` line 194:

```js
// Output the displayed value to the together data stream
readoutProperty.set( valueNode.getText() );
```

Getting the value from the scenery node and storing it in a {string} Property looks like a dubious quick-and-dirty implementation. It's a number, and it should have been passed through as a number. But that's the way it was done, so I'll roll with it.  

What this means is that when units are "mol/L", the data stream will see a string with no units, eg "0.884". When units are percent, the data stream will see a string with units next to it, eg "65 %".  If there's client code that's parsing this string and expecting a number, this will break it.  

My recommendation is to pick one of these options:
(a) Continue to treat `readoutProperty` as a `{string}`, but include the units in both cases. This will require no PhET-iO API changes other than documentation, but will break client code if it's converting the string to number.
(b) Change `readoutProperty` to `{number}` and pass only the numeric value. This will require breaking PhET-iO API changes (the type of readoutProperty changes from `TString` to `TNumber`), and the client will be responsible for keeping track of what units are enabled.

@samreid @ariel-phet Please weigh in.

**Comment by pixelzoom** [comment]
One further complication if we choose option (b).  When the concentration meter isn't reading a value, it currently displays "-" (a hyphen).  That hyphen will need to be converted to something appropriate for a {number} Property, like `null`.   

My recommendation is to go with option (a), and send exactly what the user is seeing (value + units) as a string, which seems to have been the purpose in adding this Property. If the client wants the model value, that can get that {number} from `concentrationScreen.model.concentrationMeter.valueProperty`.

**Comment by ariel-phet** [comment]
@pixelzoom I think option (a) will be fine. For instance, in BLL the second screen has a concentration (and wavelength) readout with units included within the readout window. We have multiple instances of this kind of inclusion of units, so we have no reason to suspect it would cause confusion.

**Comment by pixelzoom** [comment]
@ariel-phet How many decimal places in the displayed value? The AT detector uses 2, but that may not be appropriate for concentration.

**Comment by ariel-phet** [comment]
I think one should be fine for percent concentration (considering the use case of younger students that was presented). However, I would make this easy to change, in case it is reported back that the client would like more/fewer decimal places.

**Comment by pixelzoom** [comment]
It will be easy to change, but not changeable by the client.

**Comment by pixelzoom** [comment]
I've implemented the view changes for this feature. Summary:

(1) Units move into concentration readout for all units. Eg, "0.885 mol/L" and "65%".

(2) `readoutProperty` remains a `{string}`, and will now contain units. Any clients code that relies on this being a `{number}` will likely break, unless they programmed defensively.

Next up are the model changes, which are significant and will be obtained from beaker.

**Comment by pixelzoom** [comment]
I've implemented the view changes for this feature. Summary:

(1) Units move into concentration readout for all units. Eg, "0.885 mol/L" and "65.0%".

(2) Percent concentration is displayed with 1 decimal place, eg "65.0%".

(3) readoutProperty remains a {string}, and will now contain units. Eg, "0.885 mol/L" and "65.0%". Any clients code that relies on this being a {number} will likely break, unless they programmed defensively.

Next up are the model changes, which are significant and will be obtained from beaker.

**Comment by pixelzoom** [comment]
Screenshot showing concentration meter with "mol/L" units moved into the readout:

![screenshot_139](https://cloud.githubusercontent.com/assets/3046552/12704535/85970262-c81a-11e5-9da8-38b0926ebdd5.png)

**Comment by ariel-phet** [comment]
I would add a bit more padding to the meter body

![85970262-c81a-11e5-9da8-38b0926ebdd5](https://cloud.githubusercontent.com/assets/4051174/12704677/0563bcd6-c81d-11e5-8c8a-0da196cfb344.png)

**Comment by ariel-phet** [comment]
Just made it a bit vertically taller, seemed a little cramped

**Comment by pixelzoom** [comment]
Model changes completed.  I ran into some minor stuff when porting the model from beaker, see https://github.com/phetsims/beaker/issues/71 (assign to @jbphet, requested a high-priority reply).

**Comment by pixelzoom** [comment]
Ready to publish a dev version to demonstrate this feature, but I've run into some weirdness with the version numbering for this sim, see https://github.com/phetsims/beers-law-lab/issues/153.

**Comment by pixelzoom** [comment]
Looks like I'm not done with this.  I can't simply ask the solution for the percent concentration, since the probe can be in other places (faucet outputs, dropper output,...)

**Comment by pixelzoom** [comment]
Last piece of this is to make the meter work when it's measuring the output of the dropper. That requires computing the percent concentration of the stock solutions. I'm not clear on how to do that, and there is no dropper in the Beaker sim. I'll try consulting with @jbphet on Monday.

**Comment by pixelzoom** [comment]
Dev version is available here:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.1/beers-law-lab_en.html

The query parameter is `concentrationMeterUnits`, with values `molesPerLiter` (default) and `percent`. If you provide an invalid value, it's a runtime error, with message like "Error: invalid value for concentrationMeterUnits query parameter: foo".

To demonstrate this feature:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.1/beers-law-lab_en.html?concentrationMeterUnits=percent

Assigned to @ariel-phet for initial feedback.

Two caveats:

(1) This isn't working yet for measurement of the dropper output. See https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-177653472.

(2) We should have a chemist review the correctness of the values. I copied what was done in Beaker, and I'm not qualified to verify the correctness of the values.

**Comment by samreid** [comment]
> Getting the value from the scenery node and storing it in a Property({string}) looks like a dubious quick-and-dirty implementation. It's a number, and it should have been passed through as a number. But that's the way it was done, so I'll roll with it.

This is delivered as a string so that researchers can see exactly what value the students saw on the readout (accounting for number formatting).  The numerical value (in floating precision) is available through the model.

**Comment by pixelzoom** [comment]
Understood, thanks for the clarification.   I still think it would have been better to set the readoutProperty, and have that update the Text node, rather than the reverse.  View should be getting its value from model, not the other way around.

**Comment by samreid** [comment]
> I still think it would have been better to set the readoutProperty, and have that update the Text node, rather than the reverse.

Yes, that is a good idea.

**Comment by ariel-phet** [comment]
@amyh-phet and I discussed, the values displayed for % Concentration are correct. She was also fine with the mol/L being displayed in the meter readout. All looking good from the "view" side here.

**Comment by pixelzoom** [comment]
I discussed stock solution percent concentration with @jbphet.  Assuming that the stock solvent is water, this should be a straightforward constant computation, which I'll add as field Solute.

**Comment by pixelzoom** [comment]
@samreid heads up that I revised the documentation for readoutProperty in the API file. Here's the new documentation:

```js
// Use TString here to display exactly what the user sees.
// This includes the value (limited to some number of decimal places) and the units.
// The value and units displayed depend on the concentrationMeterUnits query parameter,
// and may be mol/L (the default) or percent concentration. The units and order of value
// and units are subject to i18n, so parsing this value is not advised.
readoutProperty: TProperty( String )
```

**Comment by pixelzoom** [comment]
Here's the computation for the percent concentration of the stock solutions:

`percentConcentration = ( molarMass * stockSolutionConcentration ) / 1000`

where 1000 is g/L for water (the solvent).

Values for molarMass and stockSolutionConcentration are as shown in https://github.com/phetsims/beers-law-lab/issues/148#issuecomment-178091606 (and the teacher tips).

**Comment by pixelzoom** [comment]
Two significant changes:
• Values for molar mass were changed to the values specified in https://github.com/phetsims/beers-law-lab/issues/148#issuecomment-178091606
• The concentration meter can now read the percent concentration of the stock solution coming out of the dropper. The computation appears in https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-178159589.

@amyh-phet please test this dev version:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.2/beers-law-lab_en.html?concentrationMeterUnits=percent 

Verifying that the meter displays the correct percent concentration for all fluids (solution in the beaker, drain faucet, water faucet, dropper):

**Comment by amyh-phet** [comment]
@pixelzoom   The meter displays the correct percent concentration for the solution in the beaker, drain faucet and water faucet.   

We need to adjust the formula used to calculate the concentration for the solution in the dropper.   The formula should be:

percent concentration = (molar mass * stock Solution Concentration)/ (1000 + (molar mass * stockSolutionConcentration))
 
For drink mix, solution concentration in the dropper should be 65.3%

**Comment by pixelzoom** [comment]
Thanks @amyh-phet. I've revised the computation of percent concentration for stock solutions, and it verifies with drink mix.  I'll publish a new version shortly.

This did raise a question... There are 2 percent concentrationvalues that were added to the model to support this feature:

`{number} Solute.stockSolutionPercentConcentration`
`{Property.<number>} ConcentrationSolution.percentConcentrationProperty`

The range of these values in model is currently [0,100].  Is that OK, or should it be [0,1] in the model, then multiplied by 100 for display in the view?  This is relevant because what's in the model is what will appear in the PhET-iO data stream.  @samreid and @ariel-phet your opinions?

**Comment by pixelzoom** [comment]
Keep in mind that the view portion of the PhET-iO data stream will display (for example) "65.5%" for the concentration meter's `readoutProperty`.  If we switch to [0,1] in the model, then the model data stream would show something like "0.65478" for the solution's `percentConcentrationProperty`.

**Comment by pixelzoom** [comment]
Keep in mind that the view portion of the PhET-iO data stream will display (for example) "65.5%" for the concentration meter's `readoutProperty`.  If we continue to use [0,100] in the model, then the model data stream would show something like "65.478" for the solution's `percentConcentrationProperty`.  If we switch to [0,1] in the model, then the model data stream would show "0.65478".

**Comment by pixelzoom** [comment]
Wrt PhET-IO changes, I verified the following:
• the sim builds with `grunt --brand=phet-io`
• the sim runs with `?togetherEvents.log=console&phet-io-standalone`
• the values in the data stream for the new `percentConcentrationProperty` look correct

**Comment by pixelzoom** [comment]
Hmmm... But I don't see ConcentrationMeterNode's `readoutProperty` in the data stream.  I've verified that `readoutProperty` is indeed being set.

**Comment by pixelzoom** [comment]
The problem with `readoutProperty` is that it's in the wrong place in the API file.  It's currently at:

`concentrationScreen.model.concentrationMeter.body.readoutProperty`

It's a view Property, and should be at:

`concentrationScreen.view.concentrationMeter.bodyNode.readoutProperty`

**Comment by pixelzoom** [comment]
Which makes me wonder... Does PhET-iO do any error checking on the API file?  Why was there no notification (at build or run time) that there was a non-existent Property specified for the model data stream?  Moving this general issue to https://github.com/phetsims/together/issues/326.

**Comment by pixelzoom** [comment]
After fixing beers-law-lab-api.js, the `readoutProperty` now appears as expected in the PhET-iO data stream.

**Comment by pixelzoom** [comment]
FYI, `readoutProperty` has been in the wrong place since 1/1/16 in commit @80af4cd812eecc5dc04ad1b41f01e03532d56e1d.

**Comment by pixelzoom** [comment]
Now that the `readoutProperty` diversion is over...

The final bit of work here is to get @samreid and @ariel-phet opinions on https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-178183466.

**Comment by samreid** [comment]
Since the variable name uses the term "percent", it should go from 0-100.

**Comment by ariel-phet** [comment]
0-100 seems logical to me

**Comment by pixelzoom** [comment]
[0,100] it is.

**Comment by pixelzoom** [comment]
@amyh-phet here's a dev version with the revised computation (percent concentration of stock solution) that you provided in https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-178171340.  Please verify that the value displayed by the concentration meter looks correct. (Note the `concentrationMeterUnits=percent` query parameter).

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.3/beers-law-lab_en.html?concentrationMeterUnits=percent

**Comment by amyh-phet** [comment]
@pixelzoom   The value displayed by the concentration meter is correct for all stock solutions in dropper.

**Comment by pixelzoom** [comment]
Thanks @amyh-phet.

All work completed on this issue.

**Comment by pixelzoom** [comment]
Verified by @phet-steele in phetsims/tasks#532 (comment). Closing.
