### ISSUE TITLE
display volume tick mark labels in mL

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#150]
Migrating this issue from phetsims/concentration#47, where @kathy-phet said:

> We are looking to add the following features to increase flexibility for lab use and for younger grade level. I suggest making all of these as behaviors that are designed into master and part of our published sim, and accessible through query parameters.

- [ ]  Display volume tick mark labels in mL (that is 500 mL and 1000 mL)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/concentration/issues/47#issuecomment-177034062, @ariel-phet described the priority:

> ideally complete next week. This would be top priority, with the understanding that it is bumping function builder priority for next week. I think we could hand a link that is tested, but not yet published on the website.

**Comment by pixelzoom** [comment]
Specifications needed:

- [ ] what is the desired query parameter to enabled this feature?
- [ ] how many ticks are shown on the beaker
- [ ] which ticks will be labeled

**Comment by ariel-phet** [comment]
Claim was that whole number units would be easier for middle school students

**Comment by pixelzoom** [comment]
@ariel-phet How do you want this feature delivered? As a maintenance 1.3.1 maintenance release (mor work for me), or as a new 1.4 release branch (requires a complete RC test)?

**Comment by pixelzoom** [comment]
... keeping in mind that recent PhET-iO changes are not in the 1.3 maintenance branch.

**Comment by pixelzoom** [comment]
Ready to publish a dev version to demonstrate this feature, but I've run into some weirdness with the version numbering for this sim, see https://github.com/phetsims/beers-law-lab/issues/153.

**Comment by samreid** [comment]
My comments are in #153, proceed at your convenience.

**Comment by pixelzoom** [comment]
Dev version is available here:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.1/beers-law-lab_en.html

The query parameter is `beakerUnits`, with values `liters` (default) and `milliliters`.  If you provide an invalid value, it's a runtime error, with message like "Error: invalid value for beakerUnits query parameter: foo".

To demonstrate this feature:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.1/beers-law-lab_en.html? beakerUnits=milliliters

Assign to @ariel-phet for initial feedback.

**Comment by ariel-phet** [comment]
@pixelzoom one request, could we change the values parameter to be simply `L` and `mL` for simplicity?

**Comment by ariel-phet** [comment]
Otherwise, working exactly as expected.

**Comment by pixelzoom** [comment]
@ariel-phet to answer your question about query parameter values, we also need to look at #149. 

Current values are:

```
beakerUnits = 'liters' | 'milliliters'
concentrationMeterUnits = 'molesPerLiter' | 'percent'
```

If we make the change you suggested, then we should do so consistently:

```
beakerUnits = 'L' | 'mL'
concentrationMeterUnits = 'mol/L' | '%'
```

Those values for `concentrationMeterUnits` are very problematic in a URL; the user would be required to manually provide escapes for special chars.   So my recommendation is to leave as is.

**Comment by samreid** [comment]
Agreed that % cannot be a query parameter value, and hence all query parameters should be spelled out to be consistent.

**Comment by pixelzoom** [comment]
I don't believe that '/' can be in a query parameter either.

**Comment by samreid** [comment]
> I don't believe that '/' can be in a query parameter either.

A quick chrome test suggests that / is ok, but % is not. (The latter fails the page load).

**Comment by ariel-phet** [comment]
Fine with leaving as is, closing

**Comment by pixelzoom** [comment]
Reopening until this enhancement makes it through RC test.

**Comment by ariel-phet** [comment]
Well then, at least let me remove the "high-priority" label....RC testing is not a high priority for delivery

**Comment by pixelzoom** [comment]
Unassigning until time to RC test.

**Comment by pixelzoom** [comment]
Verified by @phet-steele in phetsims/tasks#532 (comment). Closing.
