### ISSUE TITLE
change layout of "Concentration" screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#151]
Here's the current layout of the "Concentration" screen:

![screenshot_138](https://cloud.githubusercontent.com/assets/3046552/12699177/a2a750e2-c76f-11e5-941d-90dc228b872d.png)

@ariel-phet said that it bothers him that the shaker can be moved behind the Solute panel.  Consider moving the beaker further left, and the Solute panel and "Reset All" button further right.  This would give the user more room to move the shaker around across more of the beaker.

**Comment by ariel-phet** [comment]
potential change:

![bll](https://cloud.githubusercontent.com/assets/4051174/12699192/0ab5f2e2-c770-11e5-9643-e7fc2a8c24dd.PNG)

**Comment by pixelzoom** [comment]
Assigned to @ariel-phet to discuss with @amyh-phet.

**Comment by ariel-phet** [comment]
@pixelzoom I think without question the reset all button can be re-positioned, if nothing else, just match the position on the Beer's Law screen

**Comment by pixelzoom** [comment]
Reset All button is repositioned in this dev version:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.1/beers-law-lab_en.html

**Comment by ariel-phet** [comment]
@amyh-phet agreed moving over the Solute panel was a good idea.

Reset All button position looks good.

If an easy tweak, would be good to move the panel before we eventually RC test (but not a priority for delivery to ETS)

**Comment by pixelzoom** [comment]
Sound good. Back to me to implement.

**Comment by pixelzoom** [comment]
Work completed, demonstrated to @ariel-phet via Skype. Initial state of the "Concentration" screen is shown in this screenshot, with `?dev` query parameter to show "safe area" of screen.

![screenshot_01](https://cloud.githubusercontent.com/assets/3046552/12727372/06d72842-c8da-11e5-9aef-2aec2c812aa7.png)

**Comment by amyh-phet** [comment]
@pixelzoom and @ariel-phet   Looks good - I like the new layout.

**Comment by pixelzoom** [comment]
Dev version demonstrating the new layout:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.2/beers-law-lab_en.html

**Comment by pixelzoom** [comment]
Work completed. Unassigning until time to test.

**Comment by pixelzoom** [comment]
Verified by @phet-steele in phetsims/tasks#532 (comment). Closing.
