### ISSUE TITLE
Consider revealing query parameters in teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/beers-law-lab#152]
It is likely the modifications in #148 #149  #150 could be useful to middle school level students.

We should consider modifying the teacher tips once this work is complete. Leaving unassigned currently, but creating this issue to track

**Comment by pixelzoom** [comment]
Summary of query parameters added in  #148 #149 #150.

The follow query parameters enable options in the "Concentration" and "Beer's Law Lab" sims.

`showSoluteAmount` - shows the solute amount (in grams) below the beaker in the "Concentration" screen, does not require a value

`beakerUnits=milliliters` - labels the beaker tick marks using mL (default is L)

`concentrationMeterUnits=percent` - displays percent concentration in the concentration meter (default in mol/L) 

Query parameters are added by appending a '?' to the URL, and separating each query parameter with a '&'.

Example with all 3 options enabled:

`http://phet.colorado.edu/en/simulation/beers-law-lab?showSoluteAmount&beakerUnits=milliliters&concentrationMeterUnits=percent`

**Comment by pixelzoom** [comment]
This work has been done for awhile, so...  Are we adding these to the Teach Tips?  If so, who will do that?

**Comment by ariel-phet** [comment]
This is probably a larger question for the design team as to how and where we want to reveal query parameters.

**Comment by pixelzoom** [comment]
How/where to reveal query parameters is also a general issue, not specific to this sim, correct?

**Comment by ariel-phet** [comment]
@pixelzoom exactly....planning on discussing it as a design team

**Comment by amanda-phet** [comment]
Discussed 9/5/17 with @ariel-phet @amyh-phet @oliver-phet and we discussed a few things. 

For universal query parameters: 
(1) A page within teaching resources (that can be added to over time) with some general info about query parameters and instructions on how to use ?screens= with examples. 
(2) a URL-generator that a user can input the info they want in their URL and the page generates a URL that can be copied and pasted. This might make more sense when we have more parameters, and might need to be on every sim page. 

For sim-specific parameters: 
(1) Include this information in the teacher tips 
(2) Add a section to the sim page with information and example URLs

For right now, we decided we'll add the above information to the Concentration and Beer's Law teacher tips. We'll want to discuss the other options listed above some more, especially with Kathy.

**Comment by pixelzoom** [comment]
On 9/5/2017, @amanda-phet said:
> ... For right now, we decided we'll add the above information to the Concentration and Beer's Law teacher tips. We'll want to discuss the other options listed above some more, especially with Kathy.

What is the status of this? Has the information been added to teacher tips?  Has this been discussed with @kathy-phet?

**Comment by amanda-phet** [comment]
I just checked and didn't see this in the teacher tips. I will bring it up at our website/design meeting on Tuesday.

**Comment by pixelzoom** [comment]
Since this issue was created, additional "public facing" query parameters have been added.  For the most current list, see [BLLQueryParameters.js](https://github.com/phetsims/beers-law-lab/blob/master/js/common/BLLQueryParameters.js) and read the documentation.

**Comment by amanda-phet** [comment]
We discussed this 8/17/18 (again) and in the short-term, either I or @CWilson4960 will add this to the BLL and Concentration teacher tips. Long-term we still need a teaching resources page about query parameters.

**Comment by amanda-phet** [comment]
@CWilson4960 please close this issue when you have uploaded the updated teacher tips for Concentration and BLL.
