### ISSUE TITLE
Incorrect type for soluteGramsProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#156]
The sim is trying to set a value for a derived property, this should probably be changed from TProperty to TDerivedProperty.

**Comment by samreid** [comment]
Fixed above, state wrapper is working again, closing.

**Comment by pixelzoom** [comment]
Reopening, so that I can find out the process to test this. I'm clearly not up to speed on how to test PhET-iO changes.

**Comment by pixelzoom** [comment]
I was under the impression that building with `grunt --brand=phet-io`, then running with ?togetherEvents.log=console&phet-io-standalone` was sufficient to test PhET-iO changes.

@samreid can you describe what additional testing needs to be done? Or point me to documentation on testing?

**Comment by samreid** [comment]
Different features are exercised by the different tests in together/phet-io-site/demos/wrappers.html, the feature in question was related to save/load, so the "state" wrapper was where I saw the issue.  From https://github.com/phetsims/together/blob/master/doc/how-to-instrument-a-phet-simulation.md#step-10-broader-testing

> Step 10: Broader testing

> Now that the simulation has been more broadly instrumented, the other general wrappers can be used for testing.

> The state test should show proper mirroring for many simulation states. It is entirely Property-based, and may not show the proper behavior for some cases, like games.
The data stream should show a message for every user and model event
The instance proxies test should show an item for each intrumented object. This tool is helpful to test for tandem leaks.
Test some of the previously instrumented simulations, such as Concentration, Faraday's Law or Color Vision to get a sense of what the wrappers should behave like.

**Comment by pixelzoom** [comment]
Perfect, thanks.
