### ISSUE TITLE
change ATDetector.Mode enum to string values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#157]
See https://github.com/phetsims/together/issues/327#issuecomment-178731008

**Comment by pixelzoom** [comment]
This should be a matter of:
(1) Change the values of ATDetector.Mode to strings
(2) In beers-law-lab-api.js the type of `detector.modeProperty` to `TString` and revise the comment (breaking change)

**Comment by pixelzoom** [comment]
According to @samreid, no one is using data from beers-law-lab yet, so we can change this.

**Comment by pixelzoom** [comment]
Change completed. Over to @samreid for a quick peek.

**Comment by samreid** [comment]
Looks great, closing.
