### ISSUE TITLE
revise implementation of `readoutProperty` in ConcentrationMeterNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#158]
While working on a new feature request (https://github.com/phetsims/beers-law-lab/issues/149), I ran across the `readoutProperty` in ConcentrationMeterNode, which was added  so that researchers can see exactly what the student sees in the meter. 

In https://github.com/phetsims/beers-law-lab/issues/149, I said:
> ... it would have been better to set the readoutProperty, and have that update the Text node, rather than the reverse. View should be getting its value from model, not the other way around.

In https://github.com/phetsims/beers-law-lab/issues/149#issuecomment-178074600, @samreid replied:

> Yes, that is a good idea.

Since this has already caused complications once in what should have been an unrelated feature, I'm going to go ahead and revise the implementation.

**Comment by pixelzoom** [comment]
The other problem with the current implementation is the name given to `readoutProperty`.  Everything else in the implementation related to the "readout" used the term "value": eg: valueNode, valueBackgroundNode, VALUE_X_MARGIN,...  For clarity, I'm also going to change the terminology through the implementation to "readout".

**Comment by pixelzoom** [comment]
Another problem with the existing implementation.  Here's how the Property is instantiated:

`var readoutProperty = new Property( READOUT_NO_VALUE, tandem.createTandem( 'readoutProperty' ) );`

This is incorrect. Property has no {Tandem} parameter, the tandem needs to be passed via the options. So there is currently no sign of `readoutProperty` in the data stream.  I'm guessing that this feature was added and never tested. 

The correct instantiation is:

`var readoutProperty = new Property( READOUT_NO_VALUE, { tandem: tandem.createTandem( 'readoutProperty' ) } );`

**Comment by pixelzoom** [comment]
Note that `readoutProperty` was also in the incorrect location in the API file, and was moved to the correct location in https://github.com/phetsims/together/commit/8e28d7368c552ba307a72a181b97c68c97307bfe.

**Comment by pixelzoom** [comment]
Work completed. Assigning to @samreid to review since he added the feature.

**Comment by samreid** [comment]
I tested that the readoutProperty was getting good data in the latest version, I'd also like to add a test in Axon for 2nd arg as tandem, since I've seen this problem before and expect to see it again.

**Comment by pixelzoom** [comment]
>  I'd also like to add a test in Axon for 2nd arg as tandem, since I've seen this problem before and expect to see it again.

If possible... don't test that the 2nd arg is a {Tandem}, test that the 2nd arg is an {Object} literal.  That's more general.

**Comment by samreid** [comment]
> If possible... don't test that the 2nd arg is a {Tandem}, test that the 2nd arg is an {Object} literal. That's more general.

Great idea, I tried that and found that it wasn't specific enough, because tandem instances are also typeof "object".

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/axon/issues/89#issuecomment-180562920:

> How about this?
> 
> `assert && assert( !options.constructor );`
> 
> An object literal has no constructor.
