### ISSUE TITLE
Readout solute amount and volume suggestions-- sometime in future

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/beers-law-lab#159]
Our colleagues are happy with the recent features added and will use the current version for the study. They had 2 suggestions for us to consider down the road. Logging them here: 

> 1) The readout for the solute amount could be more prominently displayed, perhaps in a box with a colored background. 
> 2) A readout for the water amount might be desirable in addition to the solute readout for use at the middle school level. 
> These are considerations if broader use at the middle school level is desired.

**Comment by pixelzoom** [comment]
These are 2 independent feature requests, so need to be tracked in 2 separate GitHub issues. I've split this up into #160 and #161.  Closing this issue.

@kathy-phet In the future, feel free to continue to put multiple requests into one GitHub issue. But know that the first thing that will happen is that the issue will need to be split up by a developer, and that takes developer time (in this case, 20 minutes).
