### ISSUE TITLE
Correct annotation for restricted read-write access on variable

### ISSUE THREAD

**Issue by mattpen** [phetsims/beers-law-lab#162]
When implementing the customization wrapper ( see phetsims/phet-io#267 ) with @samreid, we decided to make the name and formula variables in Solute.js to have read-write access for the phet-io API only, and read-only access for everyone else.  What is the best way to annotate this requirement in the line comments? 

We were currently planning to use `// @public (read-write)`

**Comment by pixelzoom** [comment]
// @public (read-write, phet-io)

**Comment by samreid** [comment]
> `// @public (read-write, phet-io)`

Does this indicate that it is read-only for everything that is not phet-io?  Should it?

**Comment by pixelzoom** [comment]
Oh wait... They're `// @public (read-only)`.  So we need a way to say "they're read-only in general, but read-write for phet-io".  We don't have a good way to do that with our current annotation convention.  For now, how about:

`// @public (read-only), (read-write, phetio)`

**Comment by samreid** [comment]
Fixed as prescribed, @pixelzoom please verify if you wish.

**Comment by pixelzoom** [comment]
Just out of curiosity...  Is name and formula read-write via PhET-iO so that you can change "Drink Mix"?  Seems like changing the name and formula for the more specific solutes should be a no no.   If I'm interpreting that correctly, then is there some way we can specify read-write for "Drink Mix" only?

**Comment by samreid** [comment]
A PhET-iO client may wish to change the label of Cobalt Nitrate to "Unknown X/Y/Z", etc, so I think this applies to all of them.  But generally, our grammar for visibility is type specific, not instance specific.
