### ISSUE TITLE
Change ConcentrationMeterNode.readoutProperty to a DerivedProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#163]

**Comment by pixelzoom** [comment]
Recommended that we don't do any further work on `readoutProperty`, and invest in https://github.com/phetsims/tandem/issues/8 instead.

**Comment by samreid** [comment]
From https://github.com/phetsims/tandem/issues/8

> In beers-law-lab, ConcentrationMeterNode was given {Property.<string>} readoutProperty to provide access to exactly what the user is seeing on the meter. This was at request of a customer. This was not a straightforward instrumentation, and required a relatively expensive change to the sim code. 

The sim may be better off if we roll back the readout from being a Property to a plain var.  Once tandem#8 is done, this would be possible.

**Comment by pixelzoom** [comment]
I don't follow. Why do we need readout at all (Property of plain var) if the text is accessible be TandemText?

**Comment by samreid** [comment]
Indeed it could just be a temporary var or no var at all, if the text is accessible via TandemText.

**Comment by pixelzoom** [comment]
My preference would be to ditch it entirely, and revert lines 190-216 of ConcentrationMeterNode to:

```js
  meter.valueProperty.link( function( value ) {
      if ( isNaN( value ) ) {
        valueNode.setText( NO_VALUE );
        valueNode.centerX = valueBackgroundNode.centerX; // center justified
      }
      else {
        valueNode.setText( Util.toFixed( value, VALUE_DECIMALS ) );
        valueNode.right = valueBackgroundNode.right - VALUE_X_MARGIN; // right justified
      }
  }
```

**Comment by samreid** [comment]
After implementing TandemText, I've rewritten ConcentrationMeterNode to use text like the above.  Many other changes had been made to the file previously, so I couldn't use the snippet in https://github.com/phetsims/beers-law-lab/issues/163#issuecomment-184343652 verbatim.  I've tested with PhET-iO event stream and with ?concentrationMeterUnits=percent and everything seems to be working, but I'm not sure if I've missed testing some other feature.  It would be good for @pixelzoom to review if/when he has time since he is much more familiar with this code and feature set.  I'll commit my changes shortly.

**Comment by samreid** [comment]
I almost forgot, we can now remove the instrumentation for the readoutProperty, I'll do that next.

**Comment by samreid** [comment]
OK I've removed the instrumentation from readoutProperty, grunt is passing.  As I said above:

> It would be good for @pixelzoom to review if/when he has time since he is much more familiar with this code and feature set. I'll commit my changes shortly.

**Comment by pixelzoom** [comment]
Reviewed commits, looks good. Closing.
