### ISSUE TITLE
Spurious message from concentration meter node's readoutTextNode on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#164]
From: https://github.com/phetsims/beers-law-lab/issues/163

A message like:

> beersLawLab.concentrationScreen.view.concentrationMeterNode.bodyNode.readoutTextNode textChanged {"oldText":"‪1.000 ‪‪‪‪‪mol/L‬‬‬‬‬‬","newText":"-"}

Is always outputting when the sim starts up.   This is because the concentration meter text is being created with the text `1.000 mol/L` for layout purposes before the correct text is set.

Is this a problem for the data stream? Possibly not, but the convention for the data stream is not to show initial values or spurious changes like this.

**Comment by pixelzoom** [comment]
Could use a temporary Text node to determine the dimensions of `readoutBackgroundNode`.   Then initialize `readoutTextNode` with the proper initial value.

**Comment by samreid** [comment]
That sounds good if it would not be too complicated.  I'm also wondering how many times this happens throughout our codebase.  If it happens everywhere, then we would have to choose something like (a) invest in changes like the one you described (b) look for a shortcut, such as toggling messages on and off or (c) just accepting that spurious messages are part of the data stream.  I'm inclined to investigate (a)  and see how far it can get us.

**Comment by pixelzoom** [comment]
I'm certain that this pattern occurs frequently. A better general pattern might be to choose a width and height for `readoutBackgroundNode` empirically, then use that width and height (minus some margin) as `maxWidth` and `maxHeight` for `readoutTextNode`.

**Comment by pixelzoom** [comment]
We've identified that this is a general issue, and I don't intend to address it in beers-law-lab until a general solution has been identified.  @samreid If you feel that this issue is worth addressing, please move it to a move general repository, then close this issue.

**Comment by samreid** [comment]
It would be best if data analyzers could tolerate this level of noise.  Let's plan on leaving in spurious messages like this for our initial release.

**Comment by pixelzoom** [comment]
Reopening for a question....

@samreid said:
> It would be best if data analyzers could tolerate this level of noise.

Is there a message that indicates when the sim has completed startup?  If not, how will data analyzers know what is startup "noise"?

**Comment by samreid** [comment]
This spurious message is a child of the "simStarted" event, so analyzers will know it happened during startup:

![image](https://user-images.githubusercontent.com/679486/30220513-e7f0d62e-947c-11e7-91d6-7c5ada7a45f7.png)

But more generally, it would be good if our analyzers are OK with this type of spurious data throughout the data stream.

**Comment by pixelzoom** [comment]
Thanks for the clarification. Closing.
