### ISSUE TITLE
Dropper leaves litter on the screen

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#166]
From https://github.com/phetsims/phet-io/issues/352

@phet-steele pointed out that the dropper and concentration meter node leave rendering artifacts when the sim is at certain sizes on iPad (where the size is controlled by the size of the iframe).

Testing with 
```html
<html>
<head>
</head>
<body>
<iframe id="sim"
        width="640"
        height="400"
        src="http://192.168.1.11/beers-law-lab/build/beers-law-lab_en.html">
</iframe>
</body>
</html>
```

I see:

![image](https://cloud.githubusercontent.com/assets/679486/13227194/b041a4e2-d952-11e5-9023-e29a05bf80af.png)

**Comment by pixelzoom** [comment]
Is this present in a published version? master?

**Comment by samreid** [comment]
The test I reported above was in master.  Steele's test was from http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.4/phet-io/protected/wrappers.html

**Comment by pixelzoom** [comment]
Recommended to try the published version. Then bisect to determine if recent scenery changes are causing this.

**Comment by pixelzoom** [comment]
@phet-steele or @samreid What version of iOS?

**Comment by samreid** [comment]
I'm sporting 9.2.1

**Comment by pixelzoom** [comment]
I don't have an iPad handy.  Can someone test with these older production versions, which pre-date 1.4.0-dev.4?

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0/beers-law-lab_en.html
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.1/beers-law-lab_en.html
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.2/beers-law-lab_en.html

**Comment by pixelzoom** [comment]
Presumably the AT detector's probe also leaves litter?

**Comment by pixelzoom** [comment]
High priority to test this on the published version (1.3.3), which will determine the priority of fixing it.

I asked @jonathanolson about this issue on Skype. His reply:

[2/29/16, 12:16:59 PM] Jonathan Olson: There have been a decent amount of Canvas changes in Scenery lately (if it's displayed in Canvas). Not fully sure.
[2/29/16, 12:17:11 PM] Jonathan Olson: Looks like a Scenery-related issue, feel free to assign to me for bisection if you want.
[2/29/16, 12:18:10 PM] Jonathan Olson: As I have an iPad available, and scripts to bisect for easier testing

**Comment by samreid** [comment]
Confirmed this issue is still appearing with the HTML given above, using latest master and built version.  There is a tiny bit of litter for the ATDetectorNode, but it is very rare.

I tested with the same HTML as above, but with the the link pointing at http://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_en.html which I confirmed in the about dialog, and I'm still seeing the litter.

This is not a high priority issue, since it is unlikely to interfere with student usage.

**Comment by jonathanolson** [comment]
This occurs in the published version.

**Comment by jonathanolson** [comment]
Looks like both elements are rendering in SVG on the iPad. Workaround may include adding an invisible rectangle at the bottom of the dropper.

Assigning to @ariel-phet for priority.

**Comment by samreid** [comment]
Also, let's consider a bug report to Apple/WebKit.

**Comment by pixelzoom** [comment]
I'm still not clear on whether this is a Scenery issue or Apple/WebKit bug.  I have a hard time believing that this got through the most recent RC test (1.3.0-rc.2), but we could determine that by testing as in https://github.com/phetsims/beers-law-lab/issues/166#issuecomment-190339119. And I disagree that it's not a high priority issue.  If this is something that snuck in via the recent Edge/Canvas maintenance patch, then it's going to affect all sims that have that patch.

**Comment by samreid** [comment]
I also see the same problem in 1.3.0

**Comment by pixelzoom** [comment]
Thanks, that makes me feel better.  And now that you explained to me that this happens at atypical window size on iPad, I agree that it's low priority -- and should perhaps be moved to a general issue?

**Comment by ariel-phet** [comment]
@pixelzoom to clarify it looks like this only happens in an embedded version (in an iframe) - mainly the iframe testing is pretty sanity check style.

Agreed low priority and agreed should be moved to a general issue.

Assigning to @jonathanolson to decide where the issue should live.

**Comment by jonathanolson** [comment]
Tracking in https://github.com/phetsims/scenery/issues/526, closing here.
