### ISSUE TITLE
Solute amount cannot be customized on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#172]
One of our PhET-iO clients would like to customize the solute amount when the simulation starts up.  Setting this value over query parameters doesn't work because the customized value gets overriden by this code in ConcentrationModel.js:

```js
    // Things to do when the solute is changed.
    thisModel.soluteProperty.link( function() {
      thisModel.solution.soluteAmountProperty.set( 0 );
    } );
```

Should this be made a `lazyLink` so that the default solute amount can be customized on startup?

**Comment by pixelzoom** [comment]
Does the customer want to use that same customized amount of solute each time the solute is changed? Or should changing the solute set the amount to zero, regardless of the startup amount?

**Comment by samreid** [comment]
Let's make it clear solute when changing solution.  If they want to change solutions and keep a fixed solute amount, they can do that with the PhET-iO API.

**Comment by pixelzoom** [comment]
Then yes, in ConcentrationModel:

```js
var soluteAmount = ( query parameter set ) ? ( query parameter value ) : SOLUTION_VOLUME_RANGE.defaultValue;
thisModel.solution = new ConcentrationSolution( thisModel.soluteProperty, SOLUTE_AMOUNT_RANGE.defaultValue, soluteAmount, tandem.createTandem( 'solution' ) );

thisModel.soluteProperty.lazyLink(...);
```

**Comment by pixelzoom** [comment]
Then yes, in ConcentrationModel:

```js
var soluteAmount = ( query parameter set ) ? ( query parameter value ) : 
SOLUTION_VOLUME_RANGE.defaultValue;
if ( !SOLUTION_VOLUME_RANGE.contains( soluteAmount ) ) {
  throw new Error( 'soluteAmount is out of range: ' + soluteAmount );
}

thisModel.solution = new ConcentrationSolution( thisModel.soluteProperty, soluteAmount, SOLUTION_VOLUME_RANGE.defaultValue, tandem.createTandem( 'solution' ) );

thisModel.soluteProperty.lazyLink(...);
```

**Comment by pixelzoom** [comment]
Also make sure that SOLUTE_AMOUNT_RANGE is documented somewhere in the API.

**Comment by samreid** [comment]
The following code is not necessary because the value can be set through the PhET-iO API:
```js
var soluteAmount = ( query parameter set ) ? ( query parameter value ) : 
SOLUTION_AMOUNT_RANGE.defaultValue;
if ( !SOLUTION_AMOUNT_RANGE.contains( soluteAmount ) ) {
  throw new Error( 'soluteAmount is out of range: ' + soluteAmount );
}
```

The range is provided in the API:

![image](https://cloud.githubusercontent.com/assets/679486/18057305/ab9189b2-6dcc-11e6-9e8c-2196bb814b2a.png)

Hence the only change we need to make is to change `link` to `lazyLink`.  Commit forthcoming.

**Comment by samreid** [comment]
Fixed above, here's a link that can be used for testing:

http://localhost/concentration/concentration_en.html?ea&brand=phet-io&phet-io.standalone&phet-io.log=lines&phet-io.expressions=[[%22concentration.concentrationScreen.model.solution.soluteAmountProperty%22,%22setValue%22,[1]]]

**Comment by samreid** [comment]
@pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Looks good, closing.
