### ISSUE TITLE
precipitate should not change while draining solution

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#175]
This issue was reported by @phet-steele in https://github.com/phetsims/beers-law-lab/issues/154#issuecomment-221085463.

@pixelzoom the `precipitateAmountProperty` is calculated over and over again while draining a solution. The value fluctuates up and down, causing the visual effect of precipitate appearing and disappearing while draining. The capture rate on this video is lower than I'd like, so it's not as dramatic looking:
![bll01](https://cloud.githubusercontent.com/assets/5863899/15483465/08973b70-20f2-11e6-89bf-043ad98ec5b0.gif)

**Comment by pixelzoom** [comment]
This issue sounds very familiar, like something I fixed long ago.  And in fact it does not occur in release 1.2.0 (http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.2.0/beers-law-lab_en.html).  Is it possible that this may have been (re)introduced by PhET-iO instrumentation?

**Comment by pixelzoom** [comment]
The issue I was thinking of is https://github.com/phetsims/concentration/issues/1 (Flickering particles when solution from dropper is added to a "Saturated!" beaker).

**Comment by pixelzoom** [comment]
Now I'm not so sure that I'm reproducing this reliability, so it may be something that was present in 1.2.3.  I'm also wondering it's demonstrable for other solutes, or just for "Potassium permanganate".

**Comment by pixelzoom** [comment]
@phet-steele, a few questions....

(1) Can you reproduce the problem with either of these older versions?
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.2.3/
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0/beers-law-lab_en.html

(2) Is the problem reproducible with other solutes? just with "Potassium permanganate"? or more noticeable with "Potassium permanganate"?  I'm wordering if this occurs mainly for solutes with low saturation points.

(3) What platform did you observer this on? And does it also occur on other platforms?

**Comment by phet-steele** [comment]
1. 1.2.3 NO, 1.3.0 YES
2. Doable on all, easiest for me to duplicate on KMnO4 just because it's quicker (low saturation point)
3. Win 10 chrome and OSX 10.11.5 Chrome

**Comment by pixelzoom** [comment]
@ariel-phet Should this be addressed for 1.4.0 release?  It's not immediately apparent why this problem reappeared in 1.3.x, but it was present in 1.3.x, so is not technically a new problem.  If this issue needs to be addressed for 1.4.0, then that will push 1.4.0 release out into August (given the other things on my plate). If this issue is deferred, then 1.4.0 release can likely happen sometime in the next week.  My recommendation is to defer.

**Comment by ariel-phet** [comment]
Since not a new problem (and since now summer), I concur to defer, but lets plan on patching after function builder goals are met.

**Comment by pixelzoom** [comment]
@ariel-phet said:
>  lets plan on patching after function builder goals are met.

It's now long after function-builder goals were met.  So I will self assign and look at this when I have time.

**Comment by pixelzoom** [comment]
@phet-steele Could you please test this in master and see if it's still a problem?   I can't seem to reproduce it anymore, wondering if was corrected by some other change (which would be disconcerting.)

**Comment by phet-steele** [comment]
> Could you please test this in master and see if it's still a problem?

I cannot see it in master.

**Comment by pixelzoom** [comment]
Well, the problem is apparently gone.  I see nothing obvious in the commit history that might have fixed it, mostly lots of PhET-iO commits that I don't recognize.   Since I can't identify the fix, I can't patch a maintenance release.  So this fix will need to wait for the next release branch (1.7).

**Comment by pixelzoom** [comment]
Marked as fixed-pending-testing for the next RC cycle.

**Comment by pixelzoom** [comment]
This problem has resurfaced.  In https://github.com/phetsims/beers-law-lab/issues/238#issue-436825355, @KatieWoe reported:

**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
Minor bug found in https://github.com/phetsims/QA/issues/309.
When there are a smaller number of particles sitting at the bottom of a saturated solution, draining the solution causes some of the particles to move along the bottom wildly until draining stops.  Seen in older versions, so not connected to the above release.
**Steps to reproduce:**
1. Select a solute and add it until you have a saturated solution with particles on the bottom
2. If there are too many particles, use the dropper to dilute it until you have a smaller number
3. Drain some of the solution and watch the particle behavior

**Screenshots:**
![dancingsalt](https://user-images.githubusercontent.com/41024075/56517761-00881d00-64fb-11e9-83ae-7e92214b43f0.gif)


Troubleshooting information (do not edit):

<details>

Name: ‪Concentration‬
URL: https://phet.colorado.edu/sims/html/concentration/latest/concentration_en.html
Version: 1.3.13 2019-04-22 08:50:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9bf8f88c","branch":"HEAD"},"babel":{"sha":"735d57d7","branch":"master"},"beers-law-lab":{"sha":"10281f45","branch":"HEAD"},"brand":{"sha":"b040cac5","branch":"HEAD"},"chipper":{"sha":"0ebc6913","branch":"HEAD"},"concentration":{"sha":"b4e5af61","branch":"HEAD"},"dot":{"sha":"04efe0bc","branch":"HEAD"},"joist":{"sha":"a9ad0567","branch":"HEAD"},"kite":{"sha":"dce9765e","branch":"HEAD"},"nitroglycerin":{"sha":"ad3cb990","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"3a85ef86","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"864e3a56","branch":"HEAD"},"scenery-phet":{"sha":"2b60b8e4","branch":"HEAD"},"sherpa":{"sha":"e90b735f","branch":"HEAD"},"sun":{"sha":"6f66368f","branch":"HEAD"},"tandem":{"sha":"29f64233","branch":"HEAD"}}

</details>

**Comment by pixelzoom** [comment]
The steps in https://github.com/phetsims/beers-law-lab/issues/175#issuecomment-486355881 are easier/quicker to follow if you use the shaker instead of the dropper.

**Comment by pixelzoom** [comment]
I cannot reproduce in master.  And I just noticed that https://github.com/phetsims/beers-law-lab/issues/175#issuecomment-486355881 says:

> Seen in older versions, so not connected to the above release.

So this was fixed, and appears to still be fixed. Closing.
