### ISSUE TITLE
increase the maximum amount of solute

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#177]
The shaker currently contains 6 moles of solute, and stops dispensing solute after 6 moles have been dispensed. NaCl saturates at 6.15 mol/L.  So if you have 1L in the beaker, you won't see saturation or precipitate.   If you want to see precipitate, you need to decrease the amount of water in the beaker.

This was reported as a bug in https://github.com/phetsims/beers-law-lab/issues/169#issuecomment-221095734, so there is definitely the opportunity for confusion.

Options:

(1) Leave as is and treat this as a "teachable moment"

(2) Investigate increasing the maximum amount of solute, perhaps to 7 moles.  No idea if this would cause problems in other areas of the model.

@ariel-phet @amyh-phet How would you like to proceed?  And would you like this addressed for the 1.4.0 release that is in progress?

**Comment by pixelzoom** [comment]
I don't recall why 6 moles was chosen as the maximum amount of solute. But I suspect that it was because "Drink Mix" had the highest maximum concentration, at 5.96 mol/L, and the beaker can be filled to a max of 1L.

**Comment by pixelzoom** [comment]
I tried setting the max solute amount to 7 moles, and I didn't see any problems.   So if you don't mind the potential to have a lot more precipitate, then it would probably be a safe change, and easy to patch into 1.4.

**Comment by ariel-phet** [comment]
@pixelzoom seems like a lot more precipitate is not a problem in my opinion. 

I will defer to @amyh-phet for this particular decision.

**Comment by amyh-phet** [comment]
@pixelzoom   I don't see an issue with increasing the max solute amount to 7 moles.

**Comment by pixelzoom** [comment]
@amyh-phet Do you favor increasing the max to 7, versus leaving it at 6 and having a "teachable moment" (with something in teacher tips)? See options in https://github.com/phetsims/beers-law-lab/issues/177#issue-158564921 - I need someone to pick one.

**Comment by amyh-phet** [comment]
@pixelzoom  I'm assuming increasing the max to 7 would be for all solutes.   If this is the case, I think I would favor going to a max of 7.  I think there is still a teachable moment here and we don't risk having the sim seem broken (or accidentally communicating that NaCl never saturates).

**Comment by pixelzoom** [comment]
Max solute amount increased to 7 moles in master and 1.4 branches.

**Comment by pixelzoom** [comment]
Steps to verify:
1. Start sim
2. Got to Concentration screen
3. Fill beaker to 1L
4. Select solute "Sodium chloride"
5. Put concentration probe in solution
6. Shake shaker until empty
7. Verify that concentration meter reads 6.150 mol/L
8. Verify that there is precipitate in the beaker

**Comment by brroberts1231** [comment]
Verified on OS X 10.10.5 Safari, and Win 7 Chrome, looks good.
 for phetsims/tasks#622 and phetsims/tasks#624

**Comment by pixelzoom** [comment]
Thanks @brroberts1231.

**Comment by pixelzoom** [comment]
Published in Beer's Law Lab 1.4.0 and Concentration 1.3.0.
