### ISSUE TITLE
shaker dispenses more than maximum amount of solute

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#179]
In https://github.com/phetsims/beers-law-lab/issues/176, it was noted that the shaker dispenses slightly more than BLLConstants.SOLUTE_AMOUNT_RANGE.max.  That extra amount simply disappears, but could be confusing to observe.   

As noted in https://github.com/phetsims/beers-law-lab/issues/176#issuecomment-224031009:

> The issue is that the max is computed based on the amount of solute that has hit the surface of the solution, not the amount of solute actually coming out of the shaker. So there's some excess solute dispensed that just disappears.

Fixing this will require a fairly significant model change: giving the Shaker (and Droppper, for consistency?) knowledge about how much solute it contains. 

Deferred for a future release.

**Comment by pixelzoom** [comment]
Here's the relevant code in ConcentrationModel.ts:

```typescript
    // Empty shaker and dropper when max solute is reached.
    this.solution.soluteMolesProperty.link( soluteAmount => {
      const containsMaxSolute = ( soluteAmount >= SOLUTE_AMOUNT_RANGE.max );
      this.shaker.isEmptyProperty.value = containsMaxSolute;
      this.dropper.isEmptyProperty.value = containsMaxSolute;
      this.dropper.enabledProperty.value =
        ( !this.dropper.isEmptyProperty.value && !containsMaxSolute && this.solution.volumeProperty.value < SOLUTION_VOLUME_RANGE.max );
    } );
```

**Comment by pixelzoom** [comment]
A little detective work... Max solute was increased from 6 to 7 mol in https://github.com/phetsims/beers-law-lab/commit/58e0a444176e1562e9845a6b0d2573a5add7df6b for #177. And it was indeed because of Sodium Chloride. From https://github.com/phetsims/beers-law-lab/issues/177#issue-158564921:

> The shaker currently contains 6 moles of solute, and stops dispensing solute after 6 moles have been dispensed. NaCl saturates at 6.15 mol/L. So if you have 1L in the beaker, you won't see saturation or precipitate. If you want to see precipitate, you need to decrease the amount of water in the beaker.

**Comment by arouinfar** [comment]
> the max amount of solute dispensed by the shaker and dropper was changed from 6 mol to 7 mol. That was presumably because Sodium Chloride has a max concentration of 6.15 mol/L, while all of the other solutes have a max concentration < 6 mol/L

I didn't even realize there was a limit on the shaker contents. I think there is a benefit to allowing Sodium Chloride to reach saturation, so the increase seems reasonable to me.

> So while it's too bad that the shaker sometimes dispenses a bit more than 7 mol, I don't think this is worth addressing. It's too costly, too destabilizing, and no one (other than Steele) has ever noticed. I recommend closing as "won't fix".

I don't think its worth addressing, closing.
