### ISSUE TITLE
Review new instrumentation

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#181]
Concentration has been re-instrumented for phet-io using the new paradigm recommended in https://github.com/phetsims/phet-io/issues/489 in which the TType classes are specified in the simulation itself.

The Beer's Law screen has not yet been re-instrumented.  That work will be completed in https://github.com/phetsims/phet-io/issues/497

It would be great if @pixelzoom has time to review the changes that put the types in the simulation. The changes have been merged into master, so you should be able to see a diff by pulling latest and comparing with a previous version from git history.

For instance, you could compare latest master to 58e0a444176e1562e9845a6b0d2573a5add7df6b

**Comment by samreid** [comment]
As part of this, could you also weigh in on https://github.com/phetsims/phet-io/issues/517 ?

**Comment by samreid** [comment]
I discovered that the built phet-io brand is launching but the phet brand is not, can you please hold off on this review until I figure that out?  It is in https://github.com/phetsims/phet-io/issues/518

**Comment by samreid** [comment]
OK the launch problem is fixed, details are in https://github.com/phetsims/phet-io/issues/518

Ready for review again.

**Comment by pixelzoom** [comment]
I'm starting the review now, will assign back to @samreid when done.

**Comment by samreid** [comment]
Thanks @pixelzoom, please contact me on Skype if something comes up that would benefit from voice discussion.

**Comment by pixelzoom** [comment]
(1) Not all TNumbers will have units

When `units` was added as a required parameter to TNumber, I wondered about why it was required, since not all numbers have units.  I now see what looks like a workaround for that in ATDetector.  Relevant code snippets:

TNumber, see line 59:

```var TNumber = function( units, options )```

ATDetector, line 72:

```type: TNumber && TNumber( 'unitless' )```

Recommended to make `units` an option to TNumber.

**Comment by samreid** [comment]
> The Beer's Law screen has not yet been re-instrumented.

That was completed in https://github.com/phetsims/phet-io/issues/497

**Comment by pixelzoom** [comment]
(2) Short-circuiting of addInstance

This pattern (which seems to be ubiquitous) feels very awkward. E.g. ATDetectorNode, line 172:

```TNode && tandem.addInstance( this, TNode );```

We may have discussed this previously... But why can't `addInstance` simply be a no-op when `phet.chipper.brand !== 'phet-io' && !type` ?

**Comment by samreid** [comment]
I see 161 occurrences of of `TNumber '`, 52 of which are 'unitless'.  My and @andrewadare's thinking was that making this required will ensure that developers have to consider the units instead of accidentally omitting them.  When we set out we weren't really sure how frequent unitless vs unit would occur, we could use this 52/161 as an argument about whether they should be optional or required.

@pixelzoom said:
> So (for example):

> ATDetector, line 72:
```type: TNumber && TNumber```

This would not work because TNumber is a parameterized type constructor and must be invoked to return the type.  So this would become:

```type: TNumber && TNumber()```

**Comment by samreid** [comment]
@pixelzoom what are your thoughts on creating a separate issue for each of your review comments that requires discussion, so that they are threaded properly and easy to search in the future?  For instance, you could create phet-io issues.

**Comment by pixelzoom** [comment]
I think the 32% of existing usages being 'unitless' is a pretty good argument for making it an option. And if you were going to make it required, it would be a good idea to create a string constant, and make it a noun (e.g. 'none') instead of an adjective.

**Comment by pixelzoom** [comment]
> what are your thoughts on creating a separate issue for each of your review comments 

OK, will do (retroactively).

**Comment by samreid** [comment]
Regarding (2) from https://github.com/phetsims/beers-law-lab/issues/181#issuecomment-235305781

> But why can't `addInstance` simply be a no-op when `phet.chipper.brand !== 'phet-io' && !type` ?

I think the change would be to make `addInstance` a no-op when `phet.chipper.brand !== 'phet-io'.  If `phet.chipper.brand === 'phet-io', then we would want to assert that the type exists, so it is not inadvertently omitted.  I'm OK with pursuing that strategy, but we should discuss this corner case first.  Some types such as TProperty and TNumber are parameterized and code like this would throw `undefined is not a function` when run in non-phet-io mode.

```js
type: TProperty(TString) // fails with undefined is not a function
```

**Comment by pixelzoom** [comment]
Review completed. Issues that I created are linked immediate above.

**Comment by samreid** [comment]
Thanks for your thoughtful recommendations, I think everything is tracked in other issues and this can be closed.
