### ISSUE TITLE
Not all TNumbers will have units

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#182]
Related to review of https://github.com/phetsims/beers-law-lab/issues/181.

When `units` was added as a required parameter to TNumber, I wondered about why it was required, since not all numbers have units.  I now see what looks like a workaround for that in ATDetector.  Relevant code snippets:

TNumber, see line 59:

```var TNumber = function( units, options )```

ATDetector, line 72:

```type: TNumber && TNumber( 'unitless' )```

Recommended to make `units` an option to TNumber.

So (for example):

ATDetector, line 72:
```type: TNumber```

Cuvette, line 38:
```type: TNumber && TNumber( { units: 'centimeters', range: widthRange } )```

**Comment by pixelzoom** [comment]
@samreid said:

I see 161 occurrences of of `TNumber '`, 52 of which are 'unitless'.  My and @andrewadare's thinking was that making this required will ensure that developers have to consider the units instead of accidentally omitting them.  When we set out we weren't really sure how frequent unitless vs unit would occur, we could use this 52/161 as an argument about whether they should be optional or required.

@pixelzoom said:
> So (for example):

> ATDetector, line 72:
```type: TNumber && TNumber```

This would not work because TNumber is a parameterized type constructor and must be invoked to return the type.  So this would become:

```type: TNumber && TNumber()```

**Comment by pixelzoom** [comment]
I think the 32% of existing usages being 'unitless' is a pretty good argument for making it an option. And if you were going to make it required, it would be a good idea to create a string constant, and make it a noun (e.g. 'none') instead of an adjective.

**Comment by pixelzoom** [comment]
Presumably 'unitless' is showing up in the data stream. Is there any value to that?

**Comment by andrewadare** [comment]
My vote is to stay with our original thinking on this. In fact, the problem here may not be that numbers are "unitless" too often because they're really unitless, but because we're not descriptive/diligent enough in assigning units.

A few selected examples:
```
 // In FAMB, this could be 'pullers' 
numberPullersAttached: TNumber && TNumber( 'unitless' ),

// In ESPB (SceneSelectionPanel.js), this could be 'index' or 'scene':
 node: createNode( 0 ),
 tandem: tandem.createTandem( 'scene1RadioButton' ),
 type: TNumber && TNumber( 'unitless' )

// In build-an-atom-api (not yet re-instrumented), could be 'protons' etc. or 'particles':
periodicTableAtom: {
protonCountProperty: TProperty( TNumber( 'unitless' ) ),
neutronCountProperty: TProperty( TNumber( 'unitless' ) ),
electronCountProperty: TProperty( TNumber( 'unitless' ) )
},
```

**Comment by andrewadare** [comment]
My previous comment suggests a broadening of the definition of measurements from the original tightly-specified SI quantities. For the sake of conveying useful information, I view this as allowable, if we're judicious about it. There are questions about how make things consistent and standard if we do this. We currently have a very rigorous whitelist of SI units to check against, so this would need further consideration.

**Comment by pixelzoom** [comment]
Broadening the definition is fine if it creates useful information in the data stream. Not OK if it creates additional work for the developer for no clear purpose.

**Comment by pixelzoom** [comment]
For example, having to specify this:

```js
protonCountProperty: TProperty( TNumber( 'protons' ) )
```

... so that the data stream reports:

> protonCountProperty: 25 protons

Is (imo) busy work that puts redundant information in the data stream.

**Comment by andrewadare** [comment]
Yeah, that looks redundant to a human, because I'm good at interpreting the key as a unit in this case. Having that extra word could be pretty useful for automated data analysis software.

I just don't view it as such a huge burden to type one extra word, but I guess it could add up over time.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/beers-law-lab/issues/182#issuecomment-235309213, @samreid said:
> My and @andrewadare's thinking was that making this required will ensure that developers have to consider the units instead of accidentally omitting them. 

It seems like this same concern would apply to `options.type`, which currently defaults to `'FloatingPoint'`.  Why is that not a required constructor parameter?

**Comment by andrewadare** [comment]
I guess some of the reasoning behind `FloatingPoint` is because we're working in JavaScript. Admittedly, that may not be such a strong reason.

Perhaps if the unit labels were to be given a less opinionated default value than 'unitless', some trouble could be avoided. Possibilities include 'NA', 'unassigned', '-', 'number', or something to that effect. Something easily searchable in a log file would be preferable. 

I understand the maintenance issue, but defaulting to 'unitless' is not great IMO. Between that and the whitelist, it practically begs developers to leave lots of TNumbers 'unitless' when in doubt, even when that's not an entirely correct categorization, and there's something useful to say. (And here we are, with 1/3 of our TNumbers in that category already). Put another way, following this proposal would make the metadata for a majority of variables silently incorrect until overridden.

As we know, it's hard to speculate how the (meta)data will be used by clients. But in principle, it seems very useful for people to have something always available that could be incorporated into column headers in a data table, database field labels, plot axis labels, and so forth.

I think of a default as being the right thing for the majority of uses, but I don't observe that TNumbers are really unitless in the majority of cases.

**Comment by samreid** [comment]
On the other hand, might required units lead to developers sometimes putting in the wrong units, just to "get things working"?  Whether or not units are required in the API, we may need a review step to check on the units.

**Comment by andrewadare** [comment]
> we may need a review step to check on the units.

That could be added to a code review, but it's hard to check what you can't see. (Yes, it could be seen in a data stream, but that starts getting painful pretty quickly).

Honestly, I don't care all that much about this, but at least I'd push for defaulting to 'number' or something like that.

**Comment by pixelzoom** [comment]
If units continues to be a required constructor parameter, then what are your feelings about my comment in https://github.com/phetsims/beers-law-lab/issues/182#issuecomment-235309267? 
> And if you were going to make it required, it would be a good idea to create a string constant, and make it a noun (e.g. 'none') instead of an adjective.

...and related issue https://github.com/phetsims/beers-law-lab/issues/186#issue-167650240.

I don't think that repeating the literal 'unitless' (or "meters" for that matter) is particularly desirable.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/beers-law-lab/issues/182#issuecomment-235358786, @samreid wrote:
> On the other hand, might required units lead to developers sometimes putting in the wrong units, just to "get things working"?

Indeed, I suspect we'll see a lot of `TNumber( '' )` or (more hopefully) `TNumber( 'TODO' )`.

**Comment by andrewadare** [comment]
@pixelzoom using a string constant, and referencing it like `TNumber.NO_UNITS` or something seems less preferable to using a benign default like 'none', 'number', or 'quantity'.

Agreed that making it a noun is better than an adjective, and I do agree that repeating 'unitless' all over the place is silly.

So maybe we're converging here.

**Comment by samreid** [comment]
> That could be added to a code review, but it's hard to check what you can't see.

We could write a script or query parameter that outputs all of the TNumbers and their units for manual review.

**Comment by samreid** [comment]
Do we have consensus on this?  Tagging for developer meeting if not.

**Comment by andrewadare** [comment]
To summarize my position, I'm fine with making `units` an optional parameter for TNumber, but would prefer other labels (see suggestions above) to 'unitless' as the default value.

**Comment by samreid** [comment]
What about defaulting to `null`?

**Comment by samreid** [comment]
To me "null" is as clear or clearer than "NA", "unassigned", "number" etc.

**Comment by samreid** [comment]
OK we agreed to make units optional and null by default.  We'll leave FloatingPoint as the default type because it is more frequent.

**Comment by pixelzoom** [comment]
`range` and `values` are currently displayed as `null` if not provided, so +1 for doing the same for `units`.

**Comment by samreid** [comment]
Marking high-priority in order to add to my todo list.

**Comment by samreid** [comment]
I'll start work on this now, notifying @andrewadare in case he is in the neighborhood.

**Comment by samreid** [comment]
I made units optional in the preceding commit, and tested with concentration/instance proxies.  It was working nicely (units displayed properly).  Running sim tests with ?loadOnly reveals no problems related to TNumber.  @andrewadare or @pixelzoom do you want to review?

**Comment by pixelzoom** [comment]
Looks good, but there may be a formatting issue.  Using the PhET style, my IDEA wants to format this:

```angle: TNumber( {units: 'radians'} )```

like this, with spaces around curly brackets:

```angle: TNumber( { units: 'radians' } )```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/beers-law-lab/issues/182#issuecomment-235321038, @andrewadare mentioned that some of the TNumbers that were 'unitless' should in fact have units. Is there anything that needs to be addressed related to that?  Doesn't look like it was addressed in @samreid's commits.

**Comment by samreid** [comment]
Fixed formatting above.  I recall when I pushed previously, the IDEA reformat on commit checkbox was checked and grayed out, perhaps there was something odd happening there, I'm not sure what.  I've iterated through the `{units` and reformatted them and moved https://github.com/phetsims/phet-io/issues/540 to a separate issue.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
👍 Closing.
