### ISSUE TITLE
Short-circuiting of `addInstance`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#183]
Related to review of #181.

This pattern (which seems to be ubiquitous) feels very awkward, and different from how we typically use `&&` to short-circuit something. E.g. ATDetectorNode, line 172:

```TNode && tandem.addInstance( this, TNode );```

We may have discussed this previously... But why can't `addInstance` simply be a no-op when `phet.chipper.brand !== 'phet-io' && !type` ?

**Comment by samreid** [comment]
It looks like the latter issue can be solved by returning function(){} as will be done in https://github.com/phetsims/phet-io/issues/534

So the remainder of this issue will be to search through these short circuits and removing them.

**Comment by samreid** [comment]
Short circuits were removed in https://github.com/phetsims/phet-io/issues/534

@pixelzoom can you review this issue and that one?

**Comment by pixelzoom** [comment]
👍 Closing.
