### ISSUE TITLE
is short-circuiting of T types necessary?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#185]
Related to code review of #181.

The ifphetio plugin currently returns `null` if PhET-iO is not enabled. And that necessitates having to write code with short-circuiting. 

For example:

```js
var TNumber = require( 'ifphetio!PHET_IO/types/TNumber' );
```

... requires this type of short-circuiting where TNumber is used:

```js
type: TNumber && TNumber( 'unitless' )
```

Instead of returning `null`, how about returning `function() {}` (a no-op).  Then this short-circuiting would be unnecessary.

**Comment by samreid** [comment]
Bumping priority to put on my radar for investigation and testing.

**Comment by samreid** [comment]
Let's track this in phet-io, see above issue, closing.
