### ISSUE TITLE
convention for TNumber units?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#186]
Related to code review #181.

What is the convention for specifying units for TNumber?  In beers-law-lab, it looks like the convention is to use full names for the units, e.g. in Evaporator:

```js
type: TNumber && TNumber( 'liters/second' )
```

Since PhET sims typically display SI symbols (e.g. "L/sec") to the user, I'm wondering 

(1) Why the data stream is not using the same units displayed to the user?

(2) Is this convention followed in other instrumented sims?

(3) Should these units be encapsulated somewhere as constants, instead of repeated as (possibly incorrect) string literals?

**Comment by pixelzoom** [comment]
Here's another example from beers-law-lab.   This is what is displayed to the user:

![screenshot_65](https://cloud.githubusercontent.com/assets/3046552/17146168/9ab55c80-531a-11e6-83ef-94a5e2315d31.png)

This is what will appear in the PhET-iO data stream (ConcentrationSolution, line 75):

```js
tandem: tandem.createTandem( 'concentrationProperty' ),
type: TNumber && TNumber( 'moles/liter' )
```

Why is the user shown "mol/L", while the data stream uses "moles/liter"?

**Comment by andrewadare** [comment]
One big reason we went with spelling out the units is for validation. They can be checked straightforwardly (is that a word?) against the array in TNumber.js.

This provides uniformity and consistency, but as discussed in #182, it also has downsides.

**Comment by pixelzoom** [comment]
I don't follow. Why couldn't the array in TNumber correspond to what the user typically sees?

**Comment by andrewadare** [comment]
It doesn't correspond lexicographically to what the user sees, but it does in meaning. When working on this with @samreid, I asked similar questions.

If I recall correctly, his thinking was that spelled-out units are easer to search for (e.g. in logs and in code) and they are more reliable to validate. There was also the hope to avoid annoyances with capitalization of metric prefixes, unit names, and so forth by just going with lowercase.

**Comment by samreid** [comment]
> Why couldn't the array in TNumber be populated with what the user typically sees?

What the user sees depends on the sim design and in other languages may be translated to something else.  The simulation isn't always modeled in view units, sometimes different units are used for the model.  To make the data stream easy for researchers, and 3rd party groups easy to understand and work with, we recommended using the full text for the units.  And if everything was abbreviated, someone trying to navigate the API would be facing alphabet soup.  L, mol, m, a, V is confusing.  Liters, moles, meters, amperes, volts is clearer.  The simulation is also instrumented so that 3rd parties can see the text as the student sees it (with unit readouts), but @andrewadare and I thought it would be best to be clear for the PhET-iO API even though it is more verbose.

**Comment by pixelzoom** [comment]
>  spelled-out units are easer to search for

I don't understand this at all.  How is "moles/liter" any easier to search for than "mol/L". They are both unique strings.

>  they are more reliable to validate

Again, no comprendo. Validation is string comparison. "moles/liter"  and "mol/L" are both strings. What's the difference?

**Comment by pixelzoom** [comment]
> To make the data stream easy for researchers, and 3rd party groups easy to understand and work with, we recommended using the full text for the units. And if everything was abbreviated, someone trying to navigate the API would be facing alphabet soup. L, mol, m, a, V is confusing. Liters, moles, meters, amperes, volts is clearer.

Don't understand this either.  The researchers are presumably familiar with science. SI abbreviations are standardized.  And if SI abbreviation are so "confusing", then why is is that what PhET sims consistently display to students?

**Comment by pixelzoom** [comment]
The other point is that (as a developer) I consistently document things throughout my code using the units that are displayed to the user.  Now I'm are going to have to remember to spell it out for PhET-iO.  

And we're all going to have to remember whether it's 'liters' or 'litres". Which, btw, is currently *wrong* in TNumber. The SI spelling is 'litres', not 'liters', see https://en.wikipedia.org/wiki/Non-SI_units_mentioned_in_the_SI.

**Comment by pixelzoom** [comment]
Tracking 'litres' vs 'liters' in https://github.com/phetsims/phet-io/issues/529

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/phet-io/issues/529#issuecomment-235382203, @samreid pointed out that there is disagreement about whether 'liters' or 'litres' is the official full name.  Just so that my point isn't missed... There is obvious disagreement about whether 'liters' or 'litres' is correct. There appears to be no such disagreement about 'L'. And supporting both 'liters' and 'litres' defeats consistency (much like 'henrys' and 'henries', which are both in TNumber btw).

Seeing 'henrys' and 'henries' also makes me wonder... Have you consider the singular vs plural aspect of this issue?  Full names have singular and plural versions, abbreviations do not. For example, spelled out, '1L' and '2L' would be '1 liter' and '2 liters' respectively.  This is admittedly a nit, but the grammar police won't be happy.

**Comment by samreid** [comment]
I'm comfortable switching to abbreviations for the PhET-iO metadata.  Since there is a 1:1 mapping from abbreviations to actual units, there shouldn't be a problem (and if we wanted to add tools that expand the abbreviations, it would be straightforward).  I like the argument that it's what we use in the simulations.

Sound OK @andrewadare?

**Comment by andrewadare** [comment]
I don't object to abbreviating, I can see good reasons for it. But I also don't think the original rationale was nonsensical either.

> I don't understand this at all. How is "moles/liter" any easier to search for than "mol/L". They are both unique strings.

A string like "mol/L" is easy to find, but if the units are just liters, meters, or pretty much anything that abbreviates down to one or two characters, things get tougher.

> Again, no comprendo. Validation is string comparison. "moles/liter" and "mol/L" are both strings. What's the difference?

Same response as above. Also, I didn't say it can't be done.

Let's just abbreviate as is done in the sim.

**Comment by pixelzoom** [comment]
> A string like "mol/L" is easy to find, but if the units are just liters, meters, or pretty much anything that abbreviates down to one or two characters, things get tougher.

I see, you're talking about searching for the character `L` (for example) versus `liters`. I would typically search for `'L'`, with quotes around it.  But I get it... long strings, more likely to be unique and fewer false positives.

**Comment by samreid** [comment]
OK so we are agreed to abbreviate units.  Let's move to this comment from @pixelzoom:

> (3) Should these units be encapsulated somewhere as constants, instead of repeated as (possibly incorrect) string literals?

Let me show the alternatives as I understand them:

```js
// option 1, string units
type: new TNumber('mol/L'),

// option 2, constant units
type: new TNumber(TNumber.MOL_L)
```

I'm not strongly attached to one of these options, but slightly prefer how 'mol/L' looks exactly like its value.  It seems with either approach we would need a step that checks whether the units are valid, if TNumber.MOL_L is of type string.

**Comment by pixelzoom** [comment]
I'm fine with options 1 (string literals at the call sites). But if we want to change any units (like we're doing now), it will require a bit of work, and searching for (e.g.) 'mol/L' is likely to result in false positives.

If we did option 2, is TNumber the appropriate place for this?

**Comment by pixelzoom** [comment]
With option 1, we could presumably reduce false positives by searching for "TNumber( 'mol/L'", assuming that all code formatting follows PhET style.  Or we could use regular expressions if there are concerns about that.

If units were an option to TNumber (see #182), we could search for "units: 'mol/L'", with the same caveat about code formatting.

**Comment by samreid** [comment]
I've moved the "abbreviate units" issue to phet-io#530 (linked above)

**Comment by samreid** [comment]
The consensus is to abbreviate units, we shall proceed in phet-io#530, closing.
