### ISSUE TITLE
Were addInstance calls intentionally removed?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#187]
Related to code review #181.

In EvaporationControl and SoluteControls, the call to `addInstance` that previously appeared at the end of the constructor has been removed.  Was that intentional?

**Comment by samreid** [comment]
Yes, they both extend Panel, which recently got its own addInstance, so they are still instrumented.

**Comment by samreid** [comment]
Perhaps I'll leave this issue open to guarantee @pixelzoom has a chance to see and discuss, if necessary.

**Comment by pixelzoom** [comment]
> Yes, they both extend Panel, which recently got its own addInstance, so they are still instrumented.

If that's the case, then perhaps there's an error here. No tandem is currently passed in the options to the supertype (Panel) constructor in either subtype.

**Comment by samreid** [comment]
You're right, there was an error.  The tandems were omitted in the options to Panel.  I have rectified this in the preceding commit, please review.

**Comment by pixelzoom** [comment]
Inspected, looks good, closing.
