### ISSUE TITLE
method of loading the PhET-iO API file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#188]
Related to code review #181.

It looks like the PhET-iO API must now be loaded in main.js, using an assignment-less `require` call, like this in beers-law-lab-main.js:

```js
  // If running as phet-io, load the API
  require( 'ifphetio!PHET_IO/api/beers-law-lab-api' );
```

Did you consider other ways of doing this? Some alternatives:

(1) If the convention is to for the API file and repository to have the same name, could loading the API be handled automatically in Sim.js?  E.g.:

```js
// If running as phet-io, load the API
if ( phet.chipper.brand === 'phet-io' ) {
  require( 'ifphetio!PHET_IO/api/' + phet.joist.packageJSON.name );
}
```

(2) Add an `api` option to Sim.js.  

```js
var sim = new Sim( ...., {
  phetioApiFile: 'beers-law-lab-api.js'
} );

Then in Sim constructor:

```js
 // If running as phet-io, load the API
 options. phetioApiFile && require( 'ifphetio!PHET_IO/api/' + options.phetioApiFile );
```

**Comment by pixelzoom** [comment]
Ah... But I guess (1) and (2) wouldn't work because Screens are typically instantiated before the Sim.  Eg in beers-law-lab-main.js:

```js
  SimLauncher.launch( function() {
    var sim = new Sim( beersLawLabTitleString, [
      new ConcentrationScreen( tandem.createTandem( 'concentrationScreen' ) ),
      new BeersLawScreen( tandem.createTandem( 'beersLawScreen' ) )
    ], simOptions );
    sim.start();
  } );
```

**Comment by pixelzoom** [comment]
(3) Load the API file on demand (using `phet.joist.packageJSON.name`) the first time that a tandem call is made.

**Comment by pixelzoom** [comment]
(4) Encapsulate the method of loading the API in phet-io.  E.g. in main.js:

```js
Tandem.init(); // and use `phet.joist.packageJSON.name` to identify the API file
```

or 

```js
Tandem.init( 'beers-law-lab-api.js' );
```

**Comment by pixelzoom** [comment]
(4) Encapsulate the method of loading the API in phet-io.  E.g. in main.js:

```js
Tandem.init(); // use `phet.joist.packageJSON.name` to identify the API file name
```

or 

```js
Tandem.init( 'beers-law-lab-api.js' );  // specify the API file name
```

This approach would be useful if there's other initialization that's required in the future.

**Comment by samreid** [comment]
Are you reviewing a stale version of beers-law-lab-main.js?  Master looks like this and doesn't show the statement you are referring to.
https://github.com/phetsims/beers-law-lab/blob/master/js/beers-law-lab-main.js

It was removed when we re-instrumented using the "types specified by the sim" paradigm.

**Comment by pixelzoom** [comment]
I was comparing master to 58e0a444176e1562e9845a6b0d2573a5add7df6b, as recommended in https://github.com/phetsims/beers-law-lab/issues/181#issue-166931862.  Looks like I was confused and thought this was something that was added, when in fact it was removed.  Closing.
