### ISSUE TITLE
Make it possible for variableWavelengthProperty to be true on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#192]
From https://github.com/phetsims/phet-io/issues/568

> remove "preset" option in wavelengths. Leave the variable option but remove the box that reveals the wavelength in nanometers. Use phet-io to remove the radio buttons, make "variable" the default

The code currently assumes that variableWavelengthProperty is false on startup, we will need to modify it so that the node is not added twice.

The solution will look like this:
```js
    // When the radio button selection changes...
    this.variableWavelengthProperty.link( function( isVariable ) {
      if ( isVariable ) {

        // When running in PhET-iO, the variableWavelengthProperty can start out as true
        // and we must protect against adding the wavelength slider twice
        if ( !content.hasChild( wavelengthSlider ) ) {
          content.addChild( wavelengthSlider );
        }
      }
      else {
        content.removeChild( wavelengthSlider );
      }
      if ( !isVariable ) {
        // Set the light to the current solution's lambdaMax wavelength.
        light.wavelengthProperty.set( solutionProperty.get().molarAbsorptivityData.lambdaMax );
      }
    } );
```

**Comment by samreid** [comment]
The problem is the wavelength slider is getting added twice if variableWavelengthProperty is true on startup:

```
Assertion failed: Parent already contains child
```

**Comment by pixelzoom** [comment]
This request feels like we're headed down the slippery slope.

Where is this proposed change going to be added?  Where in the above code is "the box that reveals the wavelength" hidden?

**Comment by samreid** [comment]
> This request feels like we're headed down the slippery slope.

Meet me on Skype for realtime voice access.

> Where in the above code is "the box that reveals the wavelength" hidden?

I addressed that in https://github.com/phetsims/beers-law-lab/issues/193 and it is assigned to you for review.

**Comment by samreid** [comment]
@pixelzoom and I reviewed this and it seems good to close.
