### ISSUE TITLE
Instrument nodes in the WavelengthControls

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#193]
From https://github.com/phetsims/phet-io/issues/568

> remove "preset" option in wavelengths. Leave the variable option but remove the box that reveals the wavelength in nanometers. Use phet-io to remove the radio buttons, make "variable" the default, probably need to instrument the "410 nm" wavelength box so that can be hidden.

**Comment by samreid** [comment]
Fixed above, @pixelzoom would you like to review the change set https://github.com/phetsims/beers-law-lab/commit/5e9422ced0dc6d1dfa65a0548fdbd3b4e29b9171 ?

**Comment by pixelzoom** [comment]
👍 Closing.
