### ISSUE TITLE
Publish current version of wrapper

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#195]
@kathy-phet requested @samreid to publish the current version of the wrapper for ETS and UBC to review.

Tagging @andrewadare and @mattpen and @pixelzoom so they are aware.

**Comment by samreid** [comment]
Oops, I used `grunt --build-phet-io` instead of `grunt build-phet-io`.  Trying again.

**Comment by kathy-phet** [comment]
Just to add to this. We just shared via Zoom, and they see a bunch of preliminary early QA they want to do involving their computers and such. They know there are coming improvements.

**Comment by samreid** [comment]
There are numerous lint errors:

~/github/beers-law-lab$ grunt --brand=phet-io
Running "eslint:allFiles" (eslint) task

/Users/samreid/github/phet-io/apps/data-graph-app/beers-law-lab_data-graph-app.js
  236:7  error  "row" is defined but never used  no-unused-vars

/Users/samreid/github/phet-io/apps/data-graph-app/data-graph-app.js
   7:5   error  Strings must use singlequote  quotes
   8:5   error  Strings must use singlequote  quotes
   9:5   error  Strings must use singlequote  quotes
  10:5   error  Strings must use singlequote  quotes
  11:5   error  Strings must use singlequote  quotes
  11:22  error  Strings must use singlequote  quotes
  12:5   error  Strings must use singlequote  quotes
  13:5   error  Strings must use singlequote  quotes
  14:5   error  Strings must use singlequote  quotes
  14:21  error  Strings must use singlequote  quotes
  15:5   error  Strings must use singlequote  quotes
  15:21  error  Strings must use singlequote  quotes
  16:5   error  Strings must use singlequote  quotes
  16:16  error  Strings must use singlequote  quotes
  17:5   error  Strings must use singlequote  quotes
  17:24  error  Strings must use singlequote  quotes
  18:5   error  Strings must use singlequote  quotes
  18:19  error  Strings must use singlequote  quotes
  19:5   error  Strings must use singlequote  quotes
  19:19  error  Strings must use singlequote  quotes
  20:5   error  Strings must use singlequote  quotes
  20:19  error  Strings must use singlequote  quotes
  21:5   error  Strings must use singlequote  quotes
  21:19  error  Strings must use singlequote  quotes
  22:4   error  Missing semicolon             semi

✖ 26 problems (26 errors, 0 warnings)

Warning: Task "eslint:allFiles" failed. Use --force to continue.

**Comment by samreid** [comment]
d3 version was mismatched, I'll try deploy once more.

**Comment by samreid** [comment]
Published here:
https://phet-io.colorado.edu/0.1/sims/beers-law-lab/1.5.0-dev.5/phet-io/protected/apps/data-graph-app/data-graph-app.html?sim=beers-law-lab

**Comment by samreid** [comment]
I sent an email about this version.
