### ISSUE TITLE
Beam's shapeProperty undefined => null

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/beers-law-lab#196]
The sim was trying to set a Path's shape to undefined, since Beam's shapeProperty was undefined (instead of null) if beamVisible is falsy.

This was failing when Scenery's cleanup branch assertion failed.

**Comment by jonathanolson** [comment]
@pixelzoom, can you review the change to make sure I didn't break anything subtle?

**Comment by pixelzoom** [comment]
👍 Closing.
