### ISSUE TITLE
Is `resize: false` necessary in this sim?

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#198]
In https://github.com/phetsims/sun/issues/282 I noticed Beer's Law Lab has `resize: false` in two spots, which I thought was a workaround for the buggy slider bounds, but when I reverted HSlider and removed `resize: false`, BLL still seemed to work properly.  Hence I am not sure why BLL needs to supply `resize: false`.  @pixelzoom can you please take a look at your convenience?

**Comment by pixelzoom** [comment]
Probably vestigial. `resize: false` removed in above commit. Closing.
