### ISSUE TITLE
User question: controlled variables

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/beers-law-lab#199]
Perhaps @amyh-phet can help answering this user question?

> I am working on a Chemistry investigation about spectrophotometry and I would like to use your Beer's Law virtual laboratory.
> 
> If that is possible, I would like to ask three questions:
> - What are the controlled variables in the virtual lab? Is there any value for the assumed temperature, humidity or athmospheric pressure?

**Comment by pixelzoom** [comment]
@amyh-phet this may be of use in answering the questions:

Model description:
https://github.com/phetsims/beers-law-lab/blob/master/doc/model.txt

Molar absorptivity data:
https://github.com/phetsims/beers-law-lab/blob/master/js/beerslaw/model/MolarAbsorptivityData.js

I looked through the teacher tips and Java design doc, but didn't see anything about assumed temperature, humidity or atmospheric pressure.

**Comment by amyh-phet** [comment]
@oliver-phet   All solutions are assumed to be at 25 degrees Celsius except for drink mix. The solubility of drink mix is based on the solubility of sucrose at 20 degrees Celsius.  No assumed values were used for humidity or atmospheric pressure as these parameters do not influence concentration of dissolved solids (or the amount of solute needed to reach saturation).

You might want to point to the teacher tips for this user.  The values for temperature are listed in the Teacher Tips.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.
