### ISSUE TITLE
documentation: queryParameters available

### ISSUE THREAD

**Issue by jgpATs2w** [phetsims/beers-law-lab#201]
I suggest to include in documentation the queryParameters: showSoluteAmount, concentrationMeterUnits and beakerUnits, the README could be a good place.
It can be nice to users (at least developers) to know about this visualization options.

**Comment by ariel-phet** [comment]
@pixelzoom any comment here....I believe you would have documented these, perhaps the documentation is in a less obvious place to someone unfamiliar with our sim architecture?

**Comment by pixelzoom** [comment]
Hello @jgpATs2w.

The majority of query parameters are _not_ intended for use by simulation users. And PhET's documentation currently lacks any specification about which query parameters are OK to use. So PhET does not generally advertise this documentation.  That said...

In the past, PhET did attempt to document query parameters in a user-friendly file, for internal use within the PhET development team.  But the documentation quickly got out of sync with the implementation.  So we moved to a strategy where we consolidate all query parameters in one or more Javascript files, then document the query parameters in those files. 

Query parameters that apply to all PhET simulations are in [initialize-globals.js](https://github.com/phetsims/chipper/blob/master/js/initialize-globals.js).

Query parameters that are specific to a simulation are in a file that uses one of two naming conventions, which I'll attempt to explain.  In general, for a simulation named "My Favorite Simulation", the associated GitHub repository is named `my-favorite-simulation`, and the query parameters are defined in either `my-favorite-simulation/js/common/MyFavoriteSimulationQueryParameters.js`, or `my-simulation/js/common/MFSQueryParameters.js` (where 'MyFavoriteSimulation' is abbreviated as 'MFS').  For example, the query parameters for "pH Scale" are in [PHScaleQueryParameters.js](https://github.com/phetsims/ph-scale/blob/master/js/common/PHScaleQueryParameters.js), while the query parameters for "Beers Lab Lab" are in [BLLQueryParameters.js](https://github.com/phetsims/beers-law-lab/blob/master/js/common/BLLQueryParameters.js).  If there are no simulation-specific query parameters, then this file will not exist.

If/when PhET decides to advertise query parameters, we'll certainly consider making the documentation more user-friendly.  In the meantime, there are no plans to change this approach.  So closing this issue as "won't fix".

**Comment by pixelzoom** [comment]
... and if any of the above is unclear, feel free to reopen this issue and ask further questions.
