### ISSUE TITLE
PhET-iO cannot control the text justification in the sensor.

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#202]
From https://github.com/phetsims/phet-io/issues/411

It may be nice to give the PhET-iO developer control over the justification of the text in the sensor *or* to indicate that it isn't possible.  Currently it centers when `-` and left justified when reading a value.

Another way out of this trouble would be to always center the readout, but that is probably not what the design team specified.  Leaving unassigned until we work on another publication of this sim.

**Comment by pixelzoom** [comment]
> It may be nice to give the PhET-iO developer control over the justification of the text in the sensor or to indicate that it isn't possible.

Justification is an aesthetic aspect, and has nothing to do with functionality.  It is also not something that can be simply changed on a Node, it would require special code - to handle something that is unlikely to ever be needed.  So I think this is something that is reasonable to tell the client "you can't do that".    And I think that's probably true of justification in general.

**Comment by pixelzoom** [comment]
If we insist on providing PhET-iO control over justification, then it should be addressed _generally_. We should create something like scenery-phet.TextField, which has control over field width, justification, margins, border, etc.   This is most definitely not something that sim-specific code should be handling.   So I suggest that you move this to an issue in a more general repository.

**Comment by samreid** [comment]
We should wait until there is a need for this feature.  @pixelzoom OK to close?

**Comment by pixelzoom** [comment]
Yep, ok to close.
