### ISSUE TITLE
Sensor text area needs maxWidth

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#203]
From https://github.com/phetsims/phet-io/issues/413

@andrewadare and I tried adding this code to ConcentrationMeterNode.js and after 5 seconds saw this:

``` js
    setTimeout(function(){
      readoutTextNode.text = 'VERY LONG TEST,VERY LONG TEST,VERY LONG TEST,'
    },5000);
```

![image](https://cloud.githubusercontent.com/assets/679486/18453110/f10f74ca-78fa-11e6-9a0a-327deeb826d6.png)

Leaving unassigned until we work on the next version of this sim.

**Comment by pixelzoom** [comment]
The readout does have `maxWidth` set.  In ConcentrationMeterNode:

```js
    var maxTextWidth = 225; // constrain text width for i18n, determined empirically
    ...
    var readoutTextNode = new Text( formattedText, {
      font: new PhetFont( 24 ),
      fill: 'black',
      maxWidth: maxTextWidth,
      tandem: tandem.createTandem( 'readoutTextNode' )
    } );
```

And `?stringTest=long` shows no problem:

![screenshot_370](https://user-images.githubusercontent.com/3046552/29833429-a950e156-8ca8-11e7-9702-650abf567fdf.png)

So there must be something funny going on here related to PhET-iO.  @samreid thoughts?

**Comment by pixelzoom** [comment]
This is presumably a problem in both ConcentrationMeterNode and ATDetectorNode, since their implementations follow the same general pattern.

**Comment by samreid** [comment]
In recent PhET-iO simulations, we have benefited from starting with a PhET-iO Sim Design meeting to ask what should be configurable with PhET-iO.  For this simulation, it is unclear that a PhET-iO client should be able to dynamically set the text to be a very long string.  My recommendation is to close the issue.  @pixelzoom does this sound OK to you?

**Comment by pixelzoom** [comment]
@samreid said:
> My recommendation is to close the issue. @pixelzoom does this sound OK to you?

Yep. Done.
