### ISSUE TITLE
Some nodes not instrumented for PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#205]
From https://github.com/phetsims/phet-io/issues/762

<img width="554" alt="screen shot 2016-10-28 at 11 49 42 am" src="https://cloud.githubusercontent.com/assets/5863899/19817135/6b702946-9d07-11e6-9c07-3968d899f0d5.png">

<img width="555" alt="screen shot 2016-10-28 at 12 08 30 pm" src="https://cloud.githubusercontent.com/assets/5863899/19817137/70d3564c-9d07-11e6-88e0-73dc5e589881.png">

**Not Pictured**

All of these are missing their associated node:

`beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.trackInputListener: TTandemDragHandler`
`beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.thumbInputListener: TTandemDragHandler`
`beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener: TTandemDragHandler`
`beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener: TTandemDragHandler`

For two examples of correctly instrumented nodes and what I mean by "associated nodes", both these track and thumb nodes are instrumented:
`beersLawLab.concentrationScreen.view.evaporationControl.slider.track.trackInputListener: TTandemDragHandler`
with
`beersLawLab.concentrationScreen.view.evaporationControl.slider.track: THSliderTrack`

`beersLawLab.concentrationScreen.view.evaporationControl.slider.thumbInputListener: TTandemDragHandler`
with
`beersLawLab.concentrationScreen.view.evaporationControl.slider.thumb: TNode`

For phetsims/tasks/issues/718.

Edit: now also for phetsims/tasks/issues/724.

@zepumph can you please investigate?

**Comment by pixelzoom** [comment]
See also https://github.com/phetsims/beers-law-lab/issues/165 (instrument other readouts?)

**Comment by pixelzoom** [comment]
See also #126 (use HSlider)

**Comment by pixelzoom** [comment]
@zepumph If you make any changes other that adding tandems, please consult with me.

**Comment by zepumph** [comment]
I'm going to put this issue on hold as we determine what is important to instrument, since "everything" seems to not be the answer anymore. Unassigning until https://github.com/phetsims/phet-io/issues/1178 is complete.

**Comment by zepumph** [comment]
Someone can let me know if they disagree and I'm happy to just do this.

**Comment by pixelzoom** [comment]
@samreid It would be nice to address this in the "Stable PhET-iO Design" meetings.

**Comment by pixelzoom** [comment]
This will be addressed in API redesign #230.

**Comment by pixelzoom** [comment]
For these:

```
beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener: TTandemDragHandler
beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener: TTandemDragHandler
```

ConcentrationControl was reimplemented as a subtype of NumberControl in #126, and now has all of the instrumentation that comes with NumberControl.

**Comment by pixelzoom** [comment]
For these:

```js
beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.trackInputListener: TTandemDragHandler
beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.thumbInputListener: TTandemDragHandler
```

... the problem (if it's still a problem) is likely in SCENERY_PHET/SpectrumSlider.

**Comment by pixelzoom** [comment]
Looking at wavelengthSlider in Studio, I see something totally different now.   So leaving this closed, and we'll reconfirm when we revise the API.
