### ISSUE TITLE
branch: 1.6

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#207]
[EDIT: A branch name like 1.6 is typically a release branch and doesn't require explanation. But branch 1.6 is a special kind of crazy, and requires documentation.]

Slack discussion:

> @pixelzoom Very confused about beers-law-lab. The published version is 1.4.3.  But I see branches 1.5-phetio, 1.6 and 1.6-phet-io.  1.6 is a brand=phet production release branch.  Anyone know what’s going on?
@pixelzoom Branch 1.6 created by matt.   Why?
@zepumph Looks like it was created at the same time as 1.6-phetio, maybe a mistake?
@pixelzoom There are no published dev version from 1.6.

**Comment by pixelzoom** [comment]
@mattpen if creation of this branch was indeed accidental, I'd like to delete it. 

@zepumph You create 1.6-phetio.  Do you recall any coordination with @mattpen related to 1.6 and 1.6-phetio?

**Comment by pixelzoom** [comment]
1.6 was created by @mattpen on 12/2/2016.
1.6-phetio was created by @zepumph on 2/13/2017.
So I'm betting there was no coordination/relation between these branches.

**Comment by pixelzoom** [comment]
There were 2 commits to the 1.6 branch, both by @mattpen: https://github.com/phetsims/beers-law-lab/commit/6bb24036ec57daaed78e1f29cf918d6fc7821b68, https://github.com/phetsims/beers-law-lab/commit/3b9be25e4474420e7c730f9f3033d60ae325f66a.   The first updates the version id to 1.6.0, the second one updates dependencies.json for 1.6.0.   So it sure looks like he was doing a 1.6.0 release, which is a little disconcerting.

**Comment by pixelzoom** [comment]
@zepumph checked the phet-io server to see if there was an inadvertent 1.6.0 deploy, and there was not.  And I see no 1.6.0 deploy in spot:dev/html/beers-law-lab/.   So how dependencies.json got pushed with version id 1.6.0 is a mystery.  That file is typically pushed via deployDev.js or wrapperDeploy.js.

**Comment by pixelzoom** [comment]
The plot thickens.  @zepumph noticed that some of the publications from the 1.6-phetio branch precede creation of that branch.  On spot:dev/html/beers-law-lab:

```
drwxr-xr-x   5 mape5853 physphet    4096 Dec  2  2016 1.6.0-phetio/
drwxr-xr-x   6 mape5853 physphet    4096 Jan 12  2017 1.6.2-phetio/
drwxr-xr-x   5 mika5203 physphet    4096 Feb 13  2017 1.6.3-phetio/
```

1.6.0-phetio and 1.6.1-phetio were both published by @mattpen (mape5853), and their dates preceded the creation of the 1.6-phetio branch.   Then on 2/13/17, the same date as creation of the 1.6-phetio branch, @zepumph (mika5203) published 1.6.3-phetio.  

So the hypothesis is that the 1.6 branch name was incorrect, but was still used to do `grunt --brand=phet-io`.   Then the error was noted, and 1.6-phetio deploys moved over to the 1.6-phetio branch.

This illustrates 2 major problems with PhET-iO build process:
(1) When doing a deploy, the branch name should have the form `{{major}}.{{minor}}-phetio`. That would have prevented deploying 1.6.x-phetio from the 1.6 branch.
(2) Cramming 'phetio' into the version id is a _bad idea_.

**Comment by pixelzoom** [comment]
So... I suppose we'll need to keep the 1.6 branch (for 1.6.0-phetio and 1.6.1-phetio) and the 1.6-phetio branch (for 1.6.2-phetio and onwards).  I'll change the title of this issue to "branch: 1.6" since the 1.6 obviously needs special documentation.

@mattpen please confirm or deny the above :)

**Comment by zepumph** [comment]
If all above is true, then can't branch "1.6" be deleted because 1.6-phetio was taken from 1.6, and then maintenance released on top of it. So 1.6-phetio is the branch we are maintaining, see the picture below as a reference to how 1.6 has nothing unique in it.

![image](https://user-images.githubusercontent.com/6856943/29848481-67462d78-8ccd-11e7-8306-b338e0d6b292.png)

**Comment by pixelzoom** [comment]
@zepumph 
> .If all above is true, then can't branch "1.6" be deleted because 1.6-phetio was taken from 1.6, and then maintenance released on top of it.  ...

Yikes, more craziness.  Release branches are always branched from master. But apparently  not in this case.  So yeah, I guess we can delete 1.6.   But better confirm with @mattpen.

**Comment by mattpen** [comment]
@pixelzoom - It appears that this branch was indeed created accidentally, and I agree with @zepumph that it can be deleted.  I believe that 1.6-phetio was used for a release of the lab-book wrapper, so it should probably be retained.  Apologies for the confusion.

**Comment by pixelzoom** [comment]
Thanks for the clarification @mattpen.  I'll delete the 1.6 branch and close this issue.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
