### ISSUE TITLE
Concentration sliders can break the sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/beers-law-lab#208]
Carried from https://github.com/phetsims/phet-io/issues/617 into this repo.

@samreid  said:
Some of the sliders (like drinkMixConcentrationProperty) can crash the sim. Does it need better range?

**Comment by pixelzoom** [comment]
Which sim is this referring to?  phetsims/phet-io#617 gives no clues. There are concentration sliders and "drink mix" in a few sims.  

And should this issue be in a sim-specific repository?  Is suspect that if instance-proxies is having a problem, then it's because `phetioType.range` is missing for some Property.

**Comment by zepumph** [comment]
@samreid would know best in terms of the specifics of the issue.

>And should this issue be in a sim-specific repository? I suspect that if instance-proxies is having a problem, then it's because phetioType.range is missing (or wrong) for some Property.

Then that sounds like it would be a problem for the specific repo then, to fix the range in that property? Since you assign the range to the instance like 
```js
new Property( {{number}}, {phetioValueType: TNumber( {range: new Range({{. . . }})})});

**Comment by pixelzoom** [comment]
@samreid said:
> Some of the sliders (like drinkMixConcentrationProperty) can crash the sim. Does it need better range?

I search the PhET code base for "drinkMixConcentrationProperty", not found.

**Comment by zepumph** [comment]
Quite possible that this is an outdated issue then.

**Comment by pixelzoom** [comment]
"drink" appears in beers-law-lab and molarity, both of which are instrumented.  So I suspect that this issue is related to an instrumentation bug in one of those (my) sims.

**Comment by pixelzoom** [comment]
... or, as @zepumph, this may be something that was fixed and is no longer an issue.

**Comment by zepumph** [comment]
Assigning @samreid for input. I suspect BLL and not Molarity because the original issue was opened Sep 12, 2016. That was well before Molarity was on the PhET-iO plate.

**Comment by pixelzoom** [comment]
Ah... I now see that this issue was created in beers-law-lab.  Guess I got confused by the [instance-proxies] prefix in the issue title.

**Comment by zepumph** [comment]
I was hoping that prefix was helpful, please make recommendations if you feel differently, and we can fix it.

**Comment by pixelzoom** [comment]
The prefix is redundant, that's the purpose of labels.

**Comment by samreid** [comment]
The Beer's Law Lab beersLawLab.beersLawScreen.solutions.drinkMix.concentrationProperty can now exercise its full range with no crashing.  Let's close this issue.
