### ISSUE TITLE
Convert Particles.changedCallbacks to use Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#216]
Noted during https://github.com/phetsims/beers-law-lab/issues/213.

Particles.js defines:

```js
    this.changedCallbacks = []; // @protected called when the collection of particles changes

/// ...

    /**
     * Registers a callback that will be called when the collection of particles changes in some way
     * (eg, number of particles, particles move, ...)
     * @param {function} callback
     * @public
     */
    registerChangedCallback: function( callback ) {
      this.changedCallbacks.push( callback );
    }
```

Then Precipitate.js has this code:

```js
    // @private Notify that the precipitate has changed.
    fireChanged: function() {
      var changedCallbacks = this.changedCallbacks.slice( 0 ); // copy to prevent concurrent modification
      for ( var i = 0; i < changedCallbacks.length; i++ ) {
        changedCallbacks[ i ]( this );
      }
    },
```

And ShakerParticles.js defines this code:
```js
    // @private Notify that at least one particle was added, removed, or moved
    fireParticlesChanged: function() {
      var changedCallbacks = this.changedCallbacks.slice( 0 );
      for ( var i = 0; i < changedCallbacks.length; i++ ) {
        changedCallbacks[ i ]();
      }
    }
```

This code should be rewritten to use axon Emitter.

**Comment by pixelzoom** [comment]
This sim implements its own listener mechanism because (1) it was ported directly from the Java version, and (2) the port predates the existence of Emitter.  I question the value (and cost) of such as small amount of working/straightforward code.  But I guess it's good to be consistent.

**Comment by pixelzoom** [comment]
Same pattern noted in gravity-and-orbits and scenery, see above issues.

**Comment by pixelzoom** [comment]
Conversion to Emitter completed.  Also required a change to TShakerParticles.  Test in requirejs mode and with instance-proxies wrapper.  Next savings was 11 lines of code.

@samreid please review.

**Comment by samreid** [comment]
The change set looks correct and I tested by saturating a solution then diluting it.  Closing.
