### ISSUE TITLE
branch: ioobject

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#219]
To support https://github.com/phetsims/tandem/issues/36

**Comment by samreid** [comment]
On hold (so it won't appear in my todo list) until https://github.com/phetsims/tandem/issues/36 is complete.

**Comment by samreid** [comment]
https://github.com/phetsims/tandem/issues/36 is approved and now we should move this code to master.  Note we will need to rename as described in https://github.com/phetsims/tandem/issues/43#issuecomment-351846924

I'll take care of this and reassign to @pixelzoom for review afterwards.

**Comment by samreid** [comment]
Renamed, merged to master, deleted `ioobject` branch, reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
BLL was failing lint in master after the merge, fixed in the above commit.  I also made a few gratuitous/OCD formatting tweaks. 

Looks generally good, closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
