### ISSUE TITLE
problems with this.tandemName

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#221]
```js
// BeersLawSolution.js
98 this.tandemName = tandem.tail;

// Solute.js
74 this.tandemName = tandem.tail;
```

Problems:
(1) No documentation
(2) No visibility annotations
(3) Bad names - these are not the tandem names of these instances. These are the tail of the tandem ids.

**Comment by zepumph** [comment]
@pixelzoom how is that? I'm not thrilled about renaming these two, as it has become a bit of a convention to call the tail `tandemName`. This corresponds to the instance's type name most often being the same as the tail. I tried to document that.
