### ISSUE TITLE
clean up IO types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#222]
IO types in BLL have inconsistencies in naming and documentation.

ShakerParticles.js appears to be an up-to-date example. It has parameter names that make sense, and type expressions:

```js
  /**
   * @param {ShakerParticles} shakerParticles
   * @param {string} phetioID
   * @constructor
   */
  function ShakerParticlesIO( shakerParticles, phetioID ) {
```

PrecipitateParticle.js appears to be an out-of-date example. It uses `instance` for the first parameter, and has no type expressions:

```js
  /**
   * @param instance
   * @param phetioID
   * @constructor
   */
  function PrecipitateParticleIO( instance, phetioID ) {
```

Since I'm responsible for this sim, I'm going to bring all the IO types up to standard.

**Comment by pixelzoom** [comment]
I cleaned up the IO types, but was unable to test because of https://github.com/phetsims/joist/issues/469.   Assigning to @samreid to review and test.

**Comment by pixelzoom** [comment]
@samreid search for "TODO #222" and you'll find some cleanup that still needs to be done.

**Comment by samreid** [comment]
I added docs in the preceding commit, ready for review.

**Comment by pixelzoom** [comment]
👍
