### ISSUE TITLE
ShakerParticlesIO is calling private methods

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#223]
Noted while working on #222.

ShakerParticlesIO is calling 2 private methods of ShakerParticles: `removeAllParticles` and `addParticle`.  I never intended these method to be part of the public API.  This needs to be fixed.

**Comment by samreid** [comment]
Would you be opposed to marking those methods as `public (phet-io)`?  If so, can you suggest an alternate approach that would allow PhET-iO to set the state of the shaker particles?

Also, there is a chance that we may be able to eliminate the state of the shaker particles when we have the "Stable PhET-iO Design" for this simulation--if the design team decides that the shaker particles are ultimately transient and do not need to be recorded in the state.

**Comment by pixelzoom** [comment]
@samreid asked
> Would you be opposed to marking those methods as public (phet-io)?

Simply changing their visibility annotation to `@public` is not appropriate. As noted in https://github.com/phetsims/beers-law-lab/issues/223#issue-283400179, the are `@private` because they were not designed to be called by clients.   If we want them to be `@public`, I'll need to revisit the implementation, and investigate what changes are needed to make them `@public`. 

I think we should leave this open until you've decided whether their state needs to be recorded.  If their state does need to be recorded, then I'll need to revisit the implementation.

**Comment by samreid** [comment]
Agreed, leaving open until after the stable PhET-iO design, unassigning for now.

**Comment by pixelzoom** [comment]
ShakerParticlesIO was deleted as part of #244, so this issue can be closed.
