### ISSUE TITLE
question about IO types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#224]
Many questions while I was doing #222 (clean up IO types)

- [x] (1) `fromStateObject` (I assume from it's name) returns an instance of the same type that appears in the IO type's constructor.  But `SoluteParticle` returns `{{location: Vector2, orientation: number}}`.  What's going on here?  Similarly for `Shaker` - how is this serializing and deserializing a `Shaker`?

- [x] (2) What does `clearChildInstances` do? It wasn't previously documented.  I search for other occurrences, and they are either not documented, or documented differently.  I chose "Clears the children from the model so it can be deserialized." but I'm not certain that it's correct, and (if it is) I don't fully understand it. 

- [x] (3) What is this comment ConcentrationModelIO trying to tell me?

```js
    // For instance:
    // http://localhost/concentration/concentration_en.html?ea&brand=phet-io&phetioStandalone&phetioLog=lines
```

- [x] (4) BeersLawSolutionIO `fromStateObject` has this comment:

```js
     * Because the simulation has a Property that contains BeersLawSolution,
     * the Property relies on these methods for saving and loading the values.
```

I don't understand this.  And `toStateObject` doesn't appear to be doing any serialization, it's just returning the `{string} phetioID`.  What's going on here?

- [x] (5) Throughout the IO types, `fromStateObject` appears before `toStateObject`.  It would make a lot more sense (and be more readable) to put `toStateObject` (serialization) before `fromStateObject` (deserialization).

**Comment by samreid** [comment]
> - [ ] (1) `fromStateObject` (I assume from it's name) returns an instance of the same type that appears in the IO type's constructor.  But `SoluteParticle` returns `{{location: Vector2, orientation: number}}`.  What's going on here?  Similarly for `Shaker` - how is this serializing and deserializing a `Shaker`?

For value types like `Vector2`, `fromStateObject` returns a newly created instance.  For reference types like `Property` and `Shaker`, the value deserialized in `fromStateObject` is set to the instance in `setValue`.  I'm not sure what's happening in `SoluteParticle`, probably something odd--will need further investigation.

> What does `clearChildInstances` do? It wasn't previously documented. 

Please see the "Support Dynamic State" section in the phet-io instrumentation guide:
https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#support-dynamic-state .  In short, clearChildInstances clears a container so it can be populated with the correct child instances (see link for context and details).

> - [ ] (3) What is this comment ConcentrationModelIO trying to tell me?

I removed the stale comment in a preceding commit.

> - [ ] (4) BeersLawSolutionIO `fromStateObject` has this comment:

BeersLawSolutions are singletons with reference identities (not overriden equals implementations), so we code them via their unique `phetioID` and look them up by that `phetioID`.

> - [ ] (5) Throughout the IO types, `fromStateObject` appears before `toStateObject`.  It would make a lot more sense (and be more readable) to put `toStateObject` (serialization) before `fromStateObject` (deserialization).

Agreed, I'll create an issue to do so.

Leave self-assigned to work on `SoluteParticleIO` and to create an issue for putting toState before fromState.

**Comment by samreid** [comment]
I decided to move the outstanding work to new issues, reassigning the remainder of this issue to @pixelzoom for discussion.  If all seems well, ok to close.

**Comment by pixelzoom** [comment]
@samreid and I discussed a few subtitles over Zoom.  I'm (mostly) clear on what's going on here now. Closing.
