### ISSUE TITLE
SoluteParticleIO doesn't implement setValue

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#225]
From https://github.com/phetsims/beers-law-lab/issues/224 it seems like a reference type but there is no `setValue`, what's happening?

**Comment by pixelzoom** [comment]
PrecipitatePariticlesIO was also a reference type, but no longer exists.  It's still mentioned in the "How To" doc (see https://github.com/phetsims/phet-io/issues/1296).  But perhaps the example there is related to the missing `setValue` for SoluteParticleIO.  The example for PrecipitatePariticlesIO looks like this:

```js
    setValue: function( instance, fromStateObject ) {
      // done in constructor, nothing else to do here, could be omitted
    }
```

**Comment by samreid** [comment]
I see, the SoluteParticleIO.toStateObject/fromStateObject are not called by PhET-iO directly, but rather called from its subtypes.  This seems reasonable and I'll add a note to the docs as such.

**Comment by samreid** [comment]
@pixelzoom can you please review?  Close if all is well.

**Comment by pixelzoom** [comment]
@samreid said:
> I see, the SoluteParticleIO.toStateObject/fromStateObject are not called by PhET-iO directly, but rather called from its subtypes. This seems reasonable and I'll add a note to the docs as such.

After previous discussions, my understanding was that "reference" types implemented `setValue` as a necessary means of restoring state.  Apparently that's not always true for reference types, and  SoluteParticleIO is an example.   But I don't understand why, and the documentation doesn't make it clear.

**Comment by samreid** [comment]
I see, this is confusing because `fromObjectState` is not called by the PhET-iO framework directly.  Instead it is called from ShakerParticles.addChildInstance:

```js
    /**
     * Create a dynamic particle as specified by the phetioID and state.
     * @param {ShakerParticles} shakerParticles
     * @param {Tandem} tandem
     * @param {Object} stateObject
     * @returns {ChargedParticle}
     */
    addChildInstance: function( shakerParticles, tandem, stateObject ) {
      assert && assertInstanceOf( shakerParticles, phet.beersLawLab.ShakerParticles );

      var value = ShakerParticleIO.fromStateObject( stateObject );
      assert && assert( value.acceleration instanceof Vector2, 'acceleration should be a Vector2' );

      shakerParticles.addParticle( new ShakerParticle(
        value.solute,
        value.location,
        value.orientation,
        value.velocity,
        value.acceleration, {
          tandem: tandem
        }
      ) );

      // Particles.step is not called in playback mode, so this needs to be called explicitly to update the view.
      shakerParticles.fireChanged();
    }
```

**Comment by pixelzoom** [comment]
I going to duplicate what I said over in https://github.com/phetsims/beers-law-lab/issues/226#issuecomment-357364999, because it applies here as well:

> I'm going to close this issue, even though I still don't full understand this. The fact that I don't have a good understanding of the IO types in a sim that I'm responsible for concerns me.  And I don't feel confident that I could implement custom IO types without a lot of hand holding.  There seem to be more patterns and special cases than are explained in [how-to-instrument-a-phet-simulation-for-phet-io.md](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md).
