### ISSUE TITLE
State wrapper is crashing

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#226]
From #224, I observed that the state wrapper is crashing for BLL, but not for other sims.  Self-assigning for investigation.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/225 perhaps?

**Comment by samreid** [comment]
The fix committed above repairs the crash, but there are still several toStateObjects that are large (hundreds or thousands of lines of code) that need to be cleaned up.

**Comment by pixelzoom** [comment]
Could you clarify the previous comment? Hundreds or thousands of lines of code in BLL, or elsewhere?

**Comment by samreid** [comment]
I've got the simulation state pruned down to 14000 lines of JSON--I still have a long way to go!

**Comment by pixelzoom** [comment]
So the "hundreds or thousands of lines of code" is in the saved state (JSON) that is the output of `toStateObject`?

**Comment by samreid** [comment]
Yes, more specifically the 14000+ lines of JSON is the full text output in the state wrapper (which is a composite of all the individual `toStateObject` calls.

**Comment by samreid** [comment]
After the preceding cleanup, it is down to 848 lines of JSON.  I'd volunteer to close the issue but wondering if @pixelzoom has questions about it that we should discuss now.

**Comment by pixelzoom** [comment]
I don't understand this comment that was added to `Movable`:

`35 phetioState: false // location is through composition`

I understand that (as documented in `PhetioObject`) setting `phetioState: false` means that the instance is not included in the PhET-iO state.   I'm guessing that "location" is referring to the value of `this.locationProperty`.  But I have no guess for what "through composition" means, since Movable is used solely for inheritance (not composition) in BLL.

**Comment by samreid** [comment]
I originally meant that the location of the Movable would be instrumented through the `Movable.locationProperty`.  However, I also realized that Movable doesn't need to extend PhetioObject, so this `phetioState:false` is a moot point.  Committed above and back to you for follow-up discussion, if any.  Close if all is well.

**Comment by pixelzoom** [comment]
Reopening.  This was added to ShakerParticlesIO, and I don't understand it at all:

```js
    /**
     * Overrides the super type toStateObject (which was grabbing JSON for the entire instance) to return an empty instance.
     * The state is set through child instances and composition.
     * @returns {Object}
     */
    toStateObject: function() {return {};},
```

**Comment by samreid** [comment]
ShakerParticlesIO inherits from ObjectIO which returns the entire object as its own state:

```js
    /**
     * Return the json that ObjectIO is wrapping.  This can be overriden by subclasses, or types can use ObjectIO type
     * directly to use this implementation.
     * @param {Object} o
     * @returns {Object}
     */
    toStateObject: function( o ) {
      return o;
    },
```

That fails because it tries to JSONify the entire object tree which includes many attributes which should not be serialized.

I tried using `phetioState: false` to disable state from the ShakerParticles altogether, but found out it is necessary to leave the default of `phetioState: true` since it uses the `clearChildInstances` / `addChildInstance` strategy for serialization support.

**Comment by pixelzoom** [comment]
I'm going to close this issue, even though I still don't full understand this. The fact that I don't have a good understanding of the IO types in a sim that I'm responsible for concerns me.  And I don't feel confident that I could implement custom IO types without a lot of hand holding.  There seem to be more patterns and special cases than are explained in [how-to-instrument-a-phet-simulation-for-phet-io.md](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md).
