### ISSUE TITLE
make Concentration slider thumb move in increments of 5

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#229]
Requested by @kathy-phet for a PhET-iO client, but generally useful.  Make the Concentration slider thumb move in increments of 5 (view units), regardless of the units or range.  Tweakers will still move in increments of 1.

**Comment by pixelzoom** [comment]
Also provide a maintenance release for the PhET-iO client.  @zepumph @samreid please identify release branch that needs to be patched.

**Comment by samreid** [comment]
It would be safest to patch 1.5 and 1.6, but we may be able to rule out 1.5 if we can determine that clients will not be using it any longer.

**Comment by pixelzoom** [comment]
@kathy-phet would like this in the next few days.

**Comment by pixelzoom** [comment]
Ugh.  This is not going to be straightforward because BLL does not use the common-code slider (HSlider).  See https://github.com/phetsims/beers-law-lab/issues/126.   @kathy-phet Should we address that issue before doing this?  It will be significantly more work, and more difficult to patch in 1.6-phetio.

**Comment by samreid** [comment]
When we switch to common code HSlider, that may warrant a new version from master instead of patching an old branch.

**Comment by pixelzoom** [comment]
I figured out where to change this in ConcentrationSlider, so the most expedient way to satisfy this is to ignore HSlider.   But complicating this is the fact that the model units are M, while the view is in either uM or mM.   So constraining to '5' means computing what '5' would be in M.

**Comment by pixelzoom** [comment]
@arouinfar Please review [1.7.0-dev.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.1/phet/beers-law-lab_en_phet.html).  If this looks OK, I'll patch the 1.6-phetio release branch.

**Comment by kathy-phet** [comment]
I did quick trial and it seemed to work great to me.

**Comment by arouinfar** [comment]
Looks good to me too. Thanks @pixelzoom!

**Comment by pixelzoom** [comment]
We're ready to do a 1.6-phetio maintenance release. I haven't published a PhET-iO version yet, and it looks like this release branch requires chipper 1.0.   @samreid @zepumph please advise.

**Comment by zepumph** [comment]
If @jonathanolson hasn't done this release yet for the scenery bug, then everything will be taken care of when he does that. @pixelzoom does this need an rc test before publishing?

**Comment by pixelzoom** [comment]
@zepumph asked:
> does this need an rc test before publishing?

Since this is a release branch and has been published before, I would guess that it's already been through RC test.  But I can't find a test matrix or GitHub issue indicating that 1.6-phetio has been RC tested.  @samreid?

**Comment by kathy-phet** [comment]
Steele tested it for the purposes of this study. Not sure if full rc.

Let’s publish for this particular use.

Kathy

Sent from my iPhone

On Jul 13, 2018, at 9:41 AM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


@zepumph<https://github.com/zepumph> asked:

does this need an rc test before publishing?

Since this is a release branch and has been published before, I would guess that it's already been through RC test. But I can't find a test matrix or GitHub issue indicating that 1.6-phetio has been RC tested. @samreid<https://github.com/samreid>?

**Comment by pixelzoom** [comment]
@kathy-phet What is the deadline for publishing?

@jonathanolson When will you be doing the "release for the scenery bug"?

**Comment by pixelzoom** [comment]
Following Slack conversation with @jonathanolson, @samreid, @zepumph...

@jonathanolson will handle the 1.6.5 maintenance release.  Please report here when completed.

**Comment by kathy-phet** [comment]
Thanks for the update. No definitive deadline but I will send it along when it is ready. I’m sure sooner would be better but I imagine they won’t do much with it until sometime next week.

Sent from my iPhone

On Jul 13, 2018, at 12:00 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


Following Slack conversation with @jonathanolson<https://github.com/jonathanolson>, @samreid<https://github.com/samreid>, @zepumph<https://github.com/zepumph>...

@jonathanolson<https://github.com/jonathanolson> will handle the 1.6.5 maintenance release. Please report here when completed.

**Comment by jonathanolson** [comment]
1.6.5 is deployed, but still has the wrong path on the phet-io server. @samreid or @zepumph, can this sim be run from /sims/beers-law-lab/1.6.5, or is a workaround for the directory name needed?

**Comment by samreid** [comment]
That path works great--we don't need to retrofit it to add the "phetio" to the directory name.

**Comment by samreid** [comment]
I wasn't sure whether to reassign this to @jonathanolson or @pixelzoom, so I went for both!

**Comment by pixelzoom** [comment]
I know nothing about phetio deployment paths, so self-unassigning.   When successfully deployed, this issue can be closed.

**Comment by zepumph** [comment]
>we don't need to retrofit it to add the "phetio" to the directory name.

We should most definitely verify this in the wrappers.

**Comment by samreid** [comment]
Good catch @zepumph I'm seeing this problem:

![image](https://user-images.githubusercontent.com/679486/42739786-0d291438-885b-11e8-9911-3cc921aebfd3.png)

You can see in the iframe it is referring to the "-phetio" path, so that would most likely resolve the problem.

@zepumph will renaming the directory be sufficient to solve this problem?

**Comment by pixelzoom** [comment]
I said:
> When successfully deployed, this issue can be closed.

Sorry, this issue should not be closed when the phet-io version is deployed.  It should remain open until the next deployment of the public version.

**Comment by zepumph** [comment]
I renamed the directory on phet-server and all works now,

https://phet-io.colorado.edu/sims/beers-law-lab/1.6.5-phetio/wrappers/index/

How should we document this, if at all?

**Comment by samreid** [comment]
What if we decide not to do maintenance on legacy versions of Beer's Law Lab PhET-iO any more, and instead focus on getting a new version out that uses chipper 2.0?

**Comment by pixelzoom** [comment]
@samreid said:
> What if we decide not to do maintenance on legacy versions of Beer's Law Lab PhET-iO any more, and instead focus on getting a new version out that uses chipper 2.0?

Yes.  I would really like to see us address the API redesign (https://github.com/phetsims/beers-law-lab/issues/230) and the open PhET-iO issues.    As the responsible developer, I don't like having this sim in "limbo" for this long.

**Comment by pixelzoom** [comment]
@samreid @zepumph Is the 1.6.5 redeploy complete? Has @kathy-phet been notified? 

If yes...  Then this issue should be relabeled with 'status:fixed-awaiting-deploy' until the next time we deploy the public version.

**Comment by samreid** [comment]
I'm not sure--I asked in https://github.com/phetsims/phet-io/issues/1329#issuecomment-405652723

**Comment by zepumph** [comment]
I updated the spreasheet for BLL to say the latest version is 1.6.5-phetio, and the sim is published and working. Since @jonathanolson unassigned himself yesterday, it seems like he thought there was nothing left for him to do. @jonathanolson please comment if you feel differently. Unassigning and marking "fixed-awaiting-deploy" for master.

**Comment by samreid** [comment]
@kathy-phet said:

> I've been seeing the github issue messages, but I am somewhat unclear as to if the update to beer's law is ready for me to send [...] Can you please clarify, and if so, send the links to the sim and to the instance proxies.

@zepumph said:

> I'm out today, would you mind taking care of this and adding to partners.md

**Comment by samreid** [comment]
I replied:

Kathy,

Beer's Law Lab was published to https://phet-io.colorado.edu/sims/beers-law-lab/1.6.5-phetio/wrappers/index/  This includes the Safari iOS touch bugfix as well as the "increments of 5" slider change as described in https://github.com/phetsims/beers-law-lab/issues/229

Best Regards,
Sam

**Comment by samreid** [comment]
I updated partners.md in the preceding commit.  Not sure what else remains for this issue.  @pixelzoom can you review the preceding comments and see what remains?

**Comment by pixelzoom** [comment]
Nothing else required for the PhET-iO redeploy.

Leaving this open and labeled "fixed-awaiting-deploy" to identify it as a change in the next public release.

**Comment by pixelzoom** [comment]
Ugh... https://github.com/phetsims/beers-law-lab/issues/126 broke this, and I'll need to reimplement it.  Starting over.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Back to "awaiting deploy".

**Comment by pixelzoom** [comment]
More on this in #275, so closing this issue.
