### ISSUE TITLE
Beers Law Lab - PhET-iO redesign

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#230]
There are several open issues labeled with dev:phet-io that have been open for quite awhile, with no progress.   Some have comments like "waiting until API redesign", e.g. https://github.com/phetsims/beers-law-lab/issues/223#issuecomment-356489916.   I'm responsible for this sim, and I don't like having things in a transient state for so long.  So... I think we should redesign the PhET-iO API for this sim "soon", and get these issues resolved.

Assigning to @ariel-phet to prioritize.

**Comment by pixelzoom** [comment]
To do this redesign, we'll need to know what features clients are currently using, so that we don't remove something that is being used.  @samreid @zepumph how do we determine this?

**Comment by samreid** [comment]
@kathy-phet is aware of how clients are leveraging some of the simulations, and it would be good for her to attend the design meetings.

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/issues/405 will need to be addressed for this too.

**Comment by pixelzoom** [comment]
From #230 - The concentration meter on the Concentration screen is the only readout that is currently instrumented. Decide whether to instrument other readouts similarly (AT detector, ...)

**Comment by pixelzoom** [comment]
- [ ] Decide how to form the tandem names for ComboBoxItemNode instances. This is currently a little awkward.  Not sure whether to add "ItemNode" suffix, or store complete string (e.g. "drinkMixItemNode") as a field in the associated model element.

**Comment by samreid** [comment]
Having fully formed tandem components such as `'drinkMixItemNode'` makes debugging and understanding a breeze.  In places where we have tried things like `element.tandemName+'ItemNode'`, it has been harder to understand and maintain.  Tagging @zepumph in case he has additional thoughts.

**Comment by pixelzoom** [comment]
Adding "block-sim-publication" label because this sim is still in a sub-standard state.

**Comment by pixelzoom** [comment]
1/14/2021 PhET-iO meeting:

Ideally @kathy-phet would like this work to be done in 2021.  I can proceed with cleaning things up and moving things forward at my discretion.

**Comment by pixelzoom** [comment]
Status for 1/4/2022 quarterly-planning meeting:

Status is unchanged from the previous quarterly-planning meeting. There are several issues that need to be fixed (estimate: 2-3 weeks), and PhET-iO re-design needs to be done.

**Comment by pixelzoom** [comment]
I've gone through the sim, and take my best-guess at redesign for modern PhET-iO standards. @arouinfar opened https://github.com/phetsims/beers-law-lab/issues/296 which seems like a duplicate of this issue.  So I'll close this issue, and we can review in https://github.com/phetsims/beers-law-lab/issues/296.
