### ISSUE TITLE
Probes have incorrect pointer areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#239]
This was factored out of https://github.com/phetsims/beers-law-lab/issues/236.

This sim suffers from the issue described in https://github.com/phetsims/scenery-phet/issues/488.  Blocked until that issue is addressed.

**Comment by pixelzoom** [comment]
Closing this. It's covered by phetsims/scenery-phet#488, and is a general problem that occurs in all sims that have a probe.

**Comment by pixelzoom** [comment]
The general issue was moved to https://github.com/phetsims/kite/issues/77, and is still not addressed.  Reopening this issue so that QA doesn't re-report.

**Comment by pixelzoom** [comment]
Self assigning.  @samreid has a fix in https://github.com/phetsims/kite/issues/77. I'm going to wait until @jonathanolson has reviewed and closed https://github.com/phetsims/kite/issues/77 before I close this issue.

**Comment by samreid** [comment]
https://github.com/phetsims/kite/issues/77 has been reviewed and closed.
