### ISSUE TITLE
branch: dynamic-layout

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#243]
For https://github.com/phetsims/joist/issues/608

**Comment by pixelzoom** [comment]
phetsims/joist#608 is closed. And dynamic layout has been in use for awhile, via LayoutBox option `excludeInvisibleChildrenFromBounds`. 

@samreid can this branch be deleted?

**Comment by samreid** [comment]
Yes, I'll delete it now then close this issue.

**Comment by samreid** [comment]
Branch deleted, closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
