### ISSUE TITLE
Reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#249]
For ES6 testing. On master phet-io and phet brand.
If you add solute your mix, evaporate all the liquid, the try to add back water you are unable to and get this console error. You can then freeze the whole sim by, for instance, clicking remove solute.
![reentrydetected](https://user-images.githubusercontent.com/41024075/76131854-66737b00-5fcd-11ea-8a3b-621ac3508b7d.gif)

**Comment by pixelzoom** [comment]
Steps to reproduce what @KatieWoe has shown above:

1. Run the sim with `?brand=phet&ea`.
2. Go to Concentration screen.
3. Shake some solute into the beaker.
4. Evaporate all solution from the beaker, leaving solute particles in the empty beaker.
5. Attempt to add water (via faucet) or solute (via dropper) to the beaker.

... then the Error shown in the gif above occurs.

Another way to cause the same Error:

1. Run the sim with `?brand=phet&ea`.
2. Go to Concentration screen.
3. Empty the beaker using the drain faucet.
4. Shake some solute into the empty beaker.
5. Attempt to add water (via faucet) or solute (via dropper) to the beaker.

**Comment by pixelzoom** [comment]
Unassigning, no plans to work on beers-law-lab.

**Comment by pixelzoom** [comment]
I can no longer reproduce this. I suspect that it was occurring after one of the other assertion failures that I fixed recently.  Closing.
