### ISSUE TITLE
Evaporation slider can't be permanently disabled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#250]
For ES6 Testing
When you use studio to disable the evaporation slider, adding or removing water/solution re-enables it.
![comesback](https://user-images.githubusercontent.com/41024075/76240607-255fae80-61f9-11ea-83dd-69d3d6a47fe4.gif)

**Comment by pixelzoom** [comment]
My recommendation is to make `model.evaporator.enabledProperty` read only.  And if the Evaporation slider is irrelevant, then the client should set `view.evaporationControl.visibleProperty` to `false`.

**Comment by pixelzoom** [comment]
While testing, I noticed that allowing the client to change `model.evaporator.evaporationRateProperty` is also problematic, and results in a hard failure. 

So `model.evaporator.enabledProperty` and `model.evaporator.evaporationRateProperty` are now `phetioReadOnly: true` in the above commit.   

Labeling this as "ready for review", but unassigned until we get to PhET-iO redesign in #230.

**Comment by pixelzoom** [comment]
We're back to working on this sim, so time to review this issue.

**Comment by arouinfar** [comment]
> My recommendation is to make `model.evaporator.enabledProperty` read only.  And if the Evaporation slider is irrelevant, then the client should set `view.evaporationControl.visibleProperty` to `false`.

That would have been my recommendation too.

> While testing, I noticed that allowing the client to change `model.evaporator.evaporationRateProperty` is also problematic, and results in a hard failure. 
>
>So `model.evaporator.enabledProperty` and `model.evaporator.evaporationRateProperty` are now `phetioReadOnly: true` in the above commit.   

Good catch. Everything looks good in master. Thanks @pixelzoom!
