### ISSUE TITLE
why was 'on' changed to 'lazyLink'? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#254]
In phetsims/beers-law-lab@a50707b for https://github.com/phetsims/scenery/issues/490, @jonathanolson made this change in ConcentrationMeterNode.js:

```diff
-     solutionNode.on( 'bounds', updateValue );
-     stockSolutionNode.on( 'bounds', updateValue );
-     solventFluidNode.on( 'bounds', updateValue );
-     drainFluidNode.on( 'bounds', updateValue );
+     solutionNode.boundsProperty.lazyLink( updateValue );
+     stockSolutionNode.boundsProperty.lazyLink( updateValue );
+     solventFluidNode.boundsProperty.lazyLink( updateValue );
+     drainFluidNode.boundsProperty.lazyLink( updateValue );
```

And in https://github.com/phetsims/scenery/issues/490#issuecomment-635691167, @zepumph asked why `on` was changed to `lazyLink` instead of `link`.   I'm interested in the answer.

**Comment by jonathanolson** [comment]
It's because I was going for compatibility, and since `.on()` only added the listener without calling it, lazyLink is the appropriate thing to change it to.

**Comment by pixelzoom** [comment]
Great, thanks for clarifying. Closing.
