### ISSUE TITLE
User request: mass of solute added

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/beers-law-lab#256]
> I have a suggestion for the concentration simulation that would be very useful in my class and that I hope would not be too much bother. It would be great if students could know the mass of the substance added. Either have a label to the side that shows how much was shaken in to give the concentration shown, or even give the ability to set a mass and see the resultant concentration.

**Comment by arouinfar** [comment]
@oliver-phet please direct the user to the Teacher Tips. The [?showSoluteAmount](https://phet.colorado.edu/sims/html/concentration/latest/concentration_en.html?showSoluteAmount) will display the amount of solute added in grams.

**Comment by oliver-phet** [comment]
Replied to user. Closing!
