### ISSUE TITLE
revisions for new IO Type pattern

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#259]
Related to the new IO Type pattern conversion that's being done in https://github.com/phetsims/tandem/issues/211...

BeersLawSolutionIO should be moved into BeersLawSolution.  That will remove the circular reference, and then the static instances defined in BeersLawSolutionInstances can be defined in BeersLawSolution.

Ditto for SoluteIO, Solute, and SoluteInstances. (And similar to https://github.com/phetsims/ph-scale/issues/205.)

@samreid FYI.

**Comment by samreid** [comment]
So you're aware, in https://github.com/phetsims/tandem/issues/211#issuecomment-695075392 I commented that 

> This work is basically stable, and I'll put further work on hold until I can coordinate with @zepumph more. There is more "busywork" that could be done, but I want to make sure we are in agreement about the desired end product before I spend more time on it.

I don't think changes like https://github.com/phetsims/ph-scale/issues/205 or even this issue are problematic.  But I wanted to make sure you are aware that this has not been reviewed by @zepumph or put through QA testing, and there may be more revisions to the strategy before it is complete.

**Comment by pixelzoom** [comment]
Got it, I did see your comment.  But it didn't say anything about cleaning up static instances (which I don't regard as "busywork").  I don't plan to do this work right away, but created this issues as a reminder.

**Comment by pixelzoom** [comment]
@samreid are the revisions to IO Type completed? And if so, can I proceed with cleanup here?

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/issues/217 was closed, so I think you are all good to go here.

**Comment by pixelzoom** [comment]
In the above commit, BeersLawSolutionInstances was moved into BeersLawSolution, and SoluteInstances was moved into Solute.  This resulted in no PhET-iO API changes, and there are no circular references when building.  

Closing.
