### ISSUE TITLE
Support PhET-iO version for data recording

### ISSUE THREAD

**Issue by zepumph** [phetsims/beers-law-lab#261]
@kathy-phet mentioned a PhET-iO study coming up for BLL, I said that the Metacog client version in our current BLL published version is out of date, and needs updating. 

@zepumph to publish at least an MR updating to 3.5 (using https://github.com/phetsims/phet-io/issues/1262).

@kathy-phet will reach out to the researcher before I implement.

**Comment by pixelzoom** [comment]
I'm triaging issues for this sim, bringing it up to current PhET-iO standards.

@zepumph @kathy-phet What is the status of this issue? Can it be closed, or is there still a researcher that needs to be supported?

**Comment by kathy-phet** [comment]
Yes, let's close this issue.
