### ISSUE TITLE
Support hiding cuvette arrow

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/beers-law-lab#263]
In an old issue (https://github.com/phetsims/phet-io/issues/1220), client comment
They want to remove the beersLawLab.beersLawScreen.view.cuvetteNode.arrowNode so that you can't adjust the width of the cuvette. Problem was communicated as they tried to "disable" it, there was something in the "engineering of it that when trying to disable that one piece, it started to freeze everything in the sim."
Could not get values of absorbance as a function of concentration for making the table

When moving to PhET-iO Studio and doing PhET-iO tree structure review, look at these specifically.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet please review. Confirm that cuvette arrow can be hidden via `beersLawLab.beersLawScreen.view.cuvetteNode.arrowNode.visibleProperty`, and that the sim continues to function.

**Comment by arouinfar** [comment]
Looks good in master, closing.
