### ISSUE TITLE
Revisit IOTypes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#265]
Related to #262.  Revisit the IO Types in this sim. Are they necessary? Are they correct?

- [x] BeersLawSolutionIO
- [x] ~~ConcentrationModelIO~~
- [x] PrecipitateParticleIO
- [x] ~~ShakerIO~~
- [x] ShakerParticleIO
- [x] SoluteIO
- [x] ~~SoluteParticleIO~~

**Comment by pixelzoom** [comment]
ShakerIO is currently not used. In Shaker.js:

```
// phetioType: ShakerIO
```

Why is this commented out?

**Comment by pixelzoom** [comment]
Looking at the list in https://github.com/phetsims/beers-law-lab/issues/265#issue-825096922 ...

ConcentrationModelIO and ShakerIO no longer exist.

BeersLawSolutionIO and SoluteIO required no changes; they are simple "reference type serialization".

SoluteParticleIO, ShakerParticleIO, and PrecipitateParticleIO were a bit more work.  Solute is the base class for  ShakerParticle and PrecipitateParticle.  But I couldn't figure out how to implement a parallel IOType hierachy.  So I deleted SoluteParticleIO and made ShakerParticleIO and PrecipitateParticleIO responsible for their entire implementations, with no supertype IOType.  I don't think this is a very good pattern in general, so I'd like to schedule some time with @samreid or @zepumph to understand the pattern for implementing a parallel IOType hierachy.

**Comment by zepumph** [comment]
Agreed! Next step is to tackle this with a pairing session to review best practices for there IOTypes.

**Comment by zepumph** [comment]
>This is not blocking, the sim could publish as is, and it (probably) won't result in a future API change. But I'd like to understand what pattern I should be using.

Good to reiterate! thanks

**Comment by zepumph** [comment]
I think it would be good to hold off on this until next year. I would like to prioritize our current sims in QA at this time.

**Comment by pixelzoom** [comment]
Fine with me. See you in 2023.

**Comment by pixelzoom** [comment]
In the above commit, I took a first stab at an IOType hierarchy for SoluteParticleIO et. al.  Losts of questions, as indicated by TODO comments.

**Comment by pixelzoom** [comment]
@samreid and I spent some time on the IOType "hierarchy".  We identified quite a few general problems, but no solutions. @samreid suggested that I collapse the core-type hierarchy, so that there's only SoluteParticle.  That seems reasonable fro beers-law-lab, so I'm going to do that.  But it doesn't address the general problems with IOTypes, and collapsing the core-type hierarchy will not be possible in (for example) natural-selection and equality-explorer.

**Comment by pixelzoom** [comment]
Summary of above commits:
* collapsed the SoluteParticle class hierachy
* collapsed the SoluteParticleIO IOType "hierarchy"
* encapsulated PhetioGroup in SoluteParticles, so that it is hidden from the rest of the sim

The general structure of the Studio tree is unchanged. There are still separate groups for shaker vs precipitate particles:

* beersLawLab.concentrationScreen.model.shakerParticles.particleGroup
* beersLawLab.concentrationScreen.model.precipitateParticles.particleGroup

One difference is that all particles now have velocity and acceleration fields, where those fields used to be present only for shaker particles. For precipitate particles, velocity and acceleration are always zero.

**Comment by pixelzoom** [comment]
All IOTypes have been revisited, and this feels like it's in a good state. So closing.
