### ISSUE TITLE
Instrumentation of concentration NumberControls

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#270]
Related to https://github.com/phetsims/beers-law-lab/issues/262 (upgrade PhET-iO implementation), in the _Beer's Law_ screen:

> - [ ] How should the NumberControls for solution concentration be instrumented? Each solution currently has its own NumberControl.

Here's what the Studio tree looks like:

<img width="1108" alt="screenshot_903" src="https://user-images.githubusercontent.com/3046552/110553440-338b2800-80f6-11eb-8272-8a59ab7f0900.png">

There is a control for each solution because each solution has its own concentration range, units, and color coding. And these things are not mutable in NumberControl. 

This makes it difficult to do any customization of these NumberControls. For example, something simple like changing the "Concentration" text requires that to be done 8 times, in for each control separately. 

What (if anything) needs to be done here?

**Comment by pixelzoom** [comment]
Here's what I came up with:

<img width="292" alt="screenshot_2000" src="https://user-images.githubusercontent.com/3046552/205413132-53fc9978-fd50-491d-b619-c108d1da458d.png">

The fact that `concentrationControl` is actually 8 NumberControl instances (1 for each solution) is hidden here. All you can do is make the entire control visible/invisible via `concentrationControl.visibleProperty`, or inspect the value that it is displaying via `concentrationControl.concentrationProperty`.   And adding additional features really feels like over-engineering to me. 

@arouinfar please review.

**Comment by pixelzoom** [comment]
> The downside is that we lose some of the customizability of the typical NumberControl, such as hiding the slider and letting the NumberDisplay serve as a readout.  ...
A workaround might be adding an enabledProperty but I don't know if that can be supported with this approach. Could that work @pixelzoom?

enabledProperty is not what we'd typically use to hide a slider. And we'd need to hide the arrow buttons too.  It sounds like what you really want is a custom `displayOnlyProperty` that hides the slider and arrow buttons for all 8 NumberControls.  I'm kind of hesitant to do that until someone actually ask for it.

So... Let me put a little more effort into seeing if I can collapse the 8 NumberControls into 1 NumberControl.

**Comment by arouinfar** [comment]
> enabledProperty is not what we'd typically use to hide a slider. 

True, but it has a similar effect. The value remains visible, but users aren't able to change it. It's definitely a bandaid, so I appreciate you looking into things a bit more.

**Comment by pixelzoom** [comment]
Using a single NumberControl proved to be impossible.  Each solution has its own units, range, and color.  A dynamic range in particular is not supported by NumberControl, and adding that feature would be a big common-code project.  So I stuck with the existing implementation, where we have 8 NumberControls, each associated with 1 solute.

To address your concern about being able to hide the slider and arrow buttons, I added `displayOnlyProperty`, whose metadata looks like this in Studio:

<img width="761" alt="screenshot_2060" src="https://user-images.githubusercontent.com/3046552/207161758-320b1706-89ed-4554-96c5-a4cc6e7544ad.png">

I'll be happy to change the name if you'd like. I also considered `readonlyProperty` and `isEditableProperty`.  But `displayOnlyProperty` currently exists in ComboBox, and has been requested for NumberControl (see https://github.com/phetsims/sun/issues/714 for NumberControl) and UI components in general (see https://github.com/phetsims/phet-io/issues/1757).  So `displayOnlyProperty` seemes the most future-proof.

Here's the full Studio tree for `concentrationControl`:

<img width="657" alt="screenshot_2059" src="https://user-images.githubusercontent.com/3046552/207161843-8ab7c4cd-397a-41f0-ae6b-64dea790b55c.png">

Back to @arouinfar for review. Feel free to close if there are no other requests.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I agree, `displayOnlyProperty` seems the most future-proof. Thanks for adding it to the `concentrationControl`. Everything looks good in master, closing.
