### ISSUE TITLE
Could not get values of absorbance as a function of concentration for making the table

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#271]
In https://github.com/phetsims/beers-law-lab/issues/263, there was one line that sounded like a second unrelated problem:

> Could not get values of absorbance as a function of concentration for making the table

This is not enough info for me to guess what the client is trying to do, and how they are going about trying to do it.  Do you have more info? 

@kathy-phet please advise on how to proceed

**Comment by pixelzoom** [comment]
Based on phetsims/phet-io#1220 (comment), it looks like the client was using 1.5.5-phetio.

**Comment by pixelzoom** [comment]
@kathy-phet checking with you again - can this issue be closed?

**Comment by pixelzoom** [comment]
Asked @kathy-phet again via DM on Slack.

**Comment by kathy-phet** [comment]
@pixelzoom -  Sorry for the delay. Hong Kong has been busy. I believe the user who reported this issue was in fact @JacquiHayes! 

We will want both absorbance and concentration values to be available through the API. Right now, when I look at the implementation, the API allows you to get the "detector" value. But only one value is available and you have to know what the detector is displaying to know what you are getting. 

@pixelzoom - Changes should probably wait until @arouinfar and I do a PhET-iO design review, but here are a few thoughts. 

1) I'm thinking would would want 2 derived properties. One for Absorbance and one for Transmission. The detector would decide which to display, but the model would have both instrumented, so you can grab whichever you want at any time if you want a specific one. And perhaps keep the displayed value, as well. 

2) With concentration, it seems fine for now to have the concentration always available in mol/L, which is what I am seeing. But I will want to discuss with @arouinfar and @JacquiHayes in design review.

**Comment by pixelzoom** [comment]
> 1. I'm thinking would would want 2 derived properties. One for Absorbance and one for Transmission. The detector would decide which to display, but the model would have both instrumented, so you can grab whichever you want at any time if you want a specific one. And perhaps keep the displayed value, as well.

This is going to require some significant changes to the model  - specifically AbsorbanceModel.ts, ATDetector.ts.

> 2. With concentration, it seems fine for now to have the concentration always available in mol/L, which is what I am seeing. But I will want to discuss with @arouinfar and @JacquiHayes in design review.

Since this is going to be a significant change, this is not appropriate to defer until design review.  Please discuss what you want now, so that I can implement.  Then you can review what I've implemented in design review.

**Comment by pixelzoom** [comment]
I'm still not clear on what "making the table" in the title of this issue means.  @JacquiHayes can you please clarify? What table? Can you provide a concrete example?

**Comment by kathy-phet** [comment]
Hooking up PhET-iO API so student can collect data to make this kind of table/graph. 
![image](https://user-images.githubusercontent.com/5096804/207203773-7ec1debc-da48-4128-866d-517788ceef5d.png)

**Comment by JacquiHayes** [comment]
It's been along time since we submitted that feedback! But I agree with what Kathy has said above, both with the table as an example and also that there are many use cases for being able to get a value for absorbance and for transmission.

**Comment by kathy-phet** [comment]
> >I'm thinking would would want 2 derived properties. One for Absorbance and one for Transmission. The detector would decide which to display, but the model would have both instrumented, so you can grab whichever you want at any time if you want a specific one. And perhaps keep the displayed value, as well.

>There are currently no Properties for aborbance and transmittance because they are computed on demand, as they were in the Java version. Doing this correctly will require some significant changes to the model - specifically AbsorbanceModel.ts and ATDetector.ts. There's also the option of hacking together some PhET-iO-only Properties. But I really dislike that approach because PhET still has no process for testing all PhET-iO-only features.

@pixelzoom - I do think we will want to have this data, but it should still be generated "on demand". Just each property separately, on demand, for the specific configuration at the moment (beaker width, concentration, solute, wavelength). I am NOT proposing some sort of data table of all values. So what I see would need to be done would be a new derivedProperty for each of these values that is instrumented, and then the readout radio button is deciding which value to display in the view.

**Comment by pixelzoom** [comment]
Regarding the table/graph in https://github.com/phetsims/beers-law-lab/issues/271#issuecomment-1347617798 ...  

I'm not sure what you're trying to accomplish with this table/graph, or the context.  But if it's meant to imply that absorbance is a function of concentration, that is incorrect.  Absorbance is a function of concentration, path length (cuvette width), and wavelength (of the light). And wavelength determines the molar absorption coefficient. 

Specifically:

`A = a * b* C`, where `a` is the molar absorption coefficient, `b` is is path length, and `c` is concentration.

**Comment by pixelzoom** [comment]
@arouinfar and I worked on this today.  I'll summarize the changes...

Here's the relevant part of the model in the Studio tree.  The important elements are `detector` and `solutionInCuvette`.

<img width="261" alt="screenshot_2063" src="https://user-images.githubusercontent.com/3046552/207736005-851a93a5-119f-460a-b72a-264d54be7500.png">

Where to inspect Properties related to absorbance depends on whether we're interested only in the solution in the cuvette, or whether we're interested in the AT detector in relation to the cuvette and light.   If you're interested in the former, look in `beersLawScreen.model.solutionInCuvette`.  If you're interested in the latter, look in `beersLawScreen.model.detector.

Note that `beersLawScreen.model.detector` no longer has `valueProperty`, which was the value displayed by the detector.  That has been moved to the view (where it typically is in PhET sims), as we'll see below.

Specifically for creating the table/graph in https://github.com/phetsims/beers-law-lab/issues/271#issuecomment-1347617798, you would look at these elements:
* `solutionInCuvette.concentrationProperty`
* `solutionInCuvette.absorbanceProperty`

But as mentioned in https://github.com/phetsims/beers-law-lab/issues/271#issuecomment-1352365384, that table/graph doesn't tell the whole story.  A complete derivation of absorbance also needs to include `pathLengthProperty`, `wavelengthProperty`, and `molarAbsorptivityProperty`, all of which can be found in the Studio tree.

Here's the relevant part of the model in the Studio tree:

<img width="247" alt="screenshot_2065" src="https://user-images.githubusercontent.com/3046552/207736708-06df5f28-013d-4a2d-9568-14b64b2f755b.png">

If someone is interested in knowing exactly what the student is seeing on the detector, they should look at `detectorNode.bodyNode.valueText.stringProperty`.

Over to @arouinfar for review. @kathy-phet @JacquiHayes FYI.

**Comment by kathy-phet** [comment]
Yes, It’s just one dependence. Students would investigate each to determine the whole relationship. I was just illustrating what one set of evidence would be for that one dependence. Sent from my iPhoneOn Dec 14, 2022, at 4:41 PM, Chris Malley ***@***.***> wrote:﻿
Regarding the table/graph in #271 (comment) ...
I'm not sure what you're trying to accomplish with this table/graph, or the context.  But if it's meant to imply that absorbance is a function of concentration, that is incorrect.  Absorbance is a function of concentration, path length (cuvette width), and wavelength (of the light). And wavelength determines the molar absorption coefficient.
Specifically:
A = a * b* C, where a is the molar absorption coefficient, b is is path length, and c is concentration.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! This all looks good in master, closing.
