### ISSUE TITLE
Snap Concentration slider to 5 units

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#275]
Make the Concentration slider in the Beer's Law screen snap to 5 units while dragging.  No Studio slider for the associated Property.

**Comment by pixelzoom** [comment]
Snapping was already implemented for the Concentration sliders.  In ConcentrationControl.js:

```js
const SLIDER_INTERVAL = 5; // in view units
```
Note that the snap intervals is "in view units". The model uses 'mol/L' throughout, but concentration is displayed in units that are specific to each solution.  So if a solution's concentration is displayed in mM, then the snap interval is 5 mM.  If  concentration is displayed in µM, then the snap interval is 5 µM.

Next, I removed the Studio slider for `concentrationProperty`. In BeersLawSolution.js, the class for all solutions in the _Beer's Law_ screen, I added `phetStudioControl: false`:

```js
    this.concentrationProperty = new NumberProperty( config.concentrationRange.defaultValue, {
      units: 'mol/L',
      range: config.concentrationRange,
      tandem: config.tandem.createTandem( 'concentrationProperty' ),
      phetioStudioControl: false // see https://github.com/phetsims/beers-law-lab/issues/275
    } );
```

For the reviewer...  There is a `concentrationProperty` for each solution, and the solutions can be found under `beersLawLab.beersLawScreen.model.solutions`.  Or you can just search for `concentrationProperty`.

@arouinfar please review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom looks great in master.
