### ISSUE TITLE
Implement particles using Sprites

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#276]
To address the performance issues reported in #209, investigate using Sprites to draw shaker particles and precipitate particles.  They are currently implemented as a subclass of CanvasNode.  See base class ParticlesNode.ts.

ShakerParticlesNode.ts:

<img width="254" alt="screenshot_2054" src="https://user-images.githubusercontent.com/3046552/206940146-18f789dd-1b93-4d9b-bf1c-1c0e4fdd7643.png">

PrecipitateNode.ts:

<img width="608" alt="screenshot_2051" src="https://user-images.githubusercontent.com/3046552/206940067-6937a463-114a-4149-a61c-fd1827647800.png">

**Comment by pixelzoom** [comment]
I took a look at this.  It's going to be a significant chunk of work, and the implementation is going to be much more complicated (ParticlesNode extends CanvasNode is currently very simple).  So over in #209 I'm going to try to improve the performance by reducing the number of things that are computed/allocated in ParticlesNode `paintCanvas`.

**Comment by pixelzoom** [comment]
Questions for @jonathanolson via Slack DM:

I’m investigating re-implementing the particle systems in Beer’s Law Lab using Sprites (they are currently CanvasNode).  Each particle is a square, with random rotation.  What’s the best way to create an ImageableImage for use with SpriteImage? I’ve considered `new Rectangle().rasterize(..)`, but that returns Node, not Image.   It sure would be convenient if any Node could be used with SpriteImage, or if there was a utility for converting any Node to what’s needed by SpriteImage.

Here’s what I came up with. It seems to work if I add it to demoSprites.js.  But in TypeScript, it involves a cast that feels unsafe. Is there a better way?

```typescript
    const particleRectangle = new Rectangle( 0, 0, 50, 50, {
      fill: 'red',
      stroke: 'black'
    } );
    const particleCanvasElement = ( particleRectangle.rasterized( { wrap: false } ) as Image ).image;
    const particleSpriteImage = new SpriteImage( particleCanvasElement, new Vector2( particleRectangle.width / 2, particleRectangle.height / 2 ) );
```

**Comment by jonathanolson** [comment]
Node has `toCanvas()` which is a bit older and clunky, but can rasterize the Node to a Canvas for use in images. The main thing `rasterized()` provides is the resolution scaling. If you don't need that, you could just directly use `toCanvas()` (it is synchronous but has an asynchronous api currently).

**Comment by pixelzoom** [comment]
As reported in https://github.com/phetsims/beers-law-lab/issues/209, there is no longer any evidence of a performance issue with the current CanvasNode implementation.   So I see no reason to convert to Sprites, and I'm closing this issue.
