### ISSUE TITLE
Do individual particles need to be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#279]
From https://github.com/phetsims/beers-law-lab/issues/262#issuecomment-793265872:

> - [ ] Does `model.shakerParticles` need to be instrumented, with a PhetioGroup for each particle?
> - [ ] Does `model.precipitate` need to be instrumented, with a PhetioGroup for each particle?

**Comment by pixelzoom** [comment]
3/11/21 design meeting @arouinfar @kathy-phet @pixelzoom 

Re:
> - [ ]  Does `model.shakerParticles` need to be instrumented, with a PhetioGroup for each particle?

Yes, they likely do.  Each particle is dispensed individually at random, and contributes to the solution after it has animated past the surface of the solution and dissolved in solution.  Due to this randomness, it's important to record and playback each shaker particle. 

Re:
> -[ ] Does `model.precipitate` need to be instrumented, with a PhetioGroup for each particle?

There is probably no reason to instrument the precipitate particles. They are a qualitative indicator of the level of saturation. In the State Wrapper, it doesn't matter if they are in the exact positions in the downstream sim.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/beers-law-lab/issues/279#issuecomment-799749092 indicates that the precipitate particles do not need to be individually instrumented.  But I'm inclined to instrument them because:

(1) They are instrumented in the current implementation.
(2) Uninstrumenting them will require an entirely new implementation.
(3) There are at most < 1400 particles, and they are not moving.
(4) If rendering the particles is the performance problem, that will be addressed by using Sprites in #276 
(5) If serialization is the problem, that will need to be addressed for Gas Properties, where each individual particle _must_ be instrumented.

**Comment by pixelzoom** [comment]
@arouinfar For the reasons listed in https://github.com/phetsims/beers-law-lab/issues/279#issuecomment-1338153230, I'm planning to make no changes here, and keep all particles instrumented.  Is that OK with you?  If so, you can close this issue.

**Comment by arouinfar** [comment]
@pixelzoom leaving the particles instrumented sounds reasonable. They look fine in the tree, but I also don't plan to feature them. Performance has been fine, even on my phone.
