### ISSUE TITLE
Add Solute link to nameProperty 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#292]
In https://github.com/phetsims/ph-scale/issues/246, we decided to link `nameProperty` for Solutes to their associated translated StringProperty.   I assume we'll want to do the same thing for Solutes in beers-law-lab.

@arouinfar does that sound correct?

Note that https://github.com/phetsims/axon/issues/414 is a prerequisite for this.

**Comment by arouinfar** [comment]
> @arouinfar does that sound correct?

Yes, that's correct @pixelzoom

**Comment by pixelzoom** [comment]
Done in the above commits.  @arouinfar ready for review, close if OK.

Solute now has a linked `nameProperty`:

<img width="262" alt="screenshot_1888" src="https://user-images.githubusercontent.com/3046552/192377047-77b425c4-6f14-4012-af0b-4a0b1e32a3e2.png">

It seemed like this enhancement should also be made for the solutions that appear in the _Beer's Law_ screen, so I went ahead and did that too. These solutions also have a `formulaProperty`, which links to the corresponding solute formulaProperty.

<img width="264" alt="screenshot_1890" src="https://user-images.githubusercontent.com/3046552/192377188-5b1bc346-361f-4d91-b96f-395852843ec7.png">

**Comment by arouinfar** [comment]
> It seemed like this enhancement should also be made for the solutions that appear in the _Beer's Law_ screen, so I went ahead and did that too. These solutions also have a `formulaProperty`, which links to the corresponding solute formulaProperty.

Good call @pixelzoom, thanks!

>  @arouinfar ready for review, close if OK.

Everything looks good in master, closing.
