### ISSUE TITLE
Generate PhET-iO API file, add `phetioDesigned: true`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#294]
This sim currently has no API file, so we'll need to run `grunt generate-phet-io-api` at an appropriate point.  I'm going to defer this as long as possible, so I don't need to keep regenerating it as I make changes.

Also add `phetioDesigned: true` to SimOptions.

This can be done when https://github.com/phetsims/beers-law-lab/issues/296 has been completed.

It should be done for both beers-law-lab and concentration repos.

**Comment by arouinfar** [comment]
The only issue remaining from #296 is #310.

**Comment by pixelzoom** [comment]
In the above commits, I generated the API files and added `phetioDesigned: true` at the top-level of the sim.  Tested in Studio with `phetioValidation=true`.

Closing.
