### ISSUE TITLE
PhET-iO Design Review

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#296]
Related to #230 

The most recent PhET-iO version of this simulation predates Studio and modern design practices. The tree should be thoroughly reviewed, so self-assigning.

**Comment by pixelzoom** [comment]
@arouinfar is this a duplicate of https://github.com/phetsims/beers-law-lab/issues/230? How is it different?

**Comment by pixelzoom** [comment]
I've gone through the sim, and taken my "best guess" at revising the instrumentation for modern PhET-iO standards.  @arouinfar this is ready for review.

**Comment by arouinfar** [comment]
Design review is complete. All relevant issues are tagged above, closing.
