### ISSUE TITLE
Add PhET-iO instrumentation for "Concentration:" label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#297]
Add PhET-iO instrumentation for "Concentration:" label, after #270 is addressed.

Instrumentation should probably be similar to the "Evaporation:" label in EvaporationPanel.ts:

```typescript
    const stringProperty = new DerivedProperty(
      [ BeersLawLabStrings.pattern[ '0labelStringProperty' ], BeersLawLabStrings.evaporationStringProperty ],
      ( pattern: string, evaporationString: string ) => StringUtils.format( pattern, evaporationString ), {
        tandem: labelTextTandem.createTandem( Text.STRING_PROPERTY_TANDEM_NAME ),
        phetioValueType: StringIO
      }
    );
```

**Comment by pixelzoom** [comment]
The  "Concentration:" string Property was instrumented in the above commit.  It's a little different than the other "Label:" string Properties because it's shared with 8 NumberControls (see https://github.com/phetsims/beers-law-lab/issues/270).  It's tandem name is "concentrationStringProperty" instead of simply "stringProperty".  And it looks like this in the Studio tree:

<img width="675" alt="screenshot_2057" src="https://user-images.githubusercontent.com/3046552/207159594-2b56b540-3f04-498a-8f3d-cc5c565a82cf.png">

@arouinfar please review. You'll probably want to review https://github.com/phetsims/beers-law-lab/issues/270 at the same time.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.
