### ISSUE TITLE
Add units to numeric Properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#298]
Some of the numeric Properties are missing units.  Add the `units:` option to their constructor.

**Comment by pixelzoom** [comment]
@arouinfar What are the desired units for these quantities?

* molar absorptivity 
* absorbance

**Comment by arouinfar** [comment]
Molar absorptivity, or the [molar absorption coefficient](https://en.wikipedia.org/wiki/Molar_absorption_coefficient), has SI units of m<sup>2</sup>/mol, but in practice, quantities are usually expressed in terms of M<sup>−1</sup>⋅cm<sup>−1</sup>. Looks like the model already uses cm for distances (cuvette width) and mol/L (M) for concentration, so let's use M<sup>−1</sup>⋅cm<sup>−1</sup> or the equivalent L⋅mol<sup>−1</sup>⋅cm<sup>−1</sup>. I have no preferences between M and mol/L, so I'll leave it your preference @pixelzoom.

The [absorbance of a material](https://en.wikipedia.org/wiki/Absorbance#Absorbance_of_a_material) is unitless. 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/8419308/207396825-b6f6358b-9d2c-40e8-b9f8-7cf8c7cb9461.png">

**Comment by pixelzoom** [comment]
Discussed molar absorptivity, and model.md says:

> Molar absorptivity (a) is in units of 1/(cm*M), and varies with solution and wavelength. 

So we used '1/(cm*M)'.

Closing.
