### ISSUE TITLE
Beer's Law Lab - Publish 1.7.0 with PhET-iO upgrades

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#300]
@arouinfar @kathy-phet FYI.

This also includes Concentration.  Note that Concentration version number should be brought forward to 1.7.

**Comment by pixelzoom** [comment]
Unassigning, because it looks like it will be awhile before we're ready to begin the release process.

**Comment by pixelzoom** [comment]
@zepumph and team phettuccine. This is the kind of comment I'm anticipating will be added to this issue when a test is added to the QA Pipeline.

---

1/30/2023 1.7.0-dev.8 (full) testing begins, `brands=phet,phet-io`.

beers-law-lab:
* https://github.com/phetsims/qa/issues/889
* https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8

concentration:
* https://github.com/phetsims/qa/issues/891
* https://phet-dev.colorado.edu/html/concentration/1.6.0-dev.2

**Comment by samreid** [comment]
2/3/2022: We are ready to create the RC.  brands=phet,phet-io.  @matthew-blackman and I will do so for this sim and concentration.  We will makes sure they have the same major.minor version.

**Comment by samreid** [comment]
Deployed: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.1/phet/beers-law-lab_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.1/phet-io/
Please wait for the build-server to complete the deployment, and then test!

I'll do concentration next.

**Comment by matthew-blackman** [comment]
2/3/2023 1.7.0-rc.1 testing begins, brands=phet,phet-io.

beers-law-lab:

https://github.com/phetsims/qa/issues/894
https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.1

concentration:

https://github.com/phetsims/qa/issues/895
https://phet-dev.colorado.edu/html/concentration/1.7.0-rc.1

**Comment by pixelzoom** [comment]
2/6/2023  Due to problems with the 1.7 shas (see https://github.com/phetsims/beers-law-lab/issues/327), testing of 1.7.0-rc.1 was paused.  1.7.0-rc.2 was published, and the QA issues for 1.7.0-rc.1 were (unfortunately) renamed to 1.7.0-rc.2.

beers-law-lab:
* https://github.com/phetsims/qa/issues/894
* https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.2

concentration:
* https://github.com/phetsims/qa/issues/895
* https://phet-dev.colorado.edu/html/concentration/1.7.0-rc.2

**Comment by pixelzoom** [comment]
1.7.0-rc.2 testing was completed 2/15/2023.  An additional RC spot-check will be needed.

**Comment by pixelzoom** [comment]
2/17/20223 1.7.0-rc.2 (spot-check) testing begins, `brands=phet,phet-io`.

beers-law-lab:
* https://github.com/phetsims/qa/issues/901
* https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.3

concentration:
* https://github.com/phetsims/qa/issues/902
* https://phet-dev.colorado.edu/html/concentration/1.7.0-rc.3

**Comment by pixelzoom** [comment]
2/17/2023 1.7.0-rc.3 testing completed. All issues vertified, and no new issues were found. I'll proceed with publishing.

**Comment by pixelzoom** [comment]
2/17/2023: 1.7.0 was published.
