### ISSUE TITLE
Migration support for 1.7 release?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#301]
Related to _Beer's Law Lab_ and __Concentration_ for #300... 

There are presumably clients using some PhET-iO version of these sims.  But these sims have no PhET-iO API files.  I’m guessing that their publication predates API files, and that there’s never been a release since we started generating API files.  

But that makes migration problematic, or maybe impossible.  So…  Is PhET planning migration support for the next release of these sims?  My recommendation is no. @samreid @zepumph your recommendation?

@arouinfar @kathy-phet FYI.

**Comment by kathy-phet** [comment]
Migration is only supported for these sims: 
Gravity And Orbits
Natural Selection
pH Scale
pH Scale: Basics
Molecule Polarity
Graphing Quadratics
Density

So no migration support. Closing!
