### ISSUE TITLE
Update QA credits for 1.7 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#302]
Update QA credits for 1.7 release.

beers-law-lab and concentration share credits via `BLLConstants.CREDITS`.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/qa/issues/894#issuecomment-1431423932, @Nancy-Salpepi said:
> Please add Liam Mulhall and Clifford Hardin to the QA credits.

**Comment by pixelzoom** [comment]
Credits have been updated in master and 1.7 branches.

In addition to the QA updates, I noticed that @arouinfar was not included in the credits, so I added her to "team".

**Comment by stemilymill** [comment]
looks good in beers law lab and concentration
