### ISSUE TITLE
Update Teacher Tips for 1.7 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#304]
The Teacher Tips were last updated in 2015 and could use some updating.

- [x] Update screenhots
- [x] Add query parameter table
- [x] % concentration is a mass percentage = mass solute/mass solution. We assume the solution has the density of water, 1 g/mL. Effectively, solution mass = mass solute (g) + volume solution (mL).

**Comment by arouinfar** [comment]
The Teacher Tips have been updated and are ready to upload to the website when 1.7 is published.

**Comment by pixelzoom** [comment]
@arouinfar 1.7 has been published, so you can proceed with this.

**Comment by arouinfar** [comment]
Done! Closing.
