### ISSUE TITLE
Update read-only metadata for a few properties

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#306]
For #296 

@pixelzoom let's update the following.

Make `phetioReadOnly: true`. Things can get strange if we let clients edit these.
- [x] `*.concentrationScreen.model.concentrationMeter.valueProperty`
- [x] `*.concentrationScreen.view.beakerNode.visibleProperty`
- [x] `*.concentrationScreen.view.removeSoluteButton.enabledProperty`

Make `phetioReadOnly: false`. Clients may want to position these with an API call.
- [x] `*.concentrationScreen.model.concentrationMeter.probe.positionProperty`
- [x] `beersLawLab.beersLawScreen.model.detector.probe.positionProperty`
- [x] `beersLawLab.beersLawScreen.model.ruler.positionProperty`

**Comment by pixelzoom** [comment]
Done. Back to @arouinfar for review in master.

**Comment by arouinfar** [comment]
@pixelzoom not sure if I missed it the first time or if it snuck in your commit, but I think `beersLawScreen.model.detector.body.positionProperty` should be read-only. The detector body isn't moveable so I don't know why we need to let clients move it. It doesn't serve any pedagogical purpose.

**Comment by pixelzoom** [comment]
Good catch, `detector.body.positionProperty` was unintentionally change in my commit.  Fixed in the above commit, back to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks! Master looks good, closing.
