### ISSUE TITLE
Add documentation to `percentConcentrationProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#307]
For #296 

There are a few methods for calculating concentration as a percentage (mass percent, volume percent, mass-volume percent). We should clarify that `percentConcentrationProperty` is a mass percentage. @pixelzoom can you please add this to the `phetioDocumentation`?

**Comment by pixelzoom** [comment]
Do you have specific wording that you'd like for `phetioDocumentation`?

**Comment by pixelzoom** [comment]
In Slack DM:

@arouinfar 
> Maybe just: Calculated as a mass percent.
> It has linked dependencies for the values, right?

@pixelzoom 
<img width="648" alt="screenshot_2145" src="https://user-images.githubusercontent.com/3046552/211939910-f01074fb-8f91-4a2f-94bb-a68d074149d8.png">

**Comment by pixelzoom** [comment]
Done in the above commit, see Studio screenshot below. @arouinfar please review, close if OK.

<img width="769" alt="screenshot_2146" src="https://user-images.githubusercontent.com/3046552/211940222-4ef8a319-be33-4c3c-91a3-9e463e8dd89b.png">

**Comment by arouinfar** [comment]
Looks good, thanks!
