### ISSUE TITLE
Add units to positionProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#309]
While working on https://github.com/phetsims/beers-law-lab/issues/306, I noticed that positionProperty is missing units in the model.

**Comment by pixelzoom** [comment]
Done, example below, "cm".   Origin is at the top-left of the layoutBounds (red rectangle with `?dev`).  Kind of weird that +y is down, but would be costly to change.   Distance/position units are not really important in the Concentration screen, but they are in the Beer's Law screen.  @arouinfar please review, close if OK.

<img width="590" alt="screenshot_2143" src="https://user-images.githubusercontent.com/3046552/211937835-470325cb-1d57-4a5b-89fb-477147319777.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The units look good.

> Kind of weird that +y is down, but would be costly to change. Maybe document in PhET-iO Guide?

No need to change the coordinate system, but this seems like something that could go in `phetioDocumentation`. Here's an example from Molecule Polarity:
> The position of this atom. (0,0) is at the upper-LEFT, +x is to the right, and +y is DOWN.

**Comment by pixelzoom** [comment]
This sim has a base class BLLMovable for all things that have a `positionProperty`.  Rather than hunt down every one of those and add (e.g.) "The position of the ruler. (0,0) is at the upper-LEFT, +x is to the right, and +y is DOWN.", I just added one generic description that will appear for all positionProperty -- see screenshot below.

Back to @arouinfar for review.

<img width="670" alt="screenshot_2147" src="https://user-images.githubusercontent.com/3046552/211944493-46ad1073-2c6a-4d79-8812-cb90246527fc.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom! The generic positionProperty documentation looks good to me.
