### ISSUE TITLE
Light beam still visible when laser is hidden

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#310]
Discovered while reviewing the phetioFeatured overrides for #305. Semi-related to #296.

If you set `view.lightNode.visibleProperty` to false while the light is on, the laser is hidden but the beam is still visible. This looks buggy to me.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/8419308/211944750-2b22873c-e991-48db-b119-b909794ac329.png">

Should we update `model.light.isOnProperty` to hide the beam in this situation? Clients would need to turn the light back on when they make the laser visible in the view again, but that seems reasonable.

**Comment by pixelzoom** [comment]
I'm not a fan of `visibleProperty` having side-effects like you've proposed.  Could we just make `view.lightNode.visibleProperty` be `phetioReadOnly: true`?  Is there any reason why the light should be hidden? This screen seems totally useless when there is no light.

**Comment by arouinfar** [comment]
Good point @pixelzoom. If clients want to prevent students from turning on the laser, they should just hide its on/off button. Let's make `view.lightNode.visibleProperty` be` phetioReadOnly: true` and `phetioFeatured: false`. I'll take care of the latter, back to you for the former.

**Comment by arouinfar** [comment]
Updated the overrides in the above commit.

**Comment by pixelzoom** [comment]
It occurred to me that we typically only instrument `visibleProperty` with `phetioReadOnly: false` when the visibility can actually change, and there's some value in the client being able to see if it's changed.  That's not the case here, so I uninstrumented `lightNode.visibleProperty` (via option `phetioVisiblePropertyInstrumented: false`) and it therefore no longer appears in Studio or the API.   

Back to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The tree looks good, closing.
