### ISSUE TITLE
sodiumChloride.formulaProperty is not a featured property

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#313]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
16.2

**Problem description**
For https://github.com/phetsims/qa/issues/889, when going through the examples https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/beers-law-lab/examples.md, the formulaProperty was a featured element for all of the solutes except for sodium chloride. I had to select "All" under PhET-iO elements in order to see it. 

**Visuals**
<img width="182" alt="Screenshot 2023-01-30 at 5 45 04 PM" src="https://user-images.githubusercontent.com/87318828/215614289-5d6db18a-a0f4-4d95-8e6a-603bd062a666.png">

**Comment by pixelzoom** [comment]
@arouinfar adjusted `phetioFeatured` in https://github.com/phetsims/beers-law-lab/issues/305.  She probably missed `sodiumChloride.formulaProperty` due to the mind-numbing repetative nature of setting up overrides.js.

**Comment by arouinfar** [comment]
> She probably missed `sodiumChloride.formulaProperty` due to the mind-numbing repetative nature of setting up overrides.js.

So true! 😆 

Thanks for the fix @pixelzoom.

**Comment by zepumph** [comment]
On it.

**Comment by zepumph** [comment]
Great catch @Nancy-Salpepi. Please confirm fixed in master on studio and feel free to close.

**Comment by Nancy-Salpepi** [comment]
Looks good in master. 
Closing.
