### ISSUE TITLE
Missing tandems for Text/RichText elements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#314]
For https://github.com/phetsims/qa/issues/889

Reviewing https://github.com/phetsims/beers-law-lab/issues/312 resulted in me identifying some Text/RichText elements that are not instrumented, along with a couple of other misc. things.

The tandems that I believe are missing are:

Text elements:

- [x] concentrationScreen.view.saturatedIndicator (SaturatedIndicator.ts)
- [x] concentrationScreen.view.saturatedIndicator.text (SaturatedIndicator.ts)
- [x] simPreferences.showSolutionVolumeCheckbox.text (BLLPreferencesNode.ts)
- [x] simPreferences.showSoluteAmountCheckbox.text (BLLPreferencesNode.ts)
- [x] simPreferences.beakerUnitsControl.radioButtonGroup.litersRadioButton.text (BeakerUnitlsControl.ts)
- [x] simPreferences.beakerUnitsControl.radioButtonGroup.millilitersRadioButton.text (BeakerUnitlsControl.ts)
- [x] simPreferences.concentrationMeterUnitsControl.radioButtonGroup.molesPerLiterRadioButton.text (ConcentrationMeterUnitsControl.ts)
- [x] simPreferences.concentrationMeterUnitsControl.radioButtonGroup.percentRadioButton.text (ConcentrationMeterUnitsControl.ts)

I'd like to confirm with @arouinfar before I instrument these.

**Comment by pixelzoom** [comment]
Confirmed with @arouinfar that the above need to be instrumented.

These do NOT need to be instrumented:

* beersLawScreen.view.solutionPanel.solutionComboBox.listBox.*.text
* concentrationScreen.view.solutePanel.soluteComboBox.listBox.*.text

**Comment by pixelzoom** [comment]
These:

> RichText elements:
> - [ ] concentrationScreen.view.solutePanel.soluteFormRadioButtonGroup.solidRadioButton.text (SolutionControl.ts)
> - [ ] concentrationScreen.view.solutePanel.soluteFormRadioButtonGroup.solutionRadioButton.text (SolutionControl.ts)

... turned out to be instrumented, but incorrectly named.  I changed the tandem name from 'labelText' to 'text', to match the pattern used for other radio buttons.

**Comment by pixelzoom** [comment]
These:

> RichText elements:
> - [ ] concentrationScreen.view.solutePanel.soluteFormRadioButtonGroup.solidRadioButton.text (SolutionControl.ts)
> - [ ] concentrationScreen.view.solutePanel.soluteFormRadioButtonGroup.solutionRadioButton.text (SolutionControl.ts)

... turned out to be instrumented, but incorrectly named.  I changed the tandem name from 'labelText' to 'text', to match the pattern used for other radio buttons.

**Comment by pixelzoom** [comment]
Over to @arouinfar to review, and let me know if she wants to feature any of these.  Feel free to close if no further changes are needed.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Everything looks good in master. The contents of `general.model.strings.beersLawLab` are featured by default. Since these new instances of text all have children linking back to the `StringProperty`, they'll show up in the tree when viewing featured elements. No need to feature the text itself.

**Comment by pixelzoom** [comment]
Reopening to confirm that these changes made it into 1.7 release branch.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment]
Confirmed that this change is present in 1.7. Closing.
