### ISSUE TITLE
PhET-iO API file is stale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#315]
For https://github.com/phetsims/qa/issues/889

Discovered while working on https://github.com/phetsims/beers-law-lab/issues/314, reported in Slack#phet-io.

I just made some changes to BLL (see https://github.com/phetsims/beers-law-lab/issues/314) that I expected to change the PhET-iO API.  I experienced no problems with pre-commit hooks, so I assumed my API file was being checked. Then  I ran `grunt generate-phet-io-api` and I’m surprised to see 100 or more changes that are not related to anything that I changed, and that look like this:

```diff
"beersLawLab-beersLawScreen-model-detector-pathLengthProperty": {
+ "_data": {
+   "initialState": {
+   "elementID": "beersLawLab.beersLawScreen.model.detector.pathLengthProperty"
+   }
+ },
```

Questions:
* What are these changes? 
* How did they happen when my sim is `phetioDesigned: true?` 
* Why are pre-commit hooks and CT not noticing that the API file needs to be regenerated?
* Is the API file out-of-sync in the dev version that was published for https://github.com/phetsims/qa/issues/889?

**Comment by pixelzoom** [comment]
I have a common-code change that I need to make (https://github.com/phetsims/scenery-phet/issues/796) that will change the API of sims that use ZoomButtonGroup or its subclasses. I'm hesitant to proceed with that work until this issue is resolved.

**Comment by zepumph** [comment]
Ahh, just typing this when you posted. phetioDesigned:true makes how you want api-comparison testing to be done (very strictly), but it doesn't tell CT to test it. You need to add it to this manually created list. I'm not really sure what a better process is. Last night I changed I was testing for an API change and realized it wasn't in that list and actually mistakenly thought, "oh, @pixelzoom must not be tracking things until we take it to RC." Otherwise I would have brought it up. Commit coming soon!

**Comment by zepumph** [comment]
I see changes for:

* when we brought back stateful LinkedElementIO elementIDs in https://github.com/phetsims/phet-io/issues/1903
* saturated indicator in https://github.com/phetsims/beers-law-lab/commit/3183271759a78414c0cae97b6a96282c21e6bf62
* Add phetioDesigned: true
* Beaker units sim preference UI
* A few minor phetioFeatured/phetioDocumentation/stateSchema updates

@pixelzoom will you please review.

**Comment by pixelzoom** [comment]
Ah yes... I forgot to add the sims to phet-io-api-stable.  Thanks for handling that.

Everything looks good. Closing.

**Comment by zepumph** [comment]
https://github.com/phetsims/perennial/commit/10cfa59b17c2f45c1e2f42aa09eed7491a8837fc did not fix this! That is an auto generated list (oops). Updating doc and fixing for good!
