### ISSUE TITLE
Size of "Evaporation" much smaller than in published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#318]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
Safari 16.2

**Problem description**
For https://github.com/phetsims/qa/issues/889, the size of the word "Evaporation" is much smaller in this version than in the Published. In Published, the words "Evaporation" and "Solute" are the same size.

From @arouinfar on Slack: 
>Looks like an unintended consequence of dynamic layout. My guess is that “Evaporation” doesn’t have an appropriate maxWidth and it is automatically shrinking to fit in the panel. I don’t see why we would intentionally make the text smaller than the published version. 

**Visuals**
<img width="391" alt="Screenshot 2023-01-31 at 4 05 01 PM" src="https://user-images.githubusercontent.com/87318828/215887529-25666027-db32-4d51-8278-b80129c73a43.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Laboratoire Loi de Beer-Lambert‬
URL: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet/beers-law-lab_all_phet.html
Version: 1.7.0-dev.8 2023-01-27 19:51:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
@pixelzoom would you like to investigate this?

**Comment by pixelzoom** [comment]
Fixed in the above commit. Screenshots below for normal and `stringTest=double`. @Nancy-Salpepi please review in master, close if OK.

<img width="1086" alt="screenshot_2224" src="https://user-images.githubusercontent.com/3046552/215894586-7d050124-cf00-4db3-8671-f0e23726b205.png">
<img width="1089" alt="screenshot_2225" src="https://user-images.githubusercontent.com/3046552/215894594-11a9f900-df60-49ea-b8aa-afe2e6dbc77d.png">

**Comment by samreid** [comment]
I noticed there is still a `    console.log( `labelText.width=${labelText.width}` );`

**Comment by pixelzoom** [comment]
Thanks. `console.log` removed.

**Comment by Nancy-Salpepi** [comment]
Looks good. Thanks!
Closing.

**Comment by pixelzoom** [comment]
Still fixed in 1.7. Closing.
