### ISSUE TITLE
Loading Studio with some nonexistent locales results in assertion errors

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#320]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/889, when appending the url for studio with a nonexistent locale, such as ty or tt, studio fails to load in English. Instead, I see assertion errors. This doesn't happen with all nonexistent locales--xx, xy, yy, oo --work correctly (the bad locale is ignored and studio opens in English).

This isn't specific to BLL. Also seen with latest pH Scale. 

**Steps to reproduce**
Add ?locale=ty to studio url

**Visuals**
<img width="714" alt="Screenshot 2023-02-01 at 10 00 57 AM" src="https://user-images.githubusercontent.com/87318828/216091323-88041ffe-71a5-4316-af71-244209d5608d.png">
<img width="714" alt="Screenshot 2023-02-01 at 10 01 15 AM" src="https://user-images.githubusercontent.com/87318828/216091378-fceb21cd-bae8-4227-b375-f3839699b5b3.png">

**Comment by samreid** [comment]
Fixed, closing.  We will discuss whether this needs to be cherry-picked into ph-scale: https://github.com/phetsims/ph-scale/issues/281

**Comment by pixelzoom** [comment]
Reopening to confirm in https://github.com/phetsims/qa/issues/894. It looks like changes I made during dev testing did not get into the 1.7 release branch.

@KatieWoe can you please test to see if this looks correct in 1.7.0-rc.1.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment]
This is not fixed in the 1.7 release branches. With URL
http://localhost:8080/studio/?sim=beers-law-lab&locales=*&keyboardLocaleSwitcher&phetioWrapperDebug=true&phetioElementsDisplay=all&locale=tt

> assert.js:28 Uncaught Error: Assertion failed: validation failed:
 Property value not valid: value not in validValues: tt
 prunedValidator:
 [object Object]
    at window.assertions.assertFunction (assert.js:28:13)
    at validate (validate.ts:25:17)
    at ReadOnlyProperty.ts:205:34
    at LocaleProperty.link (ReadOnlyProperty.ts:407:5)
    at new ReadOnlyProperty (ReadOnlyProperty.ts:205:12)
    at new Property (Property.ts:17:5)
    at new LocaleProperty (localeProperty.ts:45:1)
    at localeProperty.ts:58:24

**Comment by arouinfar** [comment]
The conclusion in https://github.com/phetsims/ph-scale/issues/274 was that there are no longer assertion errors for bad locales, regardless of the state of `phetioDebug`. This resulted in a change to the PhET-iO Guide which will need to be cherry-picked into the BLL and Concentration release branches.

https://github.com/phetsims/phet-io-sim-specific/commit/b3b518e231cfa737aa5e51b6533647c2f3f7ca11

**Comment by pixelzoom** [comment]
@KatieWoe @Nancy-Salpepi please reconfirm in 1.7.0-rc.2 for https://github.com/phetsims/qa/issues/894.

**Comment by Nancy-Salpepi** [comment]
This is fixed in 1.7.0-rc.2 for BLL and Concentration. Bad locales are ignored and there are no assertion errors in the console. 
Keeping open for https://github.com/phetsims/beers-law-lab/issues/320#issuecomment-1421106670.

**Comment by pixelzoom** [comment]
I guess I'll handle the remaining cherry-pick that's identified in https://github.com/phetsims/beers-law-lab/issues/320#issuecomment-1421106670.

**Comment by pixelzoom** [comment]
@jessegreenberg After @arouinfar identified the remaining cherry-pick in  https://github.com/phetsims/beers-law-lab/issues/320#issuecomment-1421106670, I see that you made a commit referencing this issue. The commit is https://github.com/phetsims/joist/commit/48a9d9aa11130504d35e34c98e3851607fd83599.  It appears to have only been committed to master, and not the beers-law-lab 1.7 branch.  Does it need to be patched into 1.7? 

Mentioning @samreid too, because his ID appears next to the commit above.

**Comment by pixelzoom** [comment]
@jessegreenberg I'm now doubled confused because https://github.com/phetsims/joist/commit/48a9d9aa11130504d35e34c98e3851607fd83599 was made to joist branch 'friction-1.6'.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/joist/commit/48a9d9aa11130504d35e34c98e3851607fd83599 is just a cherry-pick of https://github.com/phetsims/joist/commit/4889cfb3ae2b4a5ab9cdfdfc948a4b3660140cc5 for the 1.6 release of friction in https://github.com/phetsims/friction/issues/334.

**Comment by pixelzoom** [comment]
PhET-iO Guide change https://github.com/phetsims/phet-io-sim-specific/commit/b3b518e231cfa737aa5e51b6533647c2f3f7ca11 was cherry-picked to 1.7 branches for beers-law-lab and concentration in the above commits.  After building, I verified that this new sentence appears in the PhET-iO Guide:

> If you specify a locale for which a translation does not exist, the `locale` query parameter is ignored and the 
 simulation will retain the `localeProperty` used when creating the Standard PhET-iO Wrapper. 

Verification in the next RC should include:
* the problem reported in https://github.com/phetsims/beers-law-lab/issues/320#issue-1566354456
* the change to PhET-iO Guide shown in https://github.com/phetsims/phet-io-sim-specific/commit/b3b518e231cfa737aa5e51b6533647c2f3f7ca1

**Comment by stemilymill** [comment]
looks good
