### ISSUE TITLE
Should dropper have a fixed position?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#323]
Related to https://github.com/phetsims/qa/issues/889. 

This sim has all of the same problem with the movable dropper that we encountered in https://github.com/phetsims/ph-scale/issues/270.  Should we make the dropper also have a fixed position in this sim? Or is this sim somehow different because the shaker is (necessarily) movable?

My preference would be to also make the dropper have a fixed position here. Otherwise we'll be circling back to this when the sim gets alt input support.

**Comment by arouinfar** [comment]
> My preference would be to also make the dropper have a fixed position here. Otherwise we'll be circling back to this when the sim gets alt input support.

Yes, let's fix the position of the dropper @pixelzoom.

In case someone in the future questions this decision, the many reasons why the movable dropper was problematic in ph-scale are documented here: https://github.com/phetsims/ph-scale/issues/270#issuecomment-1398855808

**Comment by pixelzoom** [comment]
Next questions is where should the fixed position of the dropper be? The default when you start the sim is the first screenshot below.  I have a slight aesthetic preference for centering it between the faucet and right edge of the beaker, second screenshot below -- @arouinfar is that OK with you?

<img width="1087" alt="screenshot_2249" src="https://user-images.githubusercontent.com/3046552/216186506-7186ed3f-3991-4a5b-9561-c200fa1dc7d2.png">

<img width="1085" alt="screenshot_2250" src="https://user-images.githubusercontent.com/3046552/216186638-14cf6cc8-dcb9-4180-9700-bf112174e5fe.png">

**Comment by arouinfar** [comment]
Centered looks good to me @pixelzoom.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please have a look in master, close if OK.

I'm glad we're doing this for the first version of the sims to have API files, so we don't need a migration rule.

**Comment by arouinfar** [comment]
Looks good, thanks!

**Comment by pixelzoom** [comment]
Reopening to confirm in https://github.com/phetsims/qa/issues/894.   It looks like changes I made during dev testing did not get into the 1.7 release branch.

@KatieWoe can you please test to see if this looks correct in 1.7.0-rc.1.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment]
Still OK in 1.7 branch. Closing.
