### ISSUE TITLE
"Concentration" meter body should not be movable.

### ISSUE THREAD

**Issue by zepumph** [phetsims/beers-law-lab#324]
The probe makes sense to be movable. But in the spirit of #323 and others, let's remove the positionProperty for the meter's body.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good!

**Comment by pixelzoom** [comment]
Reopening to confirm in https://github.com/phetsims/qa/issues/894.   It looks like changes I made during dev testing did not get into the 1.7 release branch.

@KatieWoe can you please test to see if this looks correct in 1.7.0-rc.1.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment]
Looks OK in 1.7. Closing.
