### ISSUE TITLE
Move forward/backward should change the visible ordering in the combobox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#325]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari 16.2

**Problem description**
For https://github.com/phetsims/qa/issues/894, if I removed the two solutes (Co(NO3)2 and CoCl2) listed in the combobox after "Drink Mix," and then try to move "Drink Mix" down in the order, I have to press the down arrow three times before I see a change in the combobox order. 

@arouinfar said that this issue was addressed in pH scale but is part of common code. https://github.com/phetsims/ph-scale/issues/266

**Visuals**

https://user-images.githubusercontent.com/87318828/217344821-2bd4e91f-1ef6-472d-a566-f3762649aea4.mp4

**Comment by pixelzoom** [comment]
I'm guessing that this is a bug in ComboBoxListbox `keydown` handler.  Disappointing that this doesn't work, given that this was a primary reason for reworking ComboBox.  I'm going to defer to @samreid for fixing this.

**Comment by samreid** [comment]
I imagine this will be fixed by cherry picking https://github.com/phetsims/scenery/commit/6fe6985dd8b36346f224ee500f9cf1699f53f049

**Comment by pixelzoom** [comment]
@samreid That cherry-pick you're referring to was committed on 1/11/2023.  Why is it not in the RC?

**Comment by samreid** [comment]
I ran 

```
cd beers-law-lab
git checkout 1.7
grunt checkout-shas
```

Then I checked the history for scenery, and saw this:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/679486/217631601-d5ff5bff-acf2-4246-a8c4-a991ad87d893.png">

Note there are no commits from Jan 11, but plenty of commits afterwards.

Checking the history from master, I see the Jan 11 commit and the other nearby commits from @jessegreenberg:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/679486/217632418-6d7706fe-5b57-436e-8822-326a2c4d8e3b.png">

So the branch is somehow missing this commit.  How is this possible?  What else is it missing?

**Comment by samreid** [comment]
Oh wait, the dot for the Jan 11 commit is in the branch--you can see the dot is on the left. And it was not merged until Feb 3.  So likely we just don't understand why https://github.com/phetsims/scenery/commit/6fe6985dd8b36346f224ee500f9cf1699f53f049 says `master`.

**Comment by pixelzoom** [comment]
I don't understand. This issue was reported yesterday 2/7, and is therefore for 1.7.0-rc.2 -- after the shas in the 1.7 branch were fixed in https://github.com/phetsims/beers-law-lab/issues/327.   The sha that you're proposing to cherry-pick is dated 1/11/23.  How can that commit not be in the 1.7 release, and why do we think it's appropriate to cherry-pick it?

**Comment by pixelzoom** [comment]
Discussed with @samreid on Zoom.   Commit https://github.com/phetsims/scenery/commit/6fe6985dd8b36346f224ee500f9cf1699f53f049 was done in a branch 'carousel-dynamic', and it was not merged to master until after the 1.7 release branch was created.  So yes, it needs to be cherry-picked.  Labeling as such.

**Comment by samreid** [comment]
@pixelzoom would you like me to cherry pick this commit? And should I do that right away?

**Comment by pixelzoom** [comment]
I have a couple of other things to cherry-pick today, so I'll handle it.

**Comment by pixelzoom** [comment]
Cherry-picks completed for beers-law-lab 1.7 anf concentration 1.7 in the above commits.

To verify in the next RC:
* Follow the steps in https://github.com/phetsims/beers-law-lab/issues/325#issue-1574902766

**Comment by stemilymill** [comment]
looks good in beers law lab and concentration
