### ISSUE TITLE
Formulas incorrect with some locales

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#326]
**Test device**
MacBook Air and iPad

**Operating System**
13.1/16.3

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/894 on the Beer's Law Screen: The location of the subscripts and parenthesis in the formulas is incorrect with locales iw and ar_MA. Also, Potassium dichromate is the only formula written completely in reverse. Potassium chromate is also out of order, but in a different way. 

On the Concentration Screen, the formulas are displayed correctly on the Dropper/Shaker.

**Steps to reproduce**
1. Change the locale to iw or ar_MA
2. On the Beer's Law Screen, open the combobox

**Visuals**

<img width="400" alt="Screenshot 2023-02-08 at 9 16 45 AM" src="https://user-images.githubusercontent.com/87318828/217560957-8e58f542-559a-468b-8ef6-45a191641be1.png">

<img width="310" alt="Screenshot 2023-02-08 at 9 18 08 AM" src="https://user-images.githubusercontent.com/87318828/217560994-8421aded-bc8d-4f4e-a8e8-f1feba2dd7c6.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‫מעבדת חוק בר‬
URL: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.2/phet/beers-law-lab_all_phet.html
Version: 1.7.0-rc.2 2023-02-06 23:51:14 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1436x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. 

This looks like a case of https://github.com/phetsims/chipper/issues/1355 so we may need to consult with @jbphet and/or @jonathanolson.

**Comment by pixelzoom** [comment]
Yes, that's almost certainly the problem.  I'll investigate tomorrow.

**Comment by Nancy-Salpepi** [comment]
@pixelzoom The formulas look good on both screens. However, iw is the only locale where the solute names are written first in the combobox. All other locales have formula then name.

**Comment by arouinfar** [comment]
> However, iw is the only locale where the solute names are written first in the combobox.

There's a pattern that controls the order of the name and formula, which translators can separately control. Looks like `iw` chose to flip the pattern, so this is to be expected.

`beersLawLab.general.model.strings.beersLawLab.pattern.0Formula.1NameStringProperty`

**Comment by Nancy-Salpepi** [comment]
Thanks @arouinfar!

**Comment by pixelzoom** [comment]
Oops, I still need to cherry-pick this into the 1.7 branch. Self assigning.

**Comment by pixelzoom** [comment]
Cherry-pick completed in the above commit. Ready to verification in the next RC.

**Comment by pixelzoom** [comment]
I just remember that https://github.com/phetsims/beers-law-lab/commit/64a6d2a31ccdaba667a812b46d5334a3741e7998 did involve a change to the Concentation screen (the shaker label), so I'll need to cherry-pick into concentration 1.7.

**Comment by pixelzoom** [comment]
Cherry-pick completed in the above commit. Ready for verification in the next RC.

**Comment by pixelzoom** [comment]
To verify for beers-law-lab in the next RC:

(1) Run the sim in English. 
    * Go to the Beer's Law screen.  Inspect the items in the Solution combo box, verify that the labels look OK.
    * Go to the Concentration screen. Choose items from the Solute combo box. Verify that the shaker labels look OK.
(2) Run the sim with `locale=iw`, and repeat (1).

To verify for concentration in the next RC:

(3) Run the sim in English. 
    * Go to the Concentration screen. Choose items from the Solute combo box. Verify that the shaker labels look OK.
(4) Run the sim with `locale=iw`, and repeat (3).

**Comment by stemilymill** [comment]
looks good in beers law lab and concentration
