### ISSUE TITLE
1.7 release branch was created with old shas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#327]
This issue documents the 1.7 release branch problem, since it's not documented elsewhere.

The first indication that there was a problem with the 1.7 release branch was on 2/6/23, reported in https://github.com/phetsims/beers-law-lab/issues/317#issuecomment-1419784770.  A fix that I made during dev testing was not present in the 1.7.0-rc.1 build, and was present in master before the 1.7 release branch was created.

First, we paused QA testing of beers-law-lab 1.7.0-rc.1 (https://github.com/phetsims/qa/issues/894) and concentration 1.7.0-rc.1 ((https://github.com/phetsims/qa/issues/895).  I then re-opened issues for each change that was made during dev testing, and re-tested.  I confirmed that other fixes were not present in the RC, and that https://github.com/phetsims/beers-law-lab/issues/317 was not an isolated case. (This took a lot of time.)

Next @samreid @matthew-blackman and I investigated the 1.7 branch to identify the problem. Summary of what we discovered:

* The preceeding dev-test version was 1.7.0-dev.8, published by @matthew-blackman on 1/27/23 @ 12:51PM.
* The 1.7 release branch was created by @samreid on 2/3/23 @ 10:17AM. RC test version 1.7.0-rc.1 was published on 2/3/23 @ 10:28AM.
* Many changes to sim repos and dependencies were made between 1/27/23 and 2/3/23.
* The beers-law-lab 1.7 branch was incorrectly and unintentionally created with the same shas as 1.7.0-dev.8. We don't know how @samreid managed to do that.
* The concentration 1.7 branch is OK; it has the correct shas.

@samreid fixed the 1.7 branch by manually editing dependencies.json to have the shas that were current at the time that the 1.7 release branch was created.  @pixelzoom and @matthew-blackman supervised the manual editing.  @samreid commited the revised dependencies.json in https://github.com/phetsims/beers-law-lab/commit/2e1d628a637f0f92e7ed11c49a63c334a6d8b9be.

Finally, @samreid edited the existing 1.7.0-rc.1 QA issues, changing their names and links to 1.7.0-rc.2, and instructed QA to resume testing.  I expressed concerns about this shortcut: Imo, the right thing to do was to close the 1.7.0-rc.1 QA issues with a note, open new QA issues, and start a fresh test (not resume testing).  

@samreid feel free to add any details that I missed, then close.

**Comment by samreid** [comment]
Our foremost hypothesis was that I had branches checked out, or some incorrect configuration before running creation of rc.1 for beer's law lab.  However, @pixelzoom and I observed that the WebStorm local history indicated that I had recently pulled changes from master into my working copy directly before running the RC.1 creation.  I also recall using the same process for beers-law-lab and concentration, so it is still unclear what caused this problem.

I still want to understand https://github.com/phetsims/beers-law-lab/issues/325 better before closing.

**Comment by samreid** [comment]
Since we have (a) no explanation of what caused this problem and (b) no hypothesis as to what caused this problem and (c) other mysterious symptoms such as https://github.com/phetsims/beers-law-lab/issues/325#issuecomment-1423133911, it seems the safest thing to do would be to start over.  However, if testing is going well and all of the remaining work is well-isolated like https://github.com/phetsims/beers-law-lab/issues/325#issuecomment-1423133911, then it might be OK to continue and even publish after a few more cherry-picks. Maybe before we decide how to proceed, we should request analysis by someone that has more git expertise than I do?  I do not know how it would be possible to get all the commits surrounding the Jan 11 commit but not the Jan 11 commit itself.  Also, that commit was committed even before dev.8, so how was it not in dev.8 either?

**Comment by pixelzoom** [comment]
I'm OK to close. But I want to confirm that some lessons have been learned here:

(1) When you publish a version to give to QA, it should be spot checked, to confirm that it contains the expected fixed.

(2) When something goes wrong with a QA test issue, it's preferrable to close the issue and start a new one.  If you don't do that, then that creates potential confusion.  For example, when I see "For https://github.com/phetsims/qa/issues/894" in a beers-law-lab issue, I now have no idea if the issue was reported for 1.7.0-rc.1 or 1.7.0-rc.2.  And if I'm looking for the "RC test: Beer's Law Lab 1.7.0-rc.1" issue in the future, I'm not going to find it.

Feel free to close if you agree.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/phet-io-wrapper-lab-book/issues/13#issuecomment-1462544695, we also discovered that the version number in package.json was not updated.  It was still 1.7, and should have been updated to 1.8 when the 1.7 branch was created.  I manually changed it to 1.8 in https://github.com/phetsims/beers-law-lab/commit/7ff74ea1d7cb66a35ab221855d8cce43a6f4511d.
