### ISSUE TITLE
Uninstrument cuvetteNode.visibleProperty

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#328]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
chrome 110

**Problem description**

Discussed with @arouinfar on Slack 

For https://github.com/phetsims/qa/issues/894, on the Beer's Law Screen it is possible to set the `cuvetteNode.visibleProperty` to false. There is no reason to hide the cuvette (and the data from the detector still reads as though the cuvette is present). Is it possible to uninstrument  (or if not, to un-feature)?

This will also need to be deleted from the overrides file.

**Visuals**
<img width="756" alt="Screenshot 2023-02-08 at 4 14 15 PM" src="https://user-images.githubusercontent.com/87318828/217656943-60eb764a-7056-4f80-afb5-391ef232d58e.png">

**Comment by pixelzoom** [comment]
Yes, it's possible to uninstrument or unfeature `beersLawLab.beersLawScreen.view.cuvetteNode.visibleProperty`.  If there's no reason to hide it, I recommend uninstrumenting.   @arouinfar is that OK with you?

**Comment by pixelzoom** [comment]
While we're at it...  Is there any reason to hide the AT Detector? Should we also uninstrument `beersLawLab.beersLawScreen.view.detectorNode.visibleProperty`?

**Comment by arouinfar** [comment]
>  If there's no reason to hide it, I recommend uninstrumenting. @arouinfar is that OK with you?

Yes, uninstrumenting would be my preference. 

> While we're at it... Is there any reason to hide the AT Detector?

Hiding the detector doesn't lead to broken-looking situations like the cuvette or light #310, so we can probably leave it alone. It could be useful to temporarily hide for prediction purposes, but there are other alternatives (like moving probe out of the path). I don't have a strong feeling either way, so I'll let you make that call @pixelzoom.

**Comment by pixelzoom** [comment]
OK, I guess we'll keep `beersLawLab.beersLawScreen.view.detectorNode.visibleProperty` for its hypothetical usefulness.

`beersLawLab.beersLawScreen.view.cuvetteNode.visibleProperty` was uninstrumented in the above commits to master. So it no longer exists. See screenshot below. 

I still need to cherry-pick to 1.7.  That involves beers-law-lab and phet-io-sim-specific.

<img width="274" alt="screenshot_2296" src="https://user-images.githubusercontent.com/3046552/217664917-6263335d-89b8-419d-b565-fa26973cd894.png">

**Comment by pixelzoom** [comment]
Cherry-picks completed, ready for verification in next RC.

**Comment by pixelzoom** [comment]
Verification in the next RC should include the following for beers-law-lab only:

* Run the sim in Studio. Search for `cuvetteNode.visibleProperty`to verify that it no longer exists.

**Comment by stemilymill** [comment]
looks good
