### ISSUE TITLE
Locale switching should be available only in the all.html version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#329]
https://github.com/phetsims/chipper/issues/1378 identified a common-code problem with dynamic locale switching.  It should only be available for the all.html version, but is also available in all non-English locale-specific versions.

In Slack#dev-public....

@kathy-phet requested that the fix be patched into the 1.7 branches of beers-law-lab and concentration: 
>  is it easy to cherry pick this into BLL and Concentration for next rc?

@samreid identified the commits and confirmed with @jonathanolson:
> Probably would need at least these commits.  Not sure if this list is complete:
https://github.com/phetsims/joist/commit/8c41ace45a7f9a2c69b4756cff8746f2d27869a4
https://github.com/phetsims/chipper/commit/7d369d9216684ec860823c9947fc377608a569ab
https://github.com/phetsims/beers-law-lab/commit/0a4495502d89686b077ff99e661533160ec07c7f
https://github.com/phetsims/concentration/commit/8195733b43c4b4b23f944902bc8f9fa94be0f243
>
> @jonathanolson confirmed those are the commits we need

I'll handle the patch. 

This will need to be verified in the next RC, 1.7.0-rc.3.

**Comment by pixelzoom** [comment]
@kathy-phet asked if it's easy to cherry-pick this fix.  The answer is no. There are a bunch of manual steps, branches to be created, etc.    Here's my TODO list:

beers-law-lab:
- [ ] Cherry-pick https://github.com/phetsims/beers-law-lab/commit/0a4495502d89686b077ff99e661533160ec07c7f
- [ ] Create joist branch "beers-law-lab-1.7" and cherry-pick https://github.com/phetsims/joist/commit/8c41ace45a7f9a2c69b4756cff8746f2d27869a4
- [ ] Create chipper branch "beers-law-lab-1.7" and cherry-pick https://github.com/phetsims/chipper/commit/7d369d9216684ec860823c9947fc377608a569ab
- [ ] Regenerate and push dependencies.json

concentration
- [ ] Cherry-pick https://github.com/phetsims/concentration/commit/8195733b43c4b4b23f944902bc8f9fa94be0f243
- [ ] Checkout beers-law-lab branch "concentration-1.7" and cherry-pick https://github.com/phetsims/beers-law-lab/commit/0a4495502d89686b077ff99e661533160ec07c7f
- [ ] - [ ] Create joist branch "cncentration-1.7" and cherry-pick https://github.com/phetsims/joist/commit/8c41ace45a7f9a2c69b4756cff8746f2d27869a4
- [ ] Create chipper branch "concentration-1.7" and cherry-pick https://github.com/phetsims/chipper/commit/7d369d9216684ec860823c9947fc377608a569ab
- [ ] Regenerate and push dependencies.json

**Comment by pixelzoom** [comment]
> This will need to be verified in the next RC, 1.7.0-rc.3.

RC deploys do not include locale-specific versions other than English, and have no option for doing so.  Therefore this cannot be verified by QA.

@jessegreenberg suggested that I test with a local build:
> Not sure about `grunt rc`, but you could test with your SHAs with `grunt --brands=phet --locales=*` and opening a non-english sim and verifying that Localization tab in preferences is not present.

So in lieu of QA verification, I'll have another developer test with a local build.

**Comment by pixelzoom** [comment]
After patching in the commits identified in https://github.com/phetsims/beers-law-lab/issues/329#issuecomment-1431754801, I did local builds using:

`grunt build --brands=phet --locales=en,es,iw --allHTML`

Here's what I see for beers-law-lab (and similar for concentration):

No Localization tab in:
* locale-specific html files (beers-law-lab_en_phet.html, beers-law-lab_es_phet.html, beers-law-lab_iw_phet.html)
* beers-law-lab_en_iframe_phet.html
* beers-law-lab_all_phet_debug.html

Localization tab in:
* beers-law-lab_all_phet.html
* beers-law-lab_all_iframe_phet.html

Is this correct? beers-law-lab_all_phet_debug.html seems wrong.

@jessegreenber replied in Slack#dev-public
> I think that is wrong. I can't find how the debug file is created but it is probably missing a `window.phet.chipper.allowLocaleSwitching = true;`

@jonathanolson replied in Slack#dev-public:
> I’ll need to check buildRunnables to see if we’re passing the flag to the all-debug variety

**Comment by pixelzoom** [comment]
I reported the remaining problem with `all_phet_debug.html` https://github.com/phetsims/chipper/issues/1378#issuecomment-1431894728.  This issue is blocked and on-hold until that is resolved.

**Comment by pixelzoom** [comment]
Further patching of the 1.7 branches was completed in https://github.com/phetsims/chipper/issues/1378.  Unblocked.

**Comment by pixelzoom** [comment]
@samreid this is ready for verification.  To verify, follow these steps. While this is indeed tedious, verify all files - do not skip any files or steps.  Review is blocking for publication of the next RC.

For concentration:
1. cd perennial
2. grunt checkout-target --repo=concentration --target=1.7
3. cd concentration
4. grunt --brands=phet,phet-io --locales=es,en,iw --allHTML
5. Check html files in build/phet/. Confirm that "_all_" versions contain a Localization tab, and other versions do not.
6. Check html files in build/phet-io/. Confirm that "_all_" versions contain a Localization tab, and other versions do not.
7. Expand build/phet-io/concentration-phet-io-1.7.0-rc.2.zip. Confirm that "_all_" versions contains a Localization tab, and other versions do not.

Repeat steps 1-7 for beers-law-lab.

**Comment by samreid** [comment]
OK Beer's Law Lab is also good to go. This test for both sims took >= 30 minutes to iterate through every single case and add phetioStandalone as appropriate.

**Comment by pixelzoom** [comment]
Excellent thanks.  This issues cannot be tested by QA, but has been verified by another developer, so closing.

@samreid said:
> This test for both sims took >= 30 minutes to iterate through every single case and add phetioStandalone as appropriate.

Perhaps we should make it possible for QA to test something like this in RC?  A first step would be to add the `--locales` option to `grunt rc`. (Or maybe it's already supported but not documented?)

For my part, I'll also note that I've spent 3.5 hours on this issue and https://github.com/phetsims/chipper/issues/1378.

**Comment by pixelzoom** [comment]
@kathy-phet note that @samreid said:
> This test for both sims took >= 30 minutes to iterate through every single case and add phetioStandalone as appropriate.

For my part, I'll also note that I've spent 3.5 hours on this issue and https://github.com/phetsims/chipper/issues/1378.  The majority of that time was because https://github.com/phetsims/chipper/issues/1378 was not tested thoroughly before passing if off to me. And it would have been more efficient to have the person who made the fix do that patching, but no one stepped up to do that.
