### ISSUE TITLE
Missing dependencies for DerivedProperties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#333]
Reported in https://github.com/phetsims/axon/issues/441. 

This DerivedProperty in BeersLawSolutions is dependencies on `this.concentrationProperty.rangeProperty` and `this.solvent.colorProperty`, which are used in the derivation. (`concentrationProperty.rangeProperty` never changes in the sim currently, but could in the future.)

```js
    this.fluidColorProperty = new DerivedProperty(
      [ this.concentrationProperty, this.concentrationProperty.rangeProperty ],
      ( concentration, concentrationRange, solventColor ) => {
        let color = this.solvent.colorProperty.value;
        if ( concentration > 0 ) {
          const distance = Utils.linear( concentrationRange.min, concentrationRange.max, 0, 1, concentration );
          color = this.colorRange.interpolateLinear( distance );
        }
        return color;
      } );
```

**Comment by pixelzoom** [comment]
Fixed and tested in the above commit. Closing.

**Comment by pixelzoom** [comment]
Reopening.  2 new problems were discovered by @samreid, with a temporary workaround in https://github.com/phetsims/beers-law-lab/commit/308dae021080663fa6e437cdb526e2c7f6b0fe9d.  These usages of `accessNonDependencies: true` should be addressed.

**Comment by pixelzoom** [comment]
In ATDetector.ts, `getAbsorbanceAt` involves `solutionInCuvette.molarAbsorptivityProperty` and `solutionInCuvette.concentrationProperty`:

```ts
    this.absorbanceProperty = new DerivedProperty(
      [ pathLengthProperty, solutionInCuvette.absorbanceProperty ],
      ( pathLength, solutionInCuvetteAbsorbance ) =>
        ( pathLength === null ) ? null : solutionInCuvette.getAbsorbanceAt( pathLength ), {
```

In ATDetector.ts, `getTransmittanceAt` calls `getAbsorbanceAt`, which involves `solutionInCuvette.molarAbsorptivityProperty` and `solutionInCuvette.concentrationProperty`:

```ts
    this.transmittanceProperty = new DerivedProperty(
      [ pathLengthProperty, solutionInCuvette.transmittanceProperty ],
      ( pathLength, solutionInCuvetteTransmittance ) =>
        ( pathLength === null ) ? null : solutionInCuvette.getTransmittanceAt( pathLength ), {
```

In Beam.ts, `isProbeInBeam` involves `detector.light.isOnProperty`:

```ts
    this.shapeProperty = new DerivedProperty(
      [ this.visibleProperty, cuvette.widthProperty, detector.probe.positionProperty ],
      ( beamVisible, cuvetteWidth, probePosition ) => {
...
          const w = modelViewTransform.modelToViewDeltaX( detector.isProbeInBeam() ? probePosition.x - light.position.x : MAX_LIGHT_WIDTH ) + xOverlap;
...
        }
        else {
          return null;
        }
```

**Comment by pixelzoom** [comment]
The final use of `accessNonDependencies` is in ConcentrationSolution.ts, where `precipitateMolesProperty` depends on itself.   I don't believe that's actually a problem, but it's still being discussed in https://github.com/phetsims/axon/issues/441#issuecomment-1810592906.  So this issue is on hold until that's decided.

**Comment by zepumph** [comment]
I think this has caused a migration error because I haven't yet implemented an important rename feature for migration in https://github.com/phetsims/phet-io-wrappers/issues/537. Just noting it here and raising the priority of that issue.


```

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"beersLawLab.beersLawScreen.model.detector.absorbanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-absorbanceProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-detector-pathLengthProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-transmittanceProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [],
"expectedReportErrorNotFound": []
}
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/beers-law-lab/issues/333#issuecomment-1817588466, @zepumph is referring to the dependencies that were changed for ATDetector `absorbanceProperty` and `transmittanceProperty` in https://github.com/phetsims/beers-law-lab/commit/80d9cf3b11d66ae6f2aed51dc711d76362d8b0d2.   I'm not clear on why changes to dependencies for a DerivedProperty should require migration.

**Comment by pixelzoom** [comment]
The problem reported by @zepumph in https://github.com/phetsims/beers-law-lab/issues/333#issuecomment-1817588466 is being tracked in https://github.com/phetsims/beers-law-lab/issues/334.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/axon/issues/441#issuecomment-1861331455, @samreid and I said: 

> We decided that this complicates DerivedProperty unnecessarily. And self-reference should be something that is rarely done, possibly even to be avoided. In cases where it is necessary, the developer should opt out ...

So I'll continue to opt out using `accessNonDependencies: true` in this sim.  And I'll close this issue.
