### ISSUE TITLE
CT: MigrationReport problem: phetioIDNotInNewAPI

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#334]
Related to #333, CT reports:

```
beers-law-lab : migration : 1.7->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1700348764567/phet-io-wrappers/migration/?sim=beers-law-lab&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&oldVersion=1.7&migrationRate=5000&phetioMigrationReport=assert&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22migration%22%2C%221.7-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1700348764567%22%2C%22timestamp%22%3A1700349016766%7D
Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"beersLawLab.beersLawScreen.model.detector.absorbanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-absorbanceProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-detector-pathLengthProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-transmittanceProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [],
"expectedReportErrorNotFound": []
}
[object Object]
```

Originally reported by @zepumph in https://github.com/phetsims/beers-law-lab/issues/333#issuecomment-1817588466:

> I think this has caused a migration error because I haven't yet implemented an important rename feature for migration in https://github.com/phetsims/phet-io-wrappers/issues/537. Just noting it here and raising the priority of that issue.

**Comment by pixelzoom** [comment]
This was caused by https://github.com/phetsims/beers-law-lab/commit/80d9cf3b11d66ae6f2aed51dc711d76362d8b0d2, where dependencies were changed for DerivedProperties in ATDetector ,`absorbanceProperty` and `transmittanceProperty`.   I'm not clear on why changes to dependencies for a DerivedProperty should require migration.

**Comment by zepumph** [comment]
This was originally caused by the changes to DerivedProperty dependencies in commits like https://github.com/phetsims/beers-law-lab/commit/80d9cf3b11d66ae6f2aed51dc711d76362d8b0d2.

This has been solved by https://github.com/phetsims/phet-io-wrappers/commit/354ca6e5b1a0df63a64445e1e7498111544c34be over in https://github.com/phetsims/phet-io-wrappers/issues/536. We could have added delete-uninstrumented processors, but these are LinkedElementIOs, and so we don't want to have to care about them at all. Let's make the migration report work for us! And not the other way around. I'll check back to confirm CT is fixed.

**Comment by pixelzoom** [comment]
CT seems to be happy, so I'll close this.
