### ISSUE TITLE
Changing locale using localeProperty can cause an open combo box to become misaligned

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#336]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari, Chrome and Firefox

**Problem description**

While testing https://github.com/phetsims/qa/issues/1106 I noticed that changing locales while the combo box is open on either screen can cause the combo box to shift. Closing the box and reopening fixes the problem. 
The problem doesn't occur if the locale is changed while the combo box is closed. 

This seems specific to Beer's Law and Concentration. I didn't see this issue with pH Scale or Molecule Scapes using studio. 

**Steps to reproduce**
1. Open Studio and go to the Concentration Screen
2. Open the combo box
3. Go to `localeProperty` and switch between ar_SA, ar_MA and ar while the box is open. (Another example is "zu" to "it")

**Visuals**
<img width="245" alt="Screenshot 2024-07-11 at 9 33 03 AM" src="https://github.com/phetsims/beers-law-lab/assets/87318828/b5ad3512-193a-409e-8415-b880d89f364e">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi can you reproduce this in other sims, or is it specific to Beer's Law Lab?

I suspect that this is not specific to Beer's Law Lab and is a general issue with ComboBox. If that's the case, then this issue should be transferred to sun and assign to @jonathanolson (who did the dynamic layout for ComboBox.)

**Comment by Nancy-Salpepi** [comment]
I wasn't able to reproduce with other PhET-iO sims in the MR (see original comment). 
I just tried on main and I see that the issue is fixed.....which I should have checked. 
Sorry. Closing.

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi!  I thought this looked familiar :)
