### ISSUE TITLE
According to Color.js, lightGray is not a color

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#84]
Perhaps we should use lightgrey instead?

See ConcentrationControl and WavelengthControl.

**Comment by samreid** [comment]
Same question for scenery-phet/js/ShadowText.js

**Comment by pixelzoom** [comment]
I'll search and fix. But..

This is a porting error. lightGray is defined for java.awt.Color.  Likely to happen again, given how many times java.awt.Color is used in PhET Java sims. *HIGHLY* recommend to define all Java colors in scenery.Color. Or perhaps create scenery-phet.PhetColors.

A couple of other observations about scenery.Color:

• It's not using HTML5 color names, http://www.w3schools.com/html/html_colornames.asp

• It defines lightgrey and LIGHT_GRAY (note the difference in spelling, 'e' vs 'A'). Recommended to make this consistent.

Assigning to @jonathanolson for comment.

**Comment by pixelzoom** [comment]
Hmm... @samreid flagged 'lightGray' as incorrect, but it's working in BLL.ConcentrationControl and BLL.WavelengthControl.  Can someone clarify?...

**Comment by pixelzoom** [comment]
HTML color names are case insensitive. 'lightGray' is a valid color name. See http://www.w3schools.com/html/html_colornames.asp.  This confusion seems to be caused by the fact that scenery.Color doesn't define all supported HTML5 colors.

**Comment by jonathanolson** [comment]
Missing colors from http://www.w3.org/TR/css3-color/, I'll fix that. Notably, CSS defines both 'gray' and 'grey' variants.

Re: LIGHT_GRAY, this is meant for Java porting, and is unrelated to the CSS colors. I'll also check Java's Color for things we could be missing.

**Comment by jonathanolson** [comment]
Looks like we will be adding:
darkgrey
darkslategrey
dimgrey
grey
lightgray
lightslategrey
slategrey

Changing color values for:
mediumpurple
palevioletred

Removing colors:
feldspar
violetred

I'll be checking for usages of changed/removed colors before applying the CSS fixes.

**Comment by jonathanolson** [comment]
Fixed, reassigning to @pixelzoom to see if there's anything else to do.

**Comment by pixelzoom** [comment]
Looks good to me. Assigning to @samreid to take a peek, since he reported this.

**Comment by samreid** [comment]
I tested BLL under pixi again and no longer saw the problem, thanks!  Closing.

**Comment by pixelzoom** [comment]
Ah... I had no idea this was manifesting as a problem under Pixi.
