### ISSUE TITLE
Create a prototype "sonification" version of the Concentration sim

### ISSUE THREAD

**Issue by jbphet** [phetsims/beers-law-lab#85]
As part of the work towards accessibility, I've been asked to create a prototype version of the Concentration simulation (which is a subset of Beer's Law Lab) that includes sonification, meaning audio cues and feedback for the various actions that the user can perform.  This will be done on a branch named "sonification-prototype".

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/beers-law-lab/issues/88.

**Comment by jbphet** [comment]
This isn't really a duplicate of #88.  That one is that standard issue about why a branch exists, this is to track the request.  Or it was - the work is done on that.

For reference, here's a link to a published dev version of the concentration sim with prototyped sound: https://phet-dev.colorado.edu/html/concentration/1.2.0-sonification.3/concentration_en.html.
