### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#86]
While adding API features to Concentration, I noticed that many properties do not have Property suffix:

```js
    thisShaker.visible = new Property( visible );
    thisShaker.empty = new Property( false );
    thisShaker.dispensingRate = new Property( 0 );
```

This made things a little confusing when trying to isolate properties for api instrumentation.

**Comment by pixelzoom** [comment]
This was brought up long ago, and we decided it wasn't worth the effort, see https://github.com/phetsims/beers-law-lab/issues/78.  Happy to re-discuss.

**Comment by pixelzoom** [comment]
This was brought up twice before (#6, #78) and we decided that it would be too destabilizing. Happy to re-discuss.

**Comment by samreid** [comment]
It looks like Movable.locationProperty is the only var with Property suffix in Beers Law Lab/Concentration.  I don't feel too strongly about adding suffixes, but let's discuss on Monday.

**Comment by samreid** [comment]
I should also note (as a reminder for discussion): I have been adding some properties as part of the public API for https://github.com/phetsims/concentration/issues/34, and I have been using *Property suffix.  (This is consistent with the PhET Style Guidelines but inconsistent with the majority of the rest of the sim).  I don't feel strongly that they remain that way, but just want to discuss it.

**Comment by pixelzoom** [comment]
Repos where this convention is violated. Are we going to fix them all?...

area-builder
balancing-act
beers-law-lab
bending-light
build-a-molecule
build-an-atom
energy-forms-and-changes
forces-and-motion-basics
gravity-and-orbits
scenery-phet
sugar-and-salt-solutions
under-pressure

**Comment by pixelzoom** [comment]
Discussed with @samreid. Since this has come up 3x, I'll go ahead and do it.  And it should be done for all other sims.  I will defer until @samreid is done with https://github.com/phetsims/concentration/issues/34.

**Comment by pixelzoom** [comment]
@samreid concentration still has a 'together' branch.

**Comment by pixelzoom** [comment]
Note to self... Remaining files to fix:

Absorbance
BeersLawModel
BeersLawSolution

**Comment by pixelzoom** [comment]
Done. This was a brutal refactor, took 4+ hours. Definitely not worth the effort. I'll be amazed if I didn't break something.  

Closing.
