### ISSUE TITLE
Use together API for addComponent/removeComponent

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#87]
See https://github.com/phetsims/concentration/issues/34

Many simulation components are created dynamically, and we need a nice way to handle them regarding the together API.  @pixelzoom & I discussed creating an addComponent/removeComponent API to phet.together that will manage that.  I'll create a new branch `together` for beers-law-lab for working on this.

**Comment by samreid** [comment]
Initial work committed above, this approach seems promising so far.  Save/load/record/playback/queryParameters/archstreams all seem like they will work as well as in the previous "batched" methodology.  Still need to address dynamic components here.

**Comment by pixelzoom** [comment]
@samreid what else needs to be done here?

**Comment by samreid** [comment]
The sim has been converted to use the together.addComponent paradigm, so this seems good to go.  Closing.
