### ISSUE TITLE
rework SoluteFormNode for together instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#89]
Address issue that was created by together instrumentation, in SoluteFormNode:

```
// TODO: This should be the fundamental property, and shaker visible/dropper visible should derive from this
var soluteFormProperty = new Property( dropper.visible.value ? 'liquid' : 'solid', { componentID: 'concentrationScreen.soluteForm' } );

```

**Comment by pixelzoom** [comment]
Above TODO was added by @samreid.

**Comment by samreid** [comment]
Yes, it is very awkward in the data stream how the radio button toggles the visibility of the dropper, and that toggles the model for which solute form is selected.  It should be the other way around.

**Comment by pixelzoom** [comment]
Moved soluteFormProperty to ConcentrationModel (good thing componentID is decoupled from implementation route!)  Assigning to @samreid to verify that this didn't break any of the together examples. I recall one example that hides either the shaker or dropper radio button, but didn't see an easy way to test that.

**Comment by pixelzoom** [comment]
Btw... Just wanted to point out that there is some redundancy and incompleteness related to this in concentration-api.js.

These 2 control the same thing:

'concentrationScreen.soluteForm': { type: property( String ), values: [ 'liquid', 'solid' ] },
'concentrationScreen.dropper.visible': { type: property( Boolean ) },

And there is no 'concentrationScreen.shaker.visible'.  Perhaps it should be added. Or perhaps concentrationScreen.dropper.visible' should be deleted, since 'concentrationScreen.soluteForm' does the same thing.

**Comment by samreid** [comment]
I tested configuration and data streaming and did not see any issues, thanks.
