### ISSUE TITLE
branch: together-values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#92]
Branch created for exploring how to set values for things that are not Number, String, Boolean (e.g., Solute in Concentration).

This branch is expected to be (possibly) merged to master, then deleted.

**Comment by pixelzoom** [comment]
Notes from our discussion are in https://github.com/phetsims/concentration/issues/38.

**Comment by samreid** [comment]
I just used this branch as inspiration and worked directly in master.  Branch is now deleted.  Closing.
