### ISSUE TITLE
issues related to "solute form" in concentration-api.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#93]
Related to #89, addition of soluteFormProperty.

There is some redundancy and incompleteness related "solute form" in concentration-api.js.

Redundancy: These 2 entries control the same thing:

```
'concentrationScreen.soluteForm': { type: property( String ), values: [ 'liquid', 'solid' ] },
'concentrationScreen.dropper.visible': { type: property( Boolean ) },
```

Incompleteness: There is no 'concentrationScreen.shaker.visible'.  Perhaps it should be added. Or perhaps concentrationScreen.dropper.visible' should be deleted, since 'concentrationScreen.soluteForm' does the same thing. (Why have 3 entries when 1 is sufficient?)

**Comment by samreid** [comment]
Yes, now that #89 is complete, I think we can just put soluteForm in the together-API.

**Comment by samreid** [comment]
Removed dropper.visible above, anything else to do here?

**Comment by pixelzoom** [comment]
Looks good, closing.
