### ISSUE TITLE
Review changes in Solute.js related to together.js refactoring

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#94]
@pixelzoom I thought you would probably want to review changes in https://github.com/phetsims/beers-law-lab/commit/95a5c7fb22460cf8a7322ef739f599fe19b78d8f for Solute.js.  Particularly: the Solute constructor signature previously allowed several optional arguments--I revised them to be an options argument so the componentID could be passed through options as well.

**Comment by pixelzoom** [comment]
Looks good, thanks for doing that. I changed the formatting a bit.

One question about this:

> 55 together && together.addComponent( this );

Since componentID is optional, shouldn't it be this?:

> options.componentID && together && together.addComponent( this );

**Comment by samreid** [comment]
> Since componentID is optional, shouldn't it be this?:

We have been putting componentID in options for compatibility with sims that are not instrumented yet.  In the future, will we want componentID to be required?

Also, I have been thinking of componentID as required when together!==null.

**Comment by pixelzoom** [comment]
I don't think we want componentID to be required. If it's in a common-code component, we may or may not want to instrument that component depending on the instrumentation needs of a sim.  For example, if it's redundant to instrument a specific component, we may choose to not instrument it in some sim.  So I think it's very appropriate that its an option (not just for compatibility with sims that aren't instrumented). And where it is an option, the component should be added like:

> options.componentID && together && together.addComponent( this );

or this variation if it's more relevant:

> this.componentID && together && together.addComponent( this );

**Comment by samreid** [comment]
Sounds good to keep componentID in options.  This is critical for common code components anyways.

However, for items that *must* be instrumented, such as user interface components, I think it is appropriate to use:

```js
together && together.addComponent(this);
```

without a check for componentID.  This will cause an assertion error in together.addComponent.  This makes it very easy to identify components that still need to be instrumented.  For items like Properties which are not necessarily bound to together, it can use a check like:

```js
this.componentID && together && together.addComponent(this);
```

**Comment by pixelzoom** [comment]
Sounds good. So what about Solutes, shall they be truly optional or required? (Thinking ahead to the possibly of reusing these Solutes in the [possible] scaled-down version of Concentration that you mentioned yesterday.)

**Comment by samreid** [comment]
For Concentration and the new Concentration Sim, whenever together!==null, we will want Solutes to report to the API--(may just need different componentIDs to be assigned to them based on their context), so we should omit the check for componentID in this case.

**Comment by pixelzoom** [comment]
Sounds good. Closing.
