### ISSUE TITLE
branch: tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#97]
see https://github.com/phetsims/together/issues/85

**Comment by pixelzoom** [comment]
@samreid Please comment on whether this branch is still necessary.

**Comment by samreid** [comment]
@jbphet can we remove this branch now?

**Comment by jbphet** [comment]
I haven't done anything with this branch, and it looks like it basically hasn't been touched since April.  I will delete it.

**Comment by jbphet** [comment]
Okay, branch removed.  Closing.
