### ISSUE TITLE
Reinstrument using tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#98]
This simulation has been somewhat of a "guinea pig" for experimentation with together.js instrumentation.  The next "experiment" is instrumentation using the tandem strategy decsribed in https://github.com/phetsims/together/issues/85 .  This issue is to track commits and make it easy and review to see what has changed.

**Comment by samreid** [comment]
Commits on beers-law-lab and concentration are above.  Common library commits forthcoming, and will also be tracked in this issue.

**Comment by samreid** [comment]
@jbphet & I finished converting concentration and its dependencies to use tandem for together.js support.  All change sets notes above.  @pixelzoom do you wish to review?

**Comment by pixelzoom** [comment]
Yes, I wish to review.  Any general information that you want to give me describing the approach, or should I try to figure out the approach from the change sets?

**Comment by jbphet** [comment]
This is pretty much what we discussed at yesterday's developer meeting, so you should be fully equipped to jump in.

**Comment by samreid** [comment]
> Any general information that you want to give me describing the approach, or should I try to figure out the approach from the change sets?

Just to elaborate: tandem instances will be passed through the sim.  Tandems are required in sim code and optional in library code.  tandem.addInstance() will be done in the most general place possible, such as sun components.  When creating a new kind of component, it will register with tandem using tandem.addInstance manually.  Tandem.createTandem() is used to create a new "context" for associating ids with user elements.  More elaboration is in phetsims/together#85

**Comment by pixelzoom** [comment]
I spot checked in beers-law-lab, looks great.  General comments about tandem are in https://github.com/phetsims/together/issues/85.  Closing this issue.
